In [37]:
#imports
%matplotlib inline
%config InlineBackend.figure_format = 'retina' # high res plotting

import sys
sys.path.append('spikeparam')

from spikeparam.patch.fit import Spike
from spikeparam.patch.fit import SpikeGroup

from neurodsp import spectral

from scipy import signal
import scipy

import h5py
from tqdm import tqdm

import numpy as np
import pandas as pd

from neurodsp import filt
from neurodsp.timefrequency import amp_by_time, phase_by_time
from neurodsp.plts import plot_time_series, plot_instantaneous_measure
from neurodsp.plts.time_series import plot_bursts
from neurodsp.burst import detect_bursts_dual_threshold, compute_burst_stats

from scipy.signal import sosfiltfilt, butter

from scipy.signal import find_peaks
from scipy.optimize import curve_fit
from scipy.stats import pearsonr
import statsmodels.api as sm
from sklearn.metrics.pairwise import cosine_similarity

import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import scipy.spatial as sp_spatial

import os

from fooof import FOOOF

sns.set(rc={'figure.figsize':(12,9)})
sns.set_style('whitegrid')
sns.set_style("whitegrid", {'axes.grid' : False})

import IProgress

import openpyxl

## Defining useful functions

In [5]:
# Function to visualize sweep patch data
# no metadata, just the time series data
def extract_data(file_path, plot_data = False):
    # Open the HDF5 file
    with h5py.File(file_path, 'r') as f:
        # Initialize an empty list to store data arrays
        data = []

        # Iterate through keys in the 'acquisition' group
        for sweep_key in f['acquisition'].keys():
            dataset = f['acquisition'][sweep_key]['data'] 
            # Convert the dataset data into a NumPy array and append to the list
            data.append(np.array(dataset))

        # Plot the data
        if(plot_data):
            if all(d.ndim == 1 for d in data):
                for d in data:
                    plt.plot(d)
                plt.xlabel('time (ms)')
                plt.ylabel('mV')
                plt.title('1D Dataset Visualization')
                plt.show()
            elif all(d.ndim == 2 for d in data):
                for d in data:
                    plt.imshow(d, cmap='viridis')
                    plt.colorbar()
                    plt.xlabel('X-axis')
                    plt.ylabel('Y-axis')
                    plt.title('2D Dataset Visualization')
                    plt.show()
            else:
                print("Cannot visualize data with more than 2 dimensions.")



        return data

In [6]:
#collecting file paths

def get_file_paths(folder_path):
    """
    Function to loop through a folder and save file paths.
    
    Args:
    - folder_path (str): Path to the folder to loop through.
    
    Returns:
    - file_paths (list): List of file paths found in the folder.
    """
    file_paths = []
    for root, dirs, files in os.walk(folder_path):
        for file in files:
            file_paths.append(os.path.join(root, file))
    return file_paths

In [58]:
def update_columns_at_index(df, file_path, index):
    """
    Function to update columns in the DataFrame at a specific index with values from Excel metadata.
    
    Check if filename matches the string in the first cell of the row, drop row if not.

    Args:
    - df (pd.DataFrame): DataFrame to update.
    - file_path (str): Path to the Excel file containing metadata.
    - index (int): Index at which to update the columns.
    
    Returns:
    - df (pd.DataFrame): Updated DataFrame.
    """
    # Extract filename from file_path
    filename = os.path.splitext(os.path.basename(file_path))[0]
    
    # Load the workbook
    wb = openpyxl.load_workbook(r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\ephys_features_filenames (1).xlsx")
    # Select the active worksheet
    ws = wb.active
    
    # Extract the value from the first cell of the row
    first_cell_value = ws.cell(row=index, column=1).value
    
    # Check if filename matches the string in the first cell of the row
    if filename != first_cell_value:
        # Drop the row if they don't match
        #df.drop(index, inplace=True)
        return False
    
    # Extract column names from the first row of the Excel sheet
    column_names = [cell.value for cell in ws[1]]
    
    # Extract data from the specified row of the Excel sheet
    data_row = next(ws.iter_rows(min_row=index, max_row=index, values_only=True))
    
    # Update DataFrame columns at the specified index with new data
    for column_name, value in zip(column_names, data_row):
        df[column_name] = value
    
    return True

# Example usage:
# Assuming df is the DataFrame to update
# file_path is the path to the Excel file containing metadata
# and index is the index at which to update the columns

# df = update_columns_at_index(df, file_path, index)

In [57]:
def monkey_df(filepaths, ind_start):
    # iterate through each file, 
    # create a spike object and add the data frame from the object, plus a label from the sweep
    # add a label for a file and move to the next file (mega df)
    # mega df is the file data frame while super mega df is the monkey data frame
    super_mega_df = pd.DataFrame()
    index = ind_start
    for file in filepaths:
        print(file)
        data = extract_data(file, plot_data = False) #numpy array of all sweeps in the file
        spike_dir = {}                               #dictionary of sweeps with spikes
        i = 0
        #threshold in mVs
        with h5py.File(file, 'r') as f:
            for sweep_key in f['acquisition'].keys():
                if i < len(data):
                    try:
                        sweep_key_obj = Spike(thresh_amp=0, window_length=(5., 5.), smooth_frac=.01)
                        sweep_key_obj.fit(data[i], 20000, n_jobs=-1, progress=tqdm)
                        if sweep_key_obj.n_spikes is not None:
                            spike_dir[sweep_key] = sweep_key_obj
                    except ValueError as e:
                        print(f"Fitting failed for sweep {sweep_key}: {e}")
                i += 1
        # creating and concatenating data frame with all sweeps
        mega_df = pd.DataFrame()
        for i in spike_dir:
            print(i)
            df = spike_dir[i].df_features
            df['Sweep_#'] = i
            mega_df = pd.concat([mega_df, df], axis=0)
        exists = update_columns_at_index(mega_df, file, index)
        if exists:
            super_mega_df = pd.concat([super_mega_df, mega_df], axis=0)
            index += 1
            print("file added")
        
    return super_mega_df

In [18]:
# Functions to save a datrame to a pickle file and another to extract the data from the pickle file

def save_dataframe_to_pickle(dataframe, file_path):
    """
    Function to save a DataFrame as a pickle file.
    
    Args:
    - dataframe (pd.DataFrame): DataFrame to be saved.
    - file_path (str): Path to save the pickle file.
    """
    dataframe.to_pickle(file_path)

def load_dataframe_from_pickle(file_path):
    """
    Function to extract a DataFrame from a pickle file.
    
    Args:
    - file_path (str): Path to the pickle file.
    
    Returns:
    - dataframe (pd.DataFrame): Loaded DataFrame.
    """
    dataframe = pd.read_pickle(file_path)
    return dataframe

## Extracting Data

**M03**

In [12]:
file_paths = get_file_paths(r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03")
M03_df = monkey_df(file_paths, 2)

save_dataframe_to_pickle(M03_df, r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03_df.pkl")

C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_JS_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:04<00:00,  2.11it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 42/42 [00:04<00:00,  9.62it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 43/43 [00:04<00:00,  9.69it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 59/59 [00:04<00:00, 13.10it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 67/67 [00:04<00:00, 14.38it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.44s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.75it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_54
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_JS_A1_C03.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 46/46 [00:04<00:00, 10.34it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 108/108 [00:04<00:00, 23.94it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 128/128 [00:04<00:00, 28.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 150/150 [00:04<00:00, 32.90it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 166/166 [00:04<00:00, 34.97it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.48s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_38
Sweep_39
Sweep_40
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_JS_A1_C04.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 69/69 [00:04<00:00, 15.20it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 80/80 [00:04<00:00, 17.69it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 89/89 [00:04<00:00, 19.36it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 98/98 [00:04<00:00, 20.88it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 108/108 [00:04<00:00, 23.15it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.64it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 37/37 [00:04<00:00,  8.29it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 54/54 [00:04<00:00, 12.01it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.96s/it]

Sweep_10
Sweep_101
Sweep_102
Sweep_103
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_7
Sweep_8
Sweep_9
Sweep_98
Sweep_99
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_JS_A1_C06.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.37s/it]

Fitting failed for sweep Sweep_1: All fits failed.

Spike: 100%|███████████████████████████████████████████████████████████████████████████| 69/69 [00:04<00:00, 15.09it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 84/84 [00:04<00:00, 18.81it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 95/95 [00:04<00:00, 21.20it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 107/107 [00:04<00:00, 22.74it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 117/117 [00:04<00:00, 25.77it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.07it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 36/36 [00:04<00:00,  8.11it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 58/58 [00:04<00:00, 12.91it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_36
Sweep_39
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_JS_A1_C10.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 59/59 [00:04<00:00, 13.20it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 115/115 [00:04<00:00, 25.39it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13
Sweep_14
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_JS_A1_C14.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.81s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12
Sweep_13
Sweep_14
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_JS_A1_C18.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 34/34 [00:04<00:00,  7.40it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 38/38 [00:04<00:00,  8.34it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 40/40 [00:04<00:00,  8.90it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 42/42 [00:04<00:00,  9.01it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 41/41 [00:04<00:00,  9.05it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.54it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:04<00:00,  5.31it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 30/30 [00:04<00:00,  6.63it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_59
Sweep_60
Sweep_61
Sweep_62
Sweep_63
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_JS_A1_C19.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 49/49 [00:04<00:00, 10.76it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 40/40 [00:04<00:00,  9.01it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 27/27 [00:04<00:00,  6.10it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 26/26 [00:04<00:00,  5.77it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.50it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.44s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.43it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.95it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 34/34 [00:04<00:00,  7.46it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_61
Sweep_62
Sweep_63
Sweep_64
Sweep_65
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_JS_A1_C20.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 38/38 [00:04<00:00,  8.25it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 42/42 [00:04<00:00,  9.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 46/46 [00:04<00:00, 10.46it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 49/49 [00:04<00:00, 10.91it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 34/34 [00:04<00:00,  7.51it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.18it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:04<00:00,  5.10it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 31/31 [00:04<00:00,  6.74it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_MW_A1_C03.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.15it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.48it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.54it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:04<00:00,  3.95it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:04<00:00,  4.17it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.75it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.35it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_MW_A1_C04.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.53it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.23it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:04<00:00,  3.89it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.87it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:06<00:00,  3.49it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.91s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.96s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.06it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_45
Sweep_46
Sweep_50
Sweep_51
Sweep_52
Sweep_53
Sweep_54
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_MW_A1_C06.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.53it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:04<00:00,  4.30it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:05<00:00,  3.64it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:06<00:00,  3.64it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:06<00:00,  3.80it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.06it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.51it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_MW_A1_C08.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  3.38it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:05<00:00,  2.78it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:06<00:00,  2.69it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:06<00:00,  3.41it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:06<00:00,  3.96it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.48s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 1/1 [1:33:49<00:00, 5629.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:01<00:00,  3.45it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.84it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_7
Sweep_70
Sweep_72
Sweep_74
Sweep_75
Sweep_76
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_MW_A1_C09.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.85s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.09it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.56it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.36it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.93s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.58s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_52
Sweep_53
Sweep_55
Sweep_56
Sweep_57
Sweep_58
Sweep_59
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_MW_A1_C10.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13
Sweep_14
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_MW_A1_C11.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.48it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.42it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.58it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:04<00:00,  4.02it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.10it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_105
Sweep_107
Sweep_108
Sweep_109
Sweep_11
Sweep_110
Sweep_111
Sweep_112
Sweep_113
Sweep_114
Sweep_115
Sweep_116
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_MW_A1_C15.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.70it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.08it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.82s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.30it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.85s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.30it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  3.55it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.57it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:04<00:00,  1.89it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_0
Sweep_10
Sweep_11
Sweep_113
Sweep_118
Sweep_119
Sweep_12
Sweep_120
Sweep_121
Sweep_122
Sweep_13
Sweep_14
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_MW_A1_C16.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.44s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.72it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  3.27it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  2.95it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.24it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  3.73it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:04<00:00,  1.48it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_SM_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.23s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_SM_A1_C04.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 100/100 [00:04<00:00, 21.26it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 112/112 [00:04<00:00, 23.53it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13
Sweep_14
Sweep_51
Sweep_52
Sweep_53
Sweep_54
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_SM_A1_C05.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]

Sweep_102
Sweep_103
Sweep_104
Sweep_12
Sweep_13
Sweep_14
Sweep_97
Sweep_99
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_SM_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_14
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_SM_A1_C09.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_SM_A1_C14.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11
Sweep_12
Sweep_13
Sweep_14
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_SM_A1_C15.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12
Sweep_13
Sweep_14
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_SM_A1_C16.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
Spike: 100%|████████████████████████████████████████████████████████████████████████████| 2/2 [16:00<00:00, 480.17s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.44s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.45s/it]

Sweep_10
Sweep_11
Sweep_115
Sweep_116
Sweep_117
Sweep_118
Sweep_119
Sweep_12
Sweep_120
Sweep_121
Sweep_122
Sweep_123
Sweep_124
Sweep_125
Sweep_126
Sweep_13
Sweep_14
Sweep_8
Sweep_9

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

In [14]:
M03_df.head()

,ramp_amp,inflection_time,inflection_amp,peak_amp,peak_width,peak_sharpness,exp_lambda,exp_const,isi,r_squared_ramp,r_squared_exp,Sweep_#,file_name,dendriticType,SomaLayerLoc,brainOrigin,Weight,Sex,Age,Species
0,2.612488,0.45,-45.858766,15.164185,0.50,6.445313,6.970228,-56.733916,19.45,0.996142,0.739826,Sweep_10,M03_JS_A1_C01,A,3,PFC,6.3,F,9.96,Macaca fascicularis
1,2.116406,0.55,-42.507936,13.681031,0.50,5.018616,7.193608,-54.574427,20.15,0.998421,0.688264,Sweep_10,M03_JS_A1_C01,A,3,PFC,6.3,F,9.96,Macaca fascicularis
2,2.044173,0.60,-41.433717,12.530518,0.55,3.962708,6.693805,-54.071263,24.25,0.984082,0.725384,Sweep_10,M03_JS_A1_C01,A,3,PFC,6.3,F,9.96,Macaca fascicularis
3,1.850421,0.60,-38.183595,11.666870,0.55,3.634644,6.344601,-53.386135,24.55,0.994742,0.774003,Sweep_10,M03_JS_A1_C01,A,3,PFC,6.3,F,9.96,Macaca fascicularis
4,1.832248,0.60,-38.827516,11.984253,0.55,3.929138,5.981717,-53.646425,26.60,0.950116,0.831859,Sweep_10,M03_JS_A1_C01,A,3,PFC,6.3,F,9.96,Macaca fascicularis

In [15]:
M03_df.tail()

,ramp_amp,inflection_time,inflection_amp,peak_amp,peak_width,peak_sharpness,exp_lambda,exp_const,isi,r_squared_ramp,r_squared_exp,Sweep_#,file_name,dendriticType,SomaLayerLoc,brainOrigin,Weight,Sex,Age,Species
0,3.532513,0.50,-41.070558,34.521485,0.60,9.402466,5.926023,-41.947774,NaN,0.990231,0.869755,Sweep_13,M03_SM_A1_C16,NA,NA,PFC,6.3,F,9.96,Macaca fascicularis
0,3.611996,0.50,-41.882325,35.430909,0.55,8.175659,7.009688,-41.227819,6.55,0.979050,0.715464,Sweep_14,M03_SM_A1_C16,NA,NA,PFC,6.3,F,9.96,Macaca fascicularis
1,2.420113,1.15,-35.577393,14.031983,0.90,1.815796,3.344942,-40.903731,NaN,0.992774,0.984037,Sweep_14,M03_SM_A1_C16,NA,NA,PFC,6.3,F,9.96,Macaca fascicularis
0,3.556652,0.60,-29.888917,27.313233,0.70,3.521729,3.635624,-45.651009,NaN,0.986556,0.996845,Sweep_8,M03_SM_A1_C16,NA,NA,PFC,6.3,F,9.96,Macaca fascicularis
0,2.805506,0.55,-37.921143,33.331300,0.60,6.616211,4.633209,-44.813706,NaN,0.988634,0.978401,Sweep_9,M03_SM_A1_C16,NA,NA,PFC,6.3,F,9.96,Macaca fascicularis

**M04**

In [60]:
file_paths2 = get_file_paths(r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04")
M04_df = monkey_df(file_paths2, 28)

save_dataframe_to_pickle(M04_df, r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04_df.pkl")

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C01.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 82/82 [00:03<00:00, 25.12it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 80/80 [00:03<00:00, 23.38it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 104/104 [00:03<00:00, 30.74it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.66it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.62it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:03<00:00,  6.94it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.70it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 30/30 [00:03<00:00,  8.32it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.99it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C03.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.06it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.08it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 137/137 [00:03<00:00, 38.77it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 146/146 [00:03<00:00, 40.56it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.44s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_46
Sweep_48
Sweep_50
Sweep_51
Sweep_53
Sweep_54
Sweep_55
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C04.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.75it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  3.91it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.78it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.54it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.46it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.82it/s]

Sweep_0
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C05.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  3.97it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.04it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 26/26 [00:03<00:00,  7.35it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 29/29 [00:03<00:00,  7.86it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.11it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_40
Sweep_41
Sweep_42
Sweep_43
Sweep_44
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C06.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.04it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  4.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.52it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.73it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:04<00:00,  2.70it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.11it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.67it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.77it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.90it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_4
Sweep_5
Sweep_6
Sweep_7
Sweep_71
Sweep_73
Sweep_74
Sweep_75
Sweep_76
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C07.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.94it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:04<00:00,  4.62it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.22it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.23it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.98it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.64it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  3.29it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.44it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.00it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  3.70it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 31/31 [00:05<00:00,  5.99it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 42/42 [00:04<00:00,  8.57it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_3
Sweep_4
Sweep_5
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C08.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 44/44 [00:03<00:00, 11.97it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 52/52 [00:05<00:00,  9.43it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 57/57 [00:04<00:00, 12.34it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 65/65 [00:04<00:00, 13.75it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 70/70 [00:04<00:00, 14.18it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.62it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 30/30 [00:03<00:00,  9.11it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 36/36 [00:05<00:00,  6.51it/s]

Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_21
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_3
Sweep_6
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C09.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]

Fitting failed for sweep Sweep_1: All fits failed.

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.12it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]

Fitting failed for sweep Sweep_6: All fits failed.

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.48s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_75
Sweep_77
Sweep_78
Sweep_79
Sweep_80
Sweep_81
Sweep_82
Sweep_83
Sweep_84
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C10.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.12it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.48s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13
Sweep_14
Sweep_172
Sweep_173
Sweep_174
Sweep_175
Sweep_176
Sweep_177
Sweep_178
Sweep_179
Sweep_180
Sweep_181
Sweep_182
Sweep_183
Sweep_184
Sweep_185
Sweep_186
Sweep_187
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C12.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:03<00:00,  5.52it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  6.09it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:03<00:00,  7.10it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:03<00:00,  7.52it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 26/26 [00:03<00:00,  7.61it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.10it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  3.95it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.31it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_6
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C13.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.17it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  3.72it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.15it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:03<00:00,  4.56it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  3.55it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.80s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.08it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.69it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.00it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_4
Sweep_5
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C14.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:05<00:00,  3.54it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 22/22 [00:06<00:00,  3.62it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:05<00:00,  4.33it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 26/26 [00:05<00:00,  4.73it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 28/28 [00:05<00:00,  5.10it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.12it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.83it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:05<00:00,  2.60it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_6
Sweep_7
Sweep_77
Sweep_8
Sweep_81
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C15.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.05s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:06<00:00,  3.80it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 31/31 [00:06<00:00,  4.64it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 33/33 [00:07<00:00,  4.61it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 36/36 [00:07<00:00,  4.95it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 40/40 [00:07<00:00,  5.63it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:06<00:00,  2.42it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.04it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_6
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C16.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.06it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.44s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_3
Sweep_4
Sweep_41
Sweep_42
Sweep_44
Sweep_46
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_MJ_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_MW_A1_C01.nwb

Spike: 100%|███████████████████████████████████████████████████████████████████████████| 35/35 [00:03<00:00, 10.34it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 41/41 [00:03<00:00, 12.10it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 44/44 [00:03<00:00, 12.73it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 48/48 [00:03<00:00, 13.59it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 51/51 [00:03<00:00, 13.06it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  3.75it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:04<00:00,  5.55it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 29/29 [00:04<00:00,  6.33it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_MW_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.47it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.75it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.05it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.83it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.63it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  3.78it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:04<00:00,  3.88it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.57it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.92it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_19
Sweep_20
Sweep_21
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_30
Sweep_31
Sweep_32
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_MW_A1_C03.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.14it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 64/64 [00:05<00:00, 11.80it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]

Sweep_100
Sweep_101
Sweep_102
Sweep_13
Sweep_14
Sweep_87
Sweep_89
Sweep_90
Sweep_91
Sweep_92
Sweep_93
Sweep_94
Sweep_95
Sweep_96
Sweep_97
Sweep_98
Sweep_99
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_MW_A1_C06.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.78s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_41
Sweep_44
Sweep_45
Sweep_46
Sweep_47
Sweep_48
Sweep_49
Sweep_50
Sweep_51
Sweep_65
Sweep_66
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_MW_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_14
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_MW_A1_C08.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.83it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.61it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:05<00:00,  3.48it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.09it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:04<00:00,  4.86it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.44s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.12it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_57
Sweep_62
Sweep_63
Sweep_64
Sweep_65
Sweep_66
Sweep_67
Sweep_68
Sweep_69
Sweep_70
Sweep_71
Sweep_72
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_MW_A1_C09.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.83it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  3.99it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  4.07it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.74it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.98it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.08it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.76it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_123
Sweep_125
Sweep_126
Sweep_129
Sweep_13
Sweep_131
Sweep_134
Sweep_138
Sweep_139
Sweep_14
Sweep_140
Sweep_141
Sweep_142
Sweep_143
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_MW_A1_C10.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_149
Sweep_150
Sweep_151
Sweep_152
Sweep_153
Sweep_154
Sweep_155
Sweep_156
Sweep_157
Sweep_158
Sweep_159
Sweep_160
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_30
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_SM_A1_C01.nwb

Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.66it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 30/30 [00:03<00:00,  9.10it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:03<00:00,  5.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.84it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:03<00:00,  4.81it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:03<00:00,  5.80it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  3.91it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 33/33 [00:03<00:00,  8.56it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 37/37 [00:03<00:00,  9.50it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 40/40 [00:04<00:00, 10.00it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 33/33 [00:03<00:00,  8.39it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 33/33 [00:03<00:00,  8.28it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:03<00:00,  4.57it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 26/26 [00:04<00:00,  6.43it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.96it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_3
Sweep_4
Sweep_5
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_SM_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.98s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.05it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_22
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_30
Sweep_32
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_SM_A1_C03.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 268/268 [00:04<00:00, 60.29it/s]
Spike: 100%|██████████████████████████████████████████████████████████████████████| 3553/3553 [00:27<00:00, 127.82it/s]

Fitting failed for sweep Sweep_13: could not broadcast input array from shape (18,) into shape (20,)

Spike: 100%|██████████████████████████████████████████████████████████████████████| 5972/5972 [00:50<00:00, 118.04it/s]

Fitting failed for sweep Sweep_14: could not broadcast input array from shape (9,) into shape (20,)
Sweep_12
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_SM_A1_C04.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:02<00:00,  4.48it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:03<00:00,  5.73it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 62/62 [00:03<00:00, 17.84it/s]

Fitting failed for sweep Sweep_10: could not broadcast input array from shape (19,) into shape (20,)

Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:04<00:00,  5.31it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.64it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  4.31it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  4.08it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 22/22 [00:04<00:00,  5.33it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.73it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:04<00:00,  4.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 41/41 [00:04<00:00,  9.22it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 48/48 [00:04<00:00, 10.86it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 56/56 [00:04<00:00, 12.53it/s]

Sweep_0
Sweep_1
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_3
Sweep_4
Sweep_5
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_SM_A1_C06.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.65it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  3.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.11it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.28it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.06it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.02it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.96it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.65it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.54it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.90it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.77it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_3
Sweep_4
Sweep_5
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_SM_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_85
Sweep_86
Sweep_88
Sweep_89
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_SM_A1_C08.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 59/59 [00:03<00:00, 17.70it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 83/83 [00:06<00:00, 12.11it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 101/101 [00:06<00:00, 15.00it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 108/108 [00:06<00:00, 16.62it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 68/68 [00:06<00:00, 10.65it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]

Fitting failed for sweep Sweep_25: Length of values (2) does not match length of index (1)

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]

Fitting failed for sweep Sweep_32: Length of values (2) does not match length of index (1)

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.11it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.74it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.81it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:03<00:00,  7.29it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 35/35 [00:03<00:00, 10.47it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 46/46 [00:03<00:00, 13.31it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_18
Sweep_19
Sweep_2
Sweep_20
Sweep_21
Sweep_22
Sweep_23
Sweep_24
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_3
Sweep_30
Sweep_31
Sweep_33
Sweep_34
Sweep_4
Sweep_5
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_SM_A1_C09.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.48s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]

Sweep_0
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_44
Sweep_45
Sweep_46
Sweep_47
Sweep_48
Sweep_49
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_SM_A1_C10.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_3
Sweep_30
Sweep_31
Sweep_32
Sweep_33
Sweep_34
Sweep_35
Sweep_36
Sweep_37
Sweep_38
Sweep_39
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_SM_A1_C11.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.34it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 54/54 [00:03<00:00, 16.48it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 62/62 [00:03<00:00, 18.54it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 70/70 [00:03<00:00, 20.66it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 79/79 [00:03<00:00, 22.67it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 88/88 [00:03<00:00, 23.80it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:03<00:00,  5.00it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.81it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.72it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.11it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:03<00:00,  5.20it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 22/22 [00:03<00:00,  6.66it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 35/35 [00:03<00:00,  9.87it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 43/43 [00:03<00:00, 11.88it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_18
Sweep_19
Sweep_2
Sweep_20
Sweep_21
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_3
Sweep_30
Sweep_31
Sweep_32
Sweep_33
Sweep_34
Sweep_4
Sweep_5
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_SM_A1_C13.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]

Sweep_13
Sweep_14
Sweep_200
Sweep_205
Sweep_206
file added

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

In [61]:
M04_df.head()

,ramp_amp,inflection_time,inflection_amp,peak_amp,peak_width,peak_sharpness,exp_lambda,exp_const,isi,r_squared_ramp,r_squared_exp,Sweep_#,file_name,dendriticType,SomaLayerLoc,brainOrigin,Weight,Sex,Age,Species
0,4.387923,0.45,-40.768434,24.624634,0.40,9.146118,7.228195,-61.191912,3141.0,0.988773,0.670360,Sweep_10,M04_JS_A1_C01,NA,NA,PFC,6.5,F,11.58,Macaca fascicularis
1,4.833480,0.40,-41.177369,25.955201,0.40,10.462952,8.280124,-59.228859,NaN,0.990291,0.534707,Sweep_10,M04_JS_A1_C01,NA,NA,PFC,6.5,F,11.58,Macaca fascicularis
0,3.545225,0.40,-40.933228,24.578858,0.40,10.218811,7.681916,-60.576132,13.8,0.985757,0.618962,Sweep_11,M04_JS_A1_C01,NA,NA,PFC,6.5,F,11.58,Macaca fascicularis
1,3.574366,0.45,-38.961793,22.283936,0.45,8.531189,6.139406,-60.119660,15.2,0.983322,0.773941,Sweep_11,M04_JS_A1_C01,NA,NA,PFC,6.5,F,11.58,Macaca fascicularis
2,4.571855,0.45,-35.510255,20.413208,0.40,6.814575,5.891516,-59.775511,13.5,0.987037,0.753234,Sweep_11,M04_JS_A1_C01,NA,NA,PFC,6.5,F,11.58,Macaca fascicularis

In [62]:
M04_df = load_dataframe_from_pickle(r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04_df.pkl")

M04_df.tail()

,ramp_amp,inflection_time,inflection_amp,peak_amp,peak_width,peak_sharpness,exp_lambda,exp_const,isi,r_squared_ramp,r_squared_exp,Sweep_#,file_name,dendriticType,SomaLayerLoc,brainOrigin,Weight,Sex,Age,Species
0,0.672305,0.80,-41.328373,41.478031,0.95,2.859497,2.601819,-48.453468,NaN,0.865878,0.998288,Sweep_13,M04_SM_A1_C13,NA,NA,PFC,6.5,F,11.58,Macaca fascicularis
0,0.870738,0.80,-42.854252,41.923588,0.90,3.094482,2.641498,-48.066803,NaN,0.978995,0.998324,Sweep_14,M04_SM_A1_C13,NA,NA,PFC,6.5,F,11.58,Macaca fascicularis
0,6.746175,0.75,-47.212162,41.520756,0.85,3.582764,2.447608,-56.480353,NaN,0.998580,0.991162,Sweep_200,M04_SM_A1_C13,NA,NA,PFC,6.5,F,11.58,Macaca fascicularis
0,7.036114,0.75,-46.192875,42.369144,0.85,3.350830,2.516052,-55.528810,NaN,0.998975,0.991049,Sweep_205,M04_SM_A1_C13,NA,NA,PFC,6.5,F,11.58,Macaca fascicularis
0,7.153687,0.75,-46.510258,42.546146,0.85,3.405762,2.494742,-55.589845,NaN,0.999300,0.990622,Sweep_206,M04_SM_A1_C13,NA,NA,PFC,6.5,F,11.58,Macaca fascicularis

In [63]:
file_paths3 = get_file_paths(r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05")
M05_df = monkey_df(file_paths3, 49)

save_dataframe_to_pickle(M05_df, r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05_df.pkl")

C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_JS_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.68it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.67it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.52it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.36it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.15it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.20it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.81s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.28s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_18
Sweep_19
Sweep_2
Sweep_20
Sweep_21
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_3
Sweep_4
Sweep_5
Sweep_53
Sweep_55
Sweep_56
Sweep_57
Sweep_58
Sweep_59
Sweep_6
Sweep_60
Sweep_61
Sweep_62
Sweep_63
Sweep_64
Sweep_65
Sweep_66
Sweep_67
Sweep_68
Sweep_69
Sweep_7
Sweep_70
Sweep_71
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_JS_A1_C02.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.91it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.25it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.41it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:03<00:00,  7.20it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.44it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.09it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:03<00:00,  5.35it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 47/47 [00:03<00:00, 12.94it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.22it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.29it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.02it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.06it/s]

Sweep_0
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_18
Sweep_19
Sweep_20
Sweep_21
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_3
Sweep_4
Sweep_5
Sweep_6
Sweep_66
Sweep_67
Sweep_68
Sweep_69
Sweep_7
Sweep_70
Sweep_71
Sweep_72
Sweep_73
Sweep_74
Sweep_75
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_JS_A1_C03.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:03<00:00,  6.80it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  7.43it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 33/33 [00:04<00:00,  7.79it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 36/36 [00:04<00:00,  8.35it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 40/40 [00:04<00:00,  9.73it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.59it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.48it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:03<00:00,  4.75it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:04<00:00,  5.76it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 30/30 [00:04<00:00,  7.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 32/32 [00:04<00:00,  7.25it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 38/38 [00:05<00:00,  7.56it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 39/39 [00:04<00:00,  8.22it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.05it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.47it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:05<00:00,  3.56it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_JS_A1_C04.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_0
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_56
Sweep_57
Sweep_58
Sweep_59
Sweep_60
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_JS_A1_C05.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.77it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.67it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.66it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.11it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.11it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.93it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 30/30 [00:07<00:00,  3.91it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 48/48 [00:07<00:00,  6.55it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 75/75 [00:07<00:00,  9.38it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 94/94 [00:07<00:00, 12.06it/s]

Fitting failed for sweep Sweep_22: could not broadcast input array from shape (13,) into shape (20,)

Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:06<00:00,  1.65it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.30it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.82it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.65it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.66it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.64it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:04<00:00,  2.09it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:04<00:00,  2.14it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.84it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 27/27 [00:06<00:00,  3.98it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 51/51 [00:06<00:00,  7.74it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 63/63 [00:06<00:00,  9.62it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 47/47 [00:06<00:00,  7.22it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_17
Sweep_18
Sweep_19
Sweep_20
Sweep_21
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_4
Sweep_5
Sweep_6
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_JS_A1_C06.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.30it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.22it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.06it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.07it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 28/28 [00:04<00:00,  6.40it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 52/52 [00:04<00:00, 10.62it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 64/64 [00:05<00:00, 12.25it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 83/83 [00:05<00:00, 15.10it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 78/78 [00:05<00:00, 13.27it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 27/27 [00:06<00:00,  4.42it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.80s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.80s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_75
Sweep_76
Sweep_77
Sweep_78
Sweep_79
Sweep_8
Sweep_80
Sweep_81
Sweep_82
Sweep_83
Sweep_84
Sweep_85
Sweep_86
Sweep_87
Sweep_88
Sweep_89
Sweep_9
Sweep_90
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_JS_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.06it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_126
Sweep_128
Sweep_13
Sweep_130
Sweep_131
Sweep_132
Sweep_133
Sweep_134
Sweep_135
Sweep_136
Sweep_137
Sweep_14
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_JS_A1_C08.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.57it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.61it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.61it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  4.28it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.51it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.47it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.01it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.55it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_16
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_JS_A1_C09.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.21it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.72it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.09it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.63it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.69it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_60
Sweep_61
Sweep_62
Sweep_63
Sweep_64
Sweep_65
Sweep_66
Sweep_67
Sweep_68
Sweep_69
Sweep_7
Sweep_70
Sweep_71
Sweep_72
Sweep_73
Sweep_74
Sweep_75
Sweep_76
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_JS_A1_C10.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.11it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.05it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_21
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_6
Sweep_7
Sweep_78
Sweep_8
Sweep_80
Sweep_81
Sweep_82
Sweep_83
Sweep_84
Sweep_85
Sweep_86
Sweep_87
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_JS_A1_C11.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:03<00:00,  6.95it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:03<00:00,  7.28it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  6.08it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.66it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  4.31it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.67it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.56it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  7.70it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 43/43 [00:03<00:00, 11.17it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 45/45 [00:03<00:00, 11.59it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 48/48 [00:04<00:00, 11.93it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 47/47 [00:03<00:00, 11.96it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 36/36 [00:03<00:00,  9.09it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 37/37 [00:04<00:00,  9.24it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:04<00:00,  5.75it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 47/47 [00:04<00:00, 11.53it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 22/22 [00:04<00:00,  5.44it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 29/29 [00:03<00:00,  7.72it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 35/35 [00:03<00:00, 10.06it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_21
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_5
Sweep_6
Sweep_7
Sweep_79
Sweep_8
Sweep_81
Sweep_82
Sweep_83
Sweep_84
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_JS_A1_C13.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  4.24it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:03<00:00,  5.80it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:04<00:00,  5.28it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 29/29 [00:04<00:00,  5.86it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 32/32 [00:05<00:00,  6.35it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.07it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.53it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:05<00:00,  3.12it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 26/26 [00:05<00:00,  4.77it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 29/29 [00:05<00:00,  4.99it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 32/32 [00:05<00:00,  5.44it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:05<00:00,  2.68it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.99it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:04<00:00,  2.23it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_17
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_5
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_JS_A1_C15.nwb

Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:04<00:00,  2.30it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:04<00:00,  2.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:04<00:00,  2.41it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.93it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.54it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.56it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:04<00:00,  2.24it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.92it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.11it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.84it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.69it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.59it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_3
Sweep_30
Sweep_31
Sweep_32
Sweep_4
Sweep_5
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_JS_A1_C16.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.31it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.46it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 70/70 [00:04<00:00, 14.10it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:05<00:00,  4.58it/s]

Fitting failed for sweep Sweep_11: could not broadcast input array from shape (11,) into shape (20,)

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.99it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.75it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.48s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.84it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 31/31 [00:06<00:00,  4.90it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 43/43 [00:06<00:00,  6.22it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 52/52 [00:06<00:00,  8.06it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_34
Sweep_35
Sweep_36
Sweep_37
Sweep_39
Sweep_40
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_MJ_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.33it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.31it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:04<00:00,  1.80it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_MJ_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.54it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:04<00:00,  1.70it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:05<00:00,  1.94it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:07<00:00,  2.30it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.50it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:04<00:00,  2.04it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:04<00:00,  2.31it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:04<00:00,  2.34it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.58it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.50it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.87it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.84it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.66it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_41
Sweep_42
Sweep_43
Sweep_44
Sweep_56
Sweep_57
Sweep_58
Sweep_59
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_MJ_A1_C04.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.11it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.54it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:04<00:00,  2.73it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.09it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.41it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.41it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.81s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.11it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_41
Sweep_42
Sweep_43
Sweep_44
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_MW_A1_C04.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 80/80 [00:03<00:00, 20.19it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 100/100 [00:05<00:00, 16.71it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 120/120 [00:06<00:00, 19.28it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 138/138 [00:06<00:00, 21.22it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 141/141 [00:06<00:00, 21.28it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:06<00:00,  2.89it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 74/74 [00:06<00:00, 11.85it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 97/97 [00:06<00:00, 14.19it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 124/124 [00:06<00:00, 19.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 122/122 [00:06<00:00, 19.08it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:02<00:00,  4.49it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_50
Sweep_51
Sweep_54
Sweep_55
Sweep_56
Sweep_57
Sweep_58
Sweep_59
Sweep_60
Sweep_61
Sweep_62
Sweep_63
Sweep_64
Sweep_65
Sweep_66
Sweep_67
Sweep_68
Sweep_69
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_MW_A1_C05.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.69it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:03<00:00,  5.92it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.87it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:03<00:00,  5.68it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:03<00:00,  5.87it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:03<00:00,  6.57it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 30/30 [00:03<00:00,  7.83it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 26/26 [00:03<00:00,  7.31it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:03<00:00,  5.54it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 50/50 [00:03<00:00, 12.83it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.01it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.08it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 57/57 [00:03<00:00, 15.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.33it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.05it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.79it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.23it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.00it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.80it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.63it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.44it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_18
Sweep_2
Sweep_20
Sweep_21
Sweep_22
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_3
Sweep_4
Sweep_5
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_SM_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 26/26 [00:04<00:00,  5.98it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 34/34 [00:04<00:00,  7.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 26/26 [00:04<00:00,  5.78it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:04<00:00,  4.08it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.95it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.44it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.21it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:04<00:00,  3.89it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_SM_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:05<00:00,  3.11it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.89it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:05<00:00,  4.58it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:05<00:00,  4.63it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 28/28 [00:05<00:00,  5.06it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.63it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.12it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:05<00:00,  2.68it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 22/22 [00:08<00:00,  2.74it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:08<00:00,  3.03it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.11it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_SM_A1_C03.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 123/123 [00:06<00:00, 19.87it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 140/140 [00:06<00:00, 20.31it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 126/126 [00:06<00:00, 20.78it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 142/142 [00:06<00:00, 20.31it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 109/109 [00:03<00:00, 32.05it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 131/131 [00:05<00:00, 23.52it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 149/149 [00:05<00:00, 28.60it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 164/164 [00:05<00:00, 32.36it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_0
Sweep_12
Sweep_13
Sweep_14
Sweep_27
Sweep_28
Sweep_29
Sweep_52
Sweep_53
Sweep_54
Sweep_55
Sweep_56
Sweep_57
Sweep_58
Sweep_59
Sweep_60
Sweep_69
Sweep_70
Sweep_71
Sweep_72
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_SM_A1_C06.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 62/62 [00:04<00:00, 13.31it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 61/61 [00:04<00:00, 12.57it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 37/37 [00:05<00:00,  7.38it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.08it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.28it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.45it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 41/41 [00:05<00:00,  7.14it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 57/57 [00:06<00:00,  9.30it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 56/56 [00:06<00:00,  9.08it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.07it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:04<00:00,  2.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.46it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.73it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.04it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 37/37 [00:06<00:00,  5.77it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 49/49 [00:06<00:00,  7.45it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_19
Sweep_21
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_SM_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.20it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.68it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.78s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_SM_A1_C13.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]

Sweep_27
Sweep_28
Sweep_29

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

In [64]:
M05_df = load_dataframe_from_pickle(r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05_df.pkl")

M05_df.tail()

,ramp_amp,inflection_time,inflection_amp,peak_amp,peak_width,peak_sharpness,exp_lambda,exp_const,isi,r_squared_ramp,r_squared_exp,Sweep_#,file_name,dendriticType,SomaLayerLoc,brainOrigin,Weight,Sex,Age,Species
4,1.787917,1.20,-35.691650,26.594727,1.45,0.610352,1.165553,-47.850570,43.70,0.908361,0.997375,Sweep_9,M05_JS_A1_C13,NA,NA,PFC,7.4,M,4.39,Macaca fascicularis
5,1.474022,1.15,-35.691650,27.632324,1.40,0.946045,1.132225,-48.452109,51.80,0.890761,0.998009,Sweep_9,M05_JS_A1_C13,NA,NA,PFC,7.4,M,4.39,Macaca fascicularis
6,0.966466,1.20,-35.416992,25.740234,1.50,0.549316,1.122565,-47.547140,0.00,0.796952,0.997495,Sweep_9,M05_JS_A1_C13,NA,NA,PFC,7.4,M,4.39,Macaca fascicularis
7,0.966466,1.20,-35.416992,25.740234,1.50,0.549316,1.122565,-47.547140,52.15,0.796952,0.997495,Sweep_9,M05_JS_A1_C13,NA,NA,PFC,7.4,M,4.39,Macaca fascicularis
8,1.377192,1.30,-34.135254,24.824707,1.50,0.915527,1.099463,-47.206315,NaN,0.774453,0.998393,Sweep_9,M05_JS_A1_C13,NA,NA,PFC,7.4,M,4.39,Macaca fascicularis

In [22]:
file_paths4 = get_file_paths(r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M06")
M06_df = monkey_df(file_paths4, 66)

save_dataframe_to_pickle(M06_df, r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M06_df.pkl")

C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M06\M06_MW_A1_C04.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.85s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.34it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  4.11it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  4.14it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  4.26it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 27/27 [00:03<00:00,  7.84it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.79s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.72it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.57it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.73it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  3.89it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  4.02it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.88s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.76it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.46it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_2
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_3
Sweep_4
Sweep_48
Sweep_49
Sweep_50
Sweep_58
Sweep_60
Sweep_66
Sweep_67
Sweep_68
Sweep_69
Sweep_7
Sweep_70
Sweep_71
Sweep_72
Sweep_73
Sweep_74
Sweep_75
Sweep_76
Sweep_77
Sweep_78
Sweep_79
Sweep_8
Sweep_80
Sweep_81
Sweep_82
Sweep_83
Sweep_84
Sweep_85
Sweep_86
Sweep_87
Sweep_88
Sweep_89
Sweep_9
Sweep_90
Sweep_91
Sweep_92
Sweep_93
Sweep_94
Sweep_95
Sweep_96
Sweep_97
Sweep_98
Sweep_99
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M06\M06_SM_A1_C01.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.68it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.75it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.69it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.72it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.42it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M06\M06_SM_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.69it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.77it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.71it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.69it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.68it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]

Fitting failed for sweep Sweep_16: All fits failed.

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.71it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.71it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.74it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.02it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.71it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_21
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M06\M06_SM_A1_C08.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_39
Sweep_40
Sweep_41
Sweep_42
Sweep_43
Sweep_44
Sweep_45
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M06\M06_SM_A1_C12.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  4.26it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  4.04it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.95it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.94it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.83it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.70it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.32it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.55it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.31it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.02it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_3
Sweep_4
Sweep_7
Sweep_8
Sweep_9

In [23]:
M06_df.head()

,ramp_amp,inflection_time,inflection_amp,peak_amp,peak_width,peak_sharpness,exp_lambda,exp_const,isi,r_squared_ramp,r_squared_exp,Sweep_#,file_name,dendriticType,SomaLayerLoc,brainOrigin,Weight,Sex,Age,Species
0,3.015504,0.55,-44.738771,25.451661,0.65,4.821777,2.929958,-52.918481,NaN,0.986424,0.999387,Sweep_0,M06_MW_A1_C04,A,2,PFC,5,M,4.76,Macaca fascicularis
0,2.926016,0.55,-44.158937,26.306153,0.65,4.699707,3.093520,-53.003746,NaN,0.992559,0.998917,Sweep_1,M06_MW_A1_C04,A,2,PFC,5,M,4.76,Macaca fascicularis
0,3.816762,0.50,-41.717530,30.761719,0.60,6.072998,4.063969,-48.254377,14.90,0.994712,0.966464,Sweep_10,M06_MW_A1_C04,A,2,PFC,5,M,4.76,Macaca fascicularis
1,2.270233,0.55,-34.454346,27.465821,0.70,4.013062,2.560024,-48.684115,241.55,0.973479,0.996839,Sweep_10,M06_MW_A1_C04,A,2,PFC,5,M,4.76,Macaca fascicularis
2,1.096338,0.75,-29.998780,28.442383,0.95,1.831055,1.656402,-48.861020,174.35,0.933462,0.998526,Sweep_10,M06_MW_A1_C04,A,2,PFC,5,M,4.76,Macaca fascicularis

In [43]:
M06_df = load_dataframe_from_pickle(r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M06_df.pkl")
M06_df.tail()

,ramp_amp,inflection_time,inflection_amp,peak_amp,peak_width,peak_sharpness,exp_lambda,exp_const,isi,r_squared_ramp,r_squared_exp,Sweep_#,file_name,dendriticType,SomaLayerLoc,brainOrigin,Weight,Sex,Age,Species
3,3.509292,0.35,-39.459229,18.096924,0.35,13.931275,10.0,-37.692262,4.60,0.968336,3.119926e-31,Sweep_9,M06_SM_A1_C12,NA,NA,PFC,5,M,4.76,Macaca fascicularis
4,3.587307,0.45,-37.902833,17.181397,0.40,10.894776,10.0,-39.810521,4.95,0.970636,2.524654e-03,Sweep_9,M06_SM_A1_C12,NA,NA,PFC,5,M,4.76,Macaca fascicularis
5,3.275706,0.45,-36.834718,15.563965,0.40,10.421753,10.0,-38.339234,4.85,0.943536,2.168229e-31,Sweep_9,M06_SM_A1_C12,NA,NA,PFC,5,M,4.76,Macaca fascicularis
6,3.401448,0.50,-37.261964,14.373780,0.40,9.506226,10.0,-41.364146,6.50,0.974846,2.094324e-02,Sweep_9,M06_SM_A1_C12,NA,NA,PFC,5,M,4.76,Macaca fascicularis
7,1.979283,0.50,-33.447266,12.359619,0.40,7.080078,10.0,-40.974258,NaN,0.922619,1.694799e-02,Sweep_9,M06_SM_A1_C12,NA,NA,PFC,5,M,4.76,Macaca fascicularis

In [10]:
file_paths5 = get_file_paths(r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08")
M08_df = monkey_df(file_paths5, 71)

save_dataframe_to_pickle(M06_df, r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08_df.pkl")

C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_JS_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.13s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:05<00:00,  4.50it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 59/59 [00:05<00:00, 10.70it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 69/69 [00:04<00:00, 14.48it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 76/76 [00:04<00:00, 15.24it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.43s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 45/45 [00:04<00:00,  9.52it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 59/59 [00:04<00:00, 12.42it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 67/67 [00:04<00:00, 13.97it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 75/75 [00:05<00:00, 14.96it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_84
Sweep_85
Sweep_86
Sweep_87
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_JS_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 46/46 [00:04<00:00,  9.78it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 52/52 [00:04<00:00, 11.37it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 162/162 [00:04<00:00, 33.59it/s]

Fitting failed for sweep Sweep_12: Length of values (163) does not match length of index (162)

Spike: 100%|█████████████████████████████████████████████████████████████████████████| 173/173 [00:04<00:00, 36.24it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 102/102 [00:04<00:00, 21.74it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.02it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.51it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:04<00:00,  4.56it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 31/31 [00:04<00:00,  6.67it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 38/38 [00:04<00:00,  8.36it/s]

Sweep_10
Sweep_11
Sweep_13
Sweep_14
Sweep_4
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_JS_A1_C03.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:04<00:00,  4.46it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 56/56 [00:04<00:00, 12.11it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 64/64 [00:04<00:00, 14.07it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 77/77 [00:04<00:00, 16.92it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 86/86 [00:04<00:00, 18.62it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.10it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 39/39 [00:04<00:00,  8.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 55/55 [00:04<00:00, 11.98it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 168/168 [00:04<00:00, 35.26it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 96/96 [00:04<00:00, 20.74it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 101/101 [00:04<00:00, 21.51it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.09it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_JS_A1_C04.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.76s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.36s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.09it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 63/63 [00:04<00:00, 13.60it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 59/59 [00:04<00:00, 12.83it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 63/63 [00:04<00:00, 13.85it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 53/53 [00:04<00:00, 11.48it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_16
Sweep_17
Sweep_18
Sweep_21
Sweep_27
Sweep_28
Sweep_29
Sweep_30
Sweep_31
Sweep_32
Sweep_33
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_JS_A1_C06.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.70it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.41it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.52it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:04<00:00,  4.50it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.46it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.31s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:04<00:00,  3.90it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:04<00:00,  4.89it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.06it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.15it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 39/39 [00:04<00:00,  8.17it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.39s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_110
Sweep_111
Sweep_112
Sweep_113
Sweep_12
Sweep_13
Sweep_14
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_JS_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.03it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.45it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.85it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]

Fitting failed for sweep Sweep_18: All fits failed.

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.72s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.35s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_4
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_JS_A1_C08.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.76s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.37it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.70it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_JS_A1_C09.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 44/44 [00:04<00:00,  9.59it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 49/49 [00:04<00:00, 10.68it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 57/57 [00:04<00:00, 12.28it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 61/61 [00:04<00:00, 13.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 66/66 [00:04<00:00, 13.81it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.48s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.96s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.23s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.34it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.05it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 28/28 [00:05<00:00,  5.25it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 36/36 [00:04<00:00,  7.73it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_4
Sweep_49
Sweep_5
Sweep_51
Sweep_52
Sweep_53
Sweep_54
Sweep_55
Sweep_56
Sweep_57
Sweep_58
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_JS_A1_C10.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.10it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 41/41 [00:04<00:00,  8.94it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.88s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_101
Sweep_102
Sweep_103
Sweep_82
Sweep_83
Sweep_84
Sweep_85
Sweep_86
Sweep_87
Sweep_88
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_JS_A1_C12.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.57it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.37it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.39it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.28s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.34it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.59it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:04<00:00,  5.41it/s]

Fitting failed for sweep Sweep_23: could not broadcast input array from shape (18,) into shape (20,)

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.67it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.68it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.11it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.04it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.06it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.94it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.48it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.50it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.92it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_20
Sweep_21
Sweep_22
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_3
Sweep_38
Sweep_39
Sweep_40
Sweep_41
Sweep_42
Sweep_5
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_JS_A1_C14.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 75/75 [00:04<00:00, 16.43it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 92/92 [00:04<00:00, 19.72it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 87/87 [00:05<00:00, 17.15it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 96/96 [00:04<00:00, 20.36it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 105/105 [00:04<00:00, 22.60it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 110/110 [00:04<00:00, 23.31it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.12it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 43/43 [00:04<00:00,  9.15it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 59/59 [00:04<00:00, 12.35it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 71/71 [00:04<00:00, 15.30it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 83/83 [00:04<00:00, 16.83it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 96/96 [00:05<00:00, 19.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 101/101 [00:04<00:00, 21.09it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 109/109 [00:04<00:00, 22.57it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 31/31 [00:04<00:00,  6.34it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.01s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 61/61 [00:04<00:00, 12.91it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:05<00:00,  4.56it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 46/46 [00:04<00:00,  9.30it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 57/57 [00:05<00:00, 11.20it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 69/69 [00:06<00:00, 10.02it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 78/78 [00:06<00:00, 11.99it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 86/86 [00:06<00:00, 13.00it/s]

Sweep_10
Sweep_100
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_8
Sweep_83
Sweep_84
Sweep_85
Sweep_9
Sweep_94
Sweep_95
Sweep_96
Sweep_97
Sweep_98
Sweep_99
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_JS_A1_C15.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.05it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.07it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.30s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_27
Sweep_28
Sweep_29
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_JS_A1_C16.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.42it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.91it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  3.32it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.34it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:04<00:00,  3.61it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 55/55 [00:04<00:00, 11.09it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.32s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.67it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_27
Sweep_29
Sweep_30
Sweep_31
Sweep_32
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_MW_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.30s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 52/52 [00:04<00:00, 11.52it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_2
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_MW_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.39it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:04<00:00,  4.81it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:04<00:00,  5.41it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 29/29 [00:04<00:00,  5.87it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 31/31 [00:04<00:00,  6.28it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.43s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.41it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.13it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:04<00:00,  3.73it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.15it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:04<00:00,  4.85it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:05<00:00,  4.79it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.31it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.61it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.17it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_MW_A1_C03.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 40/40 [00:04<00:00,  8.73it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.91s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 46/46 [00:04<00:00,  9.73it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 52/52 [00:04<00:00, 11.16it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 53/53 [00:04<00:00, 11.56it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 56/56 [00:04<00:00, 12.20it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.48it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:07<00:00,  2.94it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 29/29 [00:07<00:00,  4.13it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 35/35 [00:06<00:00,  5.07it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 40/40 [00:07<00:00,  5.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 44/44 [00:08<00:00,  5.47it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.23it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.83s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 22/22 [00:05<00:00,  4.38it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.85s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.25s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 33/33 [00:04<00:00,  7.22it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]

Sweep_10
Sweep_100
Sweep_101
Sweep_102
Sweep_103
Sweep_104
Sweep_105
Sweep_106
Sweep_107
Sweep_108
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_7
Sweep_78
Sweep_79
Sweep_8
Sweep_80
Sweep_81
Sweep_82
Sweep_83
Sweep_84
Sweep_85
Sweep_86
Sweep_87
Sweep_88
Sweep_89
Sweep_9
Sweep_90
Sweep_91
Sweep_92
Sweep_93
Sweep_94
Sweep_95
Sweep_96
Sweep_97
Sweep_98
Sweep_99
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_MW_A1_C05.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13
Sweep_14
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_MW_A1_C06.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.29it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.72s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.40it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.86s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.64it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.07it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.04it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.44s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.31it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.91it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.28it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.37it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.31it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.78s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.72s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.88s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.83s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.89s/it]

Sweep_0
Sweep_10
Sweep_100
Sweep_101
Sweep_102
Sweep_103
Sweep_104
Sweep_105
Sweep_106
Sweep_107
Sweep_108
Sweep_109
Sweep_11
Sweep_110
Sweep_111
Sweep_112
Sweep_113
Sweep_114
Sweep_115
Sweep_116
Sweep_12
Sweep_13
Sweep_14
Sweep_30
Sweep_31
Sweep_32
Sweep_33
Sweep_34
Sweep_35
Sweep_36
Sweep_7
Sweep_72
Sweep_73
Sweep_74
Sweep_75
Sweep_76
Sweep_77
Sweep_78
Sweep_79
Sweep_8
Sweep_80
Sweep_81
Sweep_82
Sweep_83
Sweep_84
Sweep_85
Sweep_86
Sweep_87
Sweep_88
Sweep_89
Sweep_9
Sweep_90
Sweep_91
Sweep_92
Sweep_93
Sweep_94
Sweep_95
Sweep_96
Sweep_97
Sweep_98
Sweep_99
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_MW_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:04<00:00,  2.74it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.38it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.80it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.56it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.32it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:04<00:00,  4.08it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:04<00:00,  4.97it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:04<00:00,  5.18it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12
Sweep_13
Sweep_14
Sweep_37
Sweep_38
Sweep_39
Sweep_40
Sweep_41
Sweep_42
Sweep_43
Sweep_44
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_MW_A1_C08.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.85it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.97it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.21it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:04<00:00,  3.88it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:04<00:00,  4.61it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.06it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.69it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  3.26it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.43it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:04<00:00,  4.18it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.34it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.05it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_36
Sweep_37
Sweep_38
Sweep_39
Sweep_40
Sweep_41
Sweep_42
Sweep_43
Sweep_44
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_SM_A1_C03.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 71/71 [00:04<00:00, 15.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 90/90 [00:04<00:00, 19.23it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 107/107 [00:04<00:00, 23.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 117/117 [00:04<00:00, 25.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 126/126 [00:04<00:00, 26.33it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 68/68 [00:04<00:00, 14.85it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 86/86 [00:04<00:00, 18.64it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 101/101 [00:04<00:00, 21.47it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 113/113 [00:04<00:00, 23.99it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 127/127 [00:04<00:00, 26.51it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 86/86 [00:04<00:00, 18.66it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 100/100 [00:04<00:00, 21.19it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 114/114 [00:04<00:00, 24.09it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 56/56 [00:04<00:00, 12.18it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.97it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_53
Sweep_55
Sweep_56
Sweep_57
Sweep_58
Sweep_59
Sweep_71
Sweep_72
Sweep_73
Sweep_74
Sweep_75
Sweep_76
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_SM_A1_C04.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.09it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.30s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.41s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.28it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.22it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.46s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.00it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:04<00:00,  4.25it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.12it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:03<00:00,  1.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.35it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.80s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.97s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.13s/it]

Sweep_0
Sweep_10
Sweep_100
Sweep_101
Sweep_102
Sweep_11
Sweep_113
Sweep_114
Sweep_115
Sweep_116
Sweep_117
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_27
Sweep_28
Sweep_29
Sweep_30
Sweep_31
Sweep_78
Sweep_81
Sweep_82
Sweep_84
Sweep_85
Sweep_86
Sweep_87
Sweep_98
Sweep_99
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_SM_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.88s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:03<00:00,  1.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.45s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_18
Sweep_19
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_SM_A1_C09.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.39it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.04it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.88it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.33it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:04<00:00,  4.88it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.92s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.98s/it]
Spike: 100%|████████████████████████████████████████████████████████████████████████████| 1/1 [04:10<00:00, 250.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.47s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.31s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.40s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_186
Sweep_187
Sweep_188
Sweep_189
Sweep_190
Sweep_191
Sweep_192
Sweep_193
Sweep_194
Sweep_195
Sweep_196
Sweep_28
Sweep_29
Sweep_30
Sweep_31
Sweep_9

NameError: name 'M06_df' is not defined

In [11]:
M08_df.tail()

,ramp_amp,inflection_time,inflection_amp,peak_amp,peak_width,peak_sharpness,exp_lambda,exp_const,isi,r_squared_ramp,r_squared_exp,Sweep_#,file_name,dendriticType,SomaLayerLoc,brainOrigin,Weight,Sex,Age,Species
1,0.794375,0.65,-38.909913,36.468507,0.80,4.425049,2.137163,-51.691492,NaN,0.545088,0.997106,Sweep_30,M08_SM_A1_C09,S,3,PFC,7,F,8.92,Macaca fascicularis
0,1.468515,0.55,-46.234132,40.954591,0.75,6.378174,3.026000,-50.892683,50.2,0.879472,0.991583,Sweep_31,M08_SM_A1_C09,S,3,PFC,7,F,8.92,Macaca fascicularis
1,1.474022,0.65,-38.879395,35.888673,0.80,3.082275,2.198073,-51.345226,NaN,0.874374,0.997618,Sweep_31,M08_SM_A1_C09,S,3,PFC,7,F,8.92,Macaca fascicularis
0,1.390041,0.55,-41.839601,38.360597,0.75,5.432129,2.742456,-52.898929,132.3,0.828544,0.994800,Sweep_9,M08_SM_A1_C09,S,3,PFC,7,F,8.92,Macaca fascicularis
1,1.450618,0.70,-39.520265,33.172608,0.80,3.662109,2.285205,-52.881483,NaN,0.813673,0.997377,Sweep_9,M08_SM_A1_C09,S,3,PFC,7,F,8.92,Macaca fascicularis

In [65]:
file_paths6 = get_file_paths(r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10")
M10_df = monkey_df(file_paths6, 95)

save_dataframe_to_pickle(M10_df, r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10_df.pkl")

C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C03.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 71/71 [00:03<00:00, 19.86it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 83/83 [00:04<00:00, 17.06it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 92/92 [00:04<00:00, 19.38it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 100/100 [00:04<00:00, 22.20it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 109/109 [00:04<00:00, 24.02it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.81s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.66it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 35/35 [00:03<00:00, 10.73it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 48/48 [00:03<00:00, 14.42it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 60/60 [00:03<00:00, 16.55it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_40
Sweep_41
Sweep_42
Sweep_43
Sweep_44
Sweep_45
Sweep_46
Sweep_47
Sweep_48
Sweep_49
Sweep_50
Sweep_51
Sweep_52
Sweep_6
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C04.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 34/34 [00:03<00:00,  9.35it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.44it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.53it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.04it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:02<00:00,  4.52it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 27/27 [00:03<00:00,  8.32it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 42/42 [00:03<00:00, 12.37it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 60/60 [00:04<00:00, 13.62it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_35
Sweep_36
Sweep_37
Sweep_38
Sweep_39
Sweep_40
Sweep_41
Sweep_42
Sweep_43
Sweep_44
Sweep_45
Sweep_46
Sweep_47
Sweep_48
Sweep_49
Sweep_50
Sweep_6
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C05.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.82it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.31it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.35it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.61it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.84s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  4.08it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.96it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  2.68it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.88it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  3.11it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.81s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_113
Sweep_114
Sweep_115
Sweep_116
Sweep_117
Sweep_118
Sweep_119
Sweep_12
Sweep_120
Sweep_121
Sweep_122
Sweep_123
Sweep_124
Sweep_125
Sweep_126
Sweep_127
Sweep_128
Sweep_129
Sweep_13
Sweep_130
Sweep_131
Sweep_14
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_62
Sweep_63
Sweep_64
Sweep_65
Sweep_66
Sweep_67
Sweep_68
Sweep_69
Sweep_70
Sweep_71
Sweep_72
Sweep_73
Sweep_74
Sweep_75
Sweep_76
Sweep_77
Sweep_78
Sweep_79
Sweep_8
Sweep_80
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.84s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.85s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_119
Sweep_12
Sweep_120
Sweep_121
Sweep_122
Sweep_123
Sweep_124
Sweep_13
Sweep_137
Sweep_138
Sweep_139
Sweep_14
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C08.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.71it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.87it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.53it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.07it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.83it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.75s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.64it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.78s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_8
Sweep_89
Sweep_9
Sweep_90
Sweep_91
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C09.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 76/76 [00:03<00:00, 23.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 99/99 [00:03<00:00, 28.98it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 121/121 [00:03<00:00, 32.63it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 141/141 [00:03<00:00, 36.42it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 158/158 [00:04<00:00, 38.76it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:03<00:00,  7.64it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 50/50 [00:03<00:00, 14.66it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_48
Sweep_50
Sweep_51
Sweep_52
Sweep_53
Sweep_54
Sweep_55
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C11.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.74it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.18it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.88s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]

Sweep_100
Sweep_101
Sweep_102
Sweep_103
Sweep_104
Sweep_105
Sweep_106
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_97
Sweep_98
Sweep_99
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C13.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 33/33 [00:03<00:00,  9.95it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 76/76 [00:03<00:00, 22.19it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 97/97 [00:03<00:00, 27.26it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12
Sweep_13
Sweep_14
Sweep_69
Sweep_70
Sweep_71
Sweep_72
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C14.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.72it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.51it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.33it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12
Sweep_13
Sweep_14
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C15.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.75s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:03<00:00,  5.42it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 35/35 [00:03<00:00,  9.64it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 50/50 [00:03<00:00, 13.07it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 68/68 [00:04<00:00, 16.94it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 77/77 [00:04<00:00, 18.04it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]

Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C16.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12
Sweep_13
Sweep_14
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C17.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.72it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.12it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  3.87it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  3.94it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.04it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C18.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 31/31 [00:03<00:00,  8.31it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.03it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:04<00:00,  5.22it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  3.76it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.88s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.85s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_51
Sweep_52
Sweep_53
Sweep_54
Sweep_55
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C19.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 63/63 [00:03<00:00, 17.85it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 76/76 [00:03<00:00, 19.80it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 73/73 [00:04<00:00, 18.20it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 32/32 [00:04<00:00,  7.80it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  4.11it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.85s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 34/34 [00:03<00:00,  9.59it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 53/53 [00:03<00:00, 14.35it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_49
Sweep_50
Sweep_51
Sweep_52
Sweep_53
Sweep_54
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C20.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 43/43 [00:03<00:00, 10.93it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 51/51 [00:04<00:00, 12.57it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 58/58 [00:04<00:00, 13.98it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 63/63 [00:04<00:00, 14.95it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 69/69 [00:04<00:00, 15.77it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:02<00:00,  4.38it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:03<00:00,  6.88it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 35/35 [00:03<00:00,  9.16it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_56
Sweep_57
Sweep_58
Sweep_59
Sweep_60
Sweep_61
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C21.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]

Sweep_100
Sweep_101
Sweep_102
Sweep_103
Sweep_104
Sweep_105
Sweep_106
Sweep_107
Sweep_108
Sweep_109
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_96
Sweep_97
Sweep_98
Sweep_99
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C22.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 57/57 [00:03<00:00, 17.12it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 81/81 [00:03<00:00, 23.28it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 99/99 [00:03<00:00, 26.94it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 118/118 [00:03<00:00, 30.16it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 129/129 [00:04<00:00, 31.35it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.86it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 38/38 [00:03<00:00, 10.93it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_51
Sweep_52
Sweep_53
Sweep_54
Sweep_55
Sweep_56
Sweep_57
Sweep_58
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C23.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.68it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:05<00:00,  2.67it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 22/22 [00:06<00:00,  3.36it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:06<00:00,  3.69it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.88s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.18it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_69
Sweep_7
Sweep_70
Sweep_71
Sweep_72
Sweep_73
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C24.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.35it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.88it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.94it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.03it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  2.81it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.80s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_137
Sweep_138
Sweep_139
Sweep_14
Sweep_140
Sweep_141
Sweep_142
Sweep_143
Sweep_144
Sweep_145
Sweep_146
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C25.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.20it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.76it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C26.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 53/53 [00:03<00:00, 16.41it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 65/65 [00:04<00:00, 13.67it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 75/75 [00:04<00:00, 16.16it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 84/84 [00:04<00:00, 18.33it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 94/94 [00:04<00:00, 20.17it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.88s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 29/29 [00:03<00:00,  9.05it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 41/41 [00:04<00:00,  8.45it/s]

Sweep_0
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_57
Sweep_58
Sweep_59
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C27.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.74it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.16it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:03<00:00,  5.21it/s]

Fitting failed for sweep Sweep_7: could not broadcast input array from shape (9,) into shape (20,)

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.66it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.38it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_25
Sweep_26
Sweep_27
Sweep_6
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C28.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 42/42 [00:06<00:00,  6.36it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 55/55 [00:06<00:00,  8.14it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 69/69 [00:06<00:00,  9.94it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 75/75 [00:06<00:00, 11.26it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 82/82 [00:06<00:00, 12.14it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.12it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:04<00:00,  4.55it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 36/36 [00:05<00:00,  7.16it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_58
Sweep_59
Sweep_60
Sweep_61
Sweep_62
Sweep_63
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C30.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.76s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.75s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_62
Sweep_63
Sweep_64
Sweep_65
Sweep_66
Sweep_67
Sweep_68
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C32.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.57it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.59it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.71s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:02<00:00,  4.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  4.21it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.90it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.19it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_110
Sweep_112
Sweep_12
Sweep_13
Sweep_14
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_MJ_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_MJ_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.72it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.72it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.75it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.73it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.67it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.74it/s]

Fitting failed for sweep Sweep_64: could not broadcast input array from shape (14,) into shape (20,)

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.70it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.70it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.12it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_63
Sweep_65
Sweep_66
Sweep_67
Sweep_68
Sweep_69
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_MJ_A1_C03.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.76s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.20it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.70it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.60it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.49it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.01it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.94it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.09it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.08it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.83it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.95it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.88it/s]

Sweep_0
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_MJ_A1_C06.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  2.71it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.01it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 61/61 [00:04<00:00, 12.31it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 62/62 [00:05<00:00, 12.09it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 27/27 [00:05<00:00,  5.22it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  2.95it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.41it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.94it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.45it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.12it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.67it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 36/36 [00:06<00:00,  5.34it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 47/47 [00:06<00:00,  6.96it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 56/56 [00:06<00:00,  8.35it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_3
Sweep_4
Sweep_42
Sweep_44
Sweep_45
Sweep_46
Sweep_47
Sweep_48
Sweep_49
Sweep_50
Sweep_52
Sweep_53
Sweep_54
Sweep_6
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_MJ_A1_C10.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.62it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.00it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.04it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11
Sweep_12
Sweep_13
Sweep_14
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_MJ_A1_C11.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_MJ_A1_C12.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.20it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13
Sweep_14
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_SA_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 29/29 [00:05<00:00,  5.53it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 34/34 [00:05<00:00,  6.22it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 38/38 [00:05<00:00,  7.57it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 40/40 [00:04<00:00,  8.11it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 44/44 [00:05<00:00,  8.67it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.13it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:02<00:00,  4.47it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 32/32 [00:03<00:00,  8.60it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 35/35 [00:04<00:00,  8.06it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 40/40 [00:04<00:00,  8.65it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 43/43 [00:04<00:00,  9.73it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 46/46 [00:04<00:00, 10.11it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.69it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.86it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.19it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_140
Sweep_141
Sweep_142
Sweep_143
Sweep_144
Sweep_21
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_6
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_SA_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 141/141 [00:04<00:00, 28.39it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 163/163 [00:05<00:00, 30.42it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 183/183 [00:05<00:00, 33.42it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 196/196 [00:05<00:00, 34.46it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 210/210 [00:05<00:00, 36.20it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 82/82 [00:04<00:00, 17.80it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 114/114 [00:06<00:00, 17.76it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_57
Sweep_58
Sweep_59
Sweep_60
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_SA_A1_C03.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:06<00:00,  3.26it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 26/26 [00:06<00:00,  3.90it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:06<00:00,  3.48it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 34/34 [00:06<00:00,  5.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  4.97it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.78it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:04<00:00,  1.84it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:05<00:00,  2.83it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_6
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_SA_A1_C05.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.08it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_68
Sweep_70
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_SA_A1_C06.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 31/31 [00:03<00:00,  8.97it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 40/40 [00:04<00:00,  9.79it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 45/45 [00:05<00:00,  8.82it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 28/28 [00:04<00:00,  5.81it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.77it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.79it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.78it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.84it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.46it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 30/30 [00:05<00:00,  5.85it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 44/44 [00:05<00:00,  7.98it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.17s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 26/26 [00:04<00:00,  6.12it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.58it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:05<00:00,  4.39it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 32/32 [00:05<00:00,  5.55it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 37/37 [00:05<00:00,  6.30it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 41/41 [00:06<00:00,  6.65it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 37/37 [00:06<00:00,  5.88it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:06<00:00,  4.05it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.53it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 22/22 [00:06<00:00,  3.52it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:04<00:00,  2.42it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.53it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.15it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:05<00:00,  2.94it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 26/26 [00:05<00:00,  4.93it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.14it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 32/32 [00:04<00:00,  6.80it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 36/36 [00:04<00:00,  8.00it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 40/40 [00:04<00:00,  8.83it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 33/33 [00:04<00:00,  7.05it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 30/30 [00:04<00:00,  6.32it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:04<00:00,  3.72it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.80it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_18
Sweep_19
Sweep_2
Sweep_20
Sweep_3
Sweep_4
Sweep_64
Sweep_66
Sweep_72
Sweep_73
Sweep_74
Sweep_75
Sweep_76
Sweep_77
Sweep_78
Sweep_79
Sweep_8
Sweep_80
Sweep_81
Sweep_82
Sweep_83
Sweep_84
Sweep_85
Sweep_87
Sweep_88
Sweep_89
Sweep_9
Sweep_90
Sweep_91
Sweep_92
Sweep_93
Sweep_94
Sweep_95
Sweep_96
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_SA_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 29/29 [00:04<00:00,  5.84it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 79/79 [00:05<00:00, 15.01it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 93/93 [00:05<00:00, 16.80it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 104/104 [00:05<00:00, 18.44it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 115/115 [00:05<00:00, 19.24it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 126/126 [00:06<00:00, 20.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.91it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 77/77 [00:06<00:00, 11.93it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 91/91 [00:06<00:00, 14.40it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 107/107 [00:05<00:00, 18.26it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 121/121 [00:05<00:00, 22.01it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 133/133 [00:05<00:00, 25.33it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]

Sweep_100
Sweep_101
Sweep_102
Sweep_103
Sweep_104
Sweep_105
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_88
Sweep_89
Sweep_90
Sweep_99
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_SA_A1_C08.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 104/104 [00:03<00:00, 31.41it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 121/121 [00:03<00:00, 30.61it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 136/136 [00:04<00:00, 30.38it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 151/151 [00:04<00:00, 33.86it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 160/160 [00:04<00:00, 35.70it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 172/172 [00:04<00:00, 37.37it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 182/182 [00:04<00:00, 38.57it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 34/34 [00:03<00:00, 10.57it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 58/58 [00:04<00:00, 12.18it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 85/85 [00:04<00:00, 17.37it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_46
Sweep_47
Sweep_48
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_SA_A1_C10.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████| 108/108 [00:05<00:00, 21.41it/s]

Fitting failed for sweep Sweep_0: Length of values (109) does not match length of index (108)

Spike: 100%|███████████████████████████████████████████████████████████████████████████| 88/88 [00:05<00:00, 17.30it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 106/106 [00:05<00:00, 19.83it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 85/85 [00:05<00:00, 15.92it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 92/92 [00:05<00:00, 16.55it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 101/101 [00:05<00:00, 17.35it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 107/107 [00:06<00:00, 17.42it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 112/112 [00:06<00:00, 17.77it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 115/115 [00:06<00:00, 17.57it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 115/115 [00:06<00:00, 17.97it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 114/114 [00:06<00:00, 17.94it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 60/60 [00:04<00:00, 13.59it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 121/121 [00:05<00:00, 22.60it/s]

Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_2
Sweep_3
Sweep_39
Sweep_4
Sweep_40
Sweep_41
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_SA_A1_C11.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.58it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.19it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.80it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.47it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.64it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.73it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_151
Sweep_157
Sweep_158
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_SA_A1_C14.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_115
Sweep_116
Sweep_119
Sweep_12
Sweep_120
Sweep_13
Sweep_14
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_SA_A1_C15.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.48s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.48s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.48s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.09it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.09it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]

Sweep_101
Sweep_102
Sweep_103
Sweep_104
Sweep_105
Sweep_106
Sweep_107
Sweep_108
Sweep_109
Sweep_110
Sweep_111
Sweep_112
Sweep_113
Sweep_114
Sweep_115
Sweep_116
Sweep_117
Sweep_118
Sweep_119
Sweep_120
Sweep_121
Sweep_122
Sweep_123
Sweep_124
Sweep_125
Sweep_126
Sweep_127
Sweep_128
Sweep_129
Sweep_18
Sweep_97
Sweep_98
file added

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

In [66]:
M10_df.tail()

,ramp_amp,inflection_time,inflection_amp,peak_amp,peak_width,peak_sharpness,exp_lambda,exp_const,isi,r_squared_ramp,r_squared_exp,Sweep_#,file_name,dendriticType,SomaLayerLoc,brainOrigin,Weight,Sex,Age,Species
0,5.624321,0.70,-51.312257,35.900880,1.05,2.520752,1.306941,-55.665414,0.0,0.999225,0.998378,Sweep_129,M10_SA_A1_C15,NA,NA,PFC,5.1,M,5.11,Macaca fascicularis
1,5.624321,0.70,-51.312257,35.900880,1.05,2.520752,1.306941,-55.665414,NaN,0.999225,0.998378,Sweep_129,M10_SA_A1_C15,NA,NA,PFC,5.1,M,5.11,Macaca fascicularis
0,2.568433,0.75,-33.911134,30.499268,1.05,2.270508,0.935556,-49.614184,NaN,0.945924,0.999244,Sweep_18,M10_SA_A1_C15,NA,NA,PFC,5.1,M,5.11,Macaca fascicularis
0,3.764814,0.70,-49.493409,37.994386,1.05,3.094482,1.342215,-54.548994,NaN,0.996289,0.998179,Sweep_97,M10_SA_A1_C15,NA,NA,PFC,5.1,M,5.11,Macaca fascicularis
0,3.466705,0.75,-48.797609,37.640382,1.05,3.399658,1.288728,-54.044722,NaN,0.764764,0.998636,Sweep_98,M10_SA_A1_C15,NA,NA,PFC,5.1,M,5.11,Macaca fascicularis

In [14]:
file_paths7 = get_file_paths(r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M11")
M11_df = monkey_df(file_paths7, 130)

save_dataframe_to_pickle(M11_df, r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M11_df.pkl")

C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M11\M11_SA_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.81it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.93it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.67it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.66it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.38it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_42
Sweep_43
Sweep_44
Sweep_45
Sweep_46
Sweep_47
Sweep_7
Sweep_8
Sweep_9

In [15]:
M11_df.tail()

,ramp_amp,inflection_time,inflection_amp,peak_amp,peak_width,peak_sharpness,exp_lambda,exp_const,isi,r_squared_ramp,r_squared_exp,Sweep_#,file_name,dendriticType,SomaLayerLoc,brainOrigin,Weight,Sex,Age,Species
3,4.384619,0.65,-40.948487,24.346924,0.85,2.746582,1.752491,-56.577616,41.75,0.947650,0.996799,Sweep_9,M11_SA_A1_C02,S,3,V1,10.6,M,12.69,Macaca mulatta
4,4.359746,0.65,-39.117433,22.375489,0.85,2.416992,1.732443,-56.075213,41.95,0.951499,0.996658,Sweep_9,M11_SA_A1_C02,S,3,V1,10.6,M,12.69,Macaca mulatta
5,4.354973,0.70,-40.454102,22.973633,0.85,2.261353,1.809240,-56.006935,40.95,0.950477,0.996328,Sweep_9,M11_SA_A1_C02,S,3,V1,10.6,M,12.69,Macaca mulatta
6,3.985642,0.70,-40.075684,22.393799,0.85,2.340698,1.760836,-55.809571,47.15,0.960559,0.996670,Sweep_9,M11_SA_A1_C02,S,3,V1,10.6,M,12.69,Macaca mulatta
7,4.839124,0.75,-37.615968,20.031739,0.85,2.011108,1.737839,-55.304615,NaN,0.959954,0.996909,Sweep_9,M11_SA_A1_C02,S,3,V1,10.6,M,12.69,Macaca mulatta

In [67]:
file_paths8 = get_file_paths(r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12")
M12_df = monkey_df(file_paths8, 131)

save_dataframe_to_pickle(M12_df, r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12_df.pkl")

C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_JS_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 163/163 [00:03<00:00, 46.08it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 174/174 [00:03<00:00, 49.60it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 177/177 [00:03<00:00, 49.30it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 177/177 [00:03<00:00, 46.58it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 144/144 [00:03<00:00, 38.13it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  4.05it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 125/125 [00:03<00:00, 36.79it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 147/147 [00:03<00:00, 42.41it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_41
Sweep_42
Sweep_43
Sweep_44
Sweep_45
Sweep_46
Sweep_47
Sweep_48
Sweep_49
Sweep_50
Sweep_51
Sweep_52
Sweep_53
Sweep_54
Sweep_55
Sweep_56
Sweep_57
Sweep_58
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_JS_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:03<00:00,  4.99it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.75it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:03<00:00,  5.79it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 22/22 [00:03<00:00,  5.84it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:03<00:00,  6.07it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.39it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  4.08it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.39it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_154
Sweep_155
Sweep_156
Sweep_6
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_JS_A1_C04.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.44s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.19it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_28
Sweep_29
Sweep_30
Sweep_31
Sweep_32
Sweep_33
Sweep_34
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_JS_A1_C05.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.44s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_55
Sweep_56
Sweep_57
Sweep_58
Sweep_59
Sweep_60
Sweep_61
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_JS_A1_C08.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_4
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_JS_A1_C11.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 133/133 [00:03<00:00, 36.77it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 136/136 [00:03<00:00, 39.79it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 98/98 [00:03<00:00, 29.37it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 58/58 [00:03<00:00, 16.49it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:03<00:00,  5.19it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 88/88 [00:03<00:00, 26.30it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 106/106 [00:03<00:00, 30.29it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 119/119 [00:03<00:00, 32.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 128/128 [00:03<00:00, 33.29it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_30
Sweep_32
Sweep_33
Sweep_34
Sweep_5
Sweep_6
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_JS_A1_C12.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 30/30 [00:03<00:00,  8.01it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 152/152 [00:04<00:00, 37.30it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 158/158 [00:04<00:00, 38.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 134/134 [00:04<00:00, 32.55it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.11it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.13it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_5
Sweep_6
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_JS_A1_C14.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.06it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.64it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Fitting failed for sweep Sweep_11: could not broadcast input array from shape (12,) into shape (20,)

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.95it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.06it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 31/31 [00:03<00:00,  7.77it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 34/34 [00:03<00:00,  8.51it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 37/37 [00:04<00:00,  9.11it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  2.99it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  2.95it/s]

Fitting failed for sweep Sweep_9: could not broadcast input array from shape (14,) into shape (20,)
Sweep_10
Sweep_3
Sweep_4
Sweep_5
Sweep_6
Sweep_7
Sweep_8
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_SA_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.88s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_47
Sweep_48
Sweep_49
Sweep_50
Sweep_51
Sweep_52
Sweep_53
Sweep_54
Sweep_55
Sweep_56
Sweep_57
Sweep_58
Sweep_59
Sweep_60
Sweep_61
Sweep_62
Sweep_63
Sweep_64
Sweep_65
Sweep_66
Sweep_67
Sweep_68
Sweep_69
Sweep_70
Sweep_71
Sweep_72
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_SA_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12
Sweep_84
Sweep_85
Sweep_86
Sweep_87
Sweep_88
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_SA_A1_C08.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_57
Sweep_58
Sweep_59
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_SA_A1_C09.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11
Sweep_12
Sweep_13
Sweep_14
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_SA_A1_C10.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.78it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_14
Sweep_26
Sweep_27
Sweep_28
Sweep_29
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_SA_A1_C11.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.67it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.76it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.32it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.04it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.53it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.53it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.16it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_102
Sweep_103
Sweep_104
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_SA_A1_C13.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_21
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_SA_A1_C14.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]

Sweep_11
Sweep_12
Sweep_13
Sweep_14
file added

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

In [68]:
M12_df.tail()

,ramp_amp,inflection_time,inflection_amp,peak_amp,peak_width,peak_sharpness,exp_lambda,exp_const,isi,r_squared_ramp,r_squared_exp,Sweep_#,file_name,dendriticType,SomaLayerLoc,brainOrigin,Weight,Sex,Age,Species
1,6.263217,0.55,-38.110111,12.994629,0.55,3.976440,10.000000,-49.644095,NaN,0.997178,0.094598,Sweep_28,M12_SA_A1_C13,NA,NA,LIP,16.2,M,14.38,Macaca mulatta
0,3.142255,0.60,-44.312992,20.915285,0.75,2.908326,3.051178,-53.659981,NaN,0.985559,0.998535,Sweep_11,M12_SA_A1_C14,NA,NA,LIP,16.2,M,14.38,Macaca mulatta
0,4.129373,0.55,-45.716801,21.824709,0.75,3.527832,3.224466,-52.940475,NaN,0.987189,0.997524,Sweep_12,M12_SA_A1_C14,NA,NA,LIP,16.2,M,14.38,Macaca mulatta
0,4.780384,0.50,-49.348392,20.988527,0.70,4.699708,3.410526,-55.296365,NaN,0.991280,0.996018,Sweep_13,M12_SA_A1_C14,NA,NA,LIP,16.2,M,14.38,Macaca mulatta
0,5.296567,0.55,-51.661625,18.608156,0.75,3.240968,3.537176,-55.982380,NaN,0.996950,0.991853,Sweep_14,M12_SA_A1_C14,NA,NA,LIP,16.2,M,14.38,Macaca mulatta

In [71]:
file_paths9 = get_file_paths(r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19")
M19_df = monkey_df(file_paths9, 147)

save_dataframe_to_pickle(M19_df, r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19_df.pkl")

C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_JS_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_36
Sweep_39
Sweep_44
Sweep_45
Sweep_46
Sweep_47
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_JS_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.73it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.20it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.19it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.74it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.74it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.75it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.75it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_5
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_JS_A1_C03.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12
Sweep_13
Sweep_14
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_JS_A1_C04.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.47it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.47it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.83it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.49it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.06it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.51it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.19it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_JS_A1_C05.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.50it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.65it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.91it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.06it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 38/38 [00:03<00:00, 11.47it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.84s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.72it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.20it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.55it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.81s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_7
Sweep_8
Sweep_87
Sweep_88
Sweep_89
Sweep_9
Sweep_90
Sweep_91
Sweep_92
Sweep_93
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_JS_A1_C06.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12
Sweep_13
Sweep_14
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_JS_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.75it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.52it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.10it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.21it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.20it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_60
Sweep_62
Sweep_63
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_JS_A1_C08.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.79s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.72it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.77it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.71it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.58it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.05it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.33it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_175
Sweep_176
Sweep_177
Sweep_178
Sweep_179
Sweep_30
Sweep_31
Sweep_32
Sweep_33
Sweep_34
Sweep_35
Sweep_36
Sweep_37
Sweep_38
Sweep_39
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_JS_A1_C09.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.22it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.71it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.74it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.49it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.71it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.60it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_6
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_JS_A1_C10.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:02<00:00,  4.53it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.58it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.52it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:03<00:00,  5.32it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:03<00:00,  6.51it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.08it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.06it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.49it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.12it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_8
Sweep_87
Sweep_88
Sweep_89
Sweep_9
Sweep_90
Sweep_91
Sweep_92
Sweep_93
Sweep_94
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_JS_A1_C11.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.74it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.71it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_JS_A1_C13.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 62/62 [00:03<00:00, 19.04it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 80/80 [00:03<00:00, 23.38it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 97/97 [00:03<00:00, 25.72it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 114/114 [00:04<00:00, 27.46it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 129/129 [00:04<00:00, 32.02it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.71it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 44/44 [00:03<00:00, 12.26it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_53
Sweep_54
Sweep_55
Sweep_56
Sweep_57
Sweep_58
Sweep_59
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_JS_A1_C14.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.73it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.69it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.09it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.11it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.51it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.81s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_18
Sweep_65
Sweep_66
Sweep_67
Sweep_68
Sweep_69
Sweep_70
Sweep_71
Sweep_72
Sweep_73
Sweep_74
Sweep_75
Sweep_76
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_JS_A1_C15.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.52it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.85it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:02<00:00,  4.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.68it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.75it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.97it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  3.72it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.36it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.20it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.21it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.25it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.27it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.01it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.22it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.03it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  3.50it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_18
Sweep_19
Sweep_20
Sweep_21
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_30
Sweep_31
Sweep_32
Sweep_33
Sweep_34
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_MM_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  3.82it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 22/22 [00:03<00:00,  5.82it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:03<00:00,  4.32it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.37it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.25it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.03it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.65it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  4.18it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.95it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.85it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  4.10it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_MM_A1_C02.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_MM_A1_C03.nwb
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_MM_A1_C05.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.12it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  3.77it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.84it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.00it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.25it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11
Sweep_17
Sweep_18
Sweep_19
Sweep_20
Sweep_21
Sweep_22
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_MM_A1_C06.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 39/39 [00:03<00:00,  9.98it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 48/48 [00:04<00:00, 11.75it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 61/61 [00:04<00:00, 14.58it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 73/73 [00:04<00:00, 16.88it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 86/86 [00:04<00:00, 20.16it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.76it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.81it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 56/56 [00:03<00:00, 16.12it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 65/65 [00:03<00:00, 17.63it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.35it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_67
Sweep_68
Sweep_69
Sweep_70
Sweep_71
Sweep_72
Sweep_73
Sweep_74
Sweep_85
Sweep_86
Sweep_87
Sweep_88
Sweep_89
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_MM_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 58/58 [00:03<00:00, 16.95it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 73/73 [00:03<00:00, 19.67it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 87/87 [00:03<00:00, 22.04it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.85s/it]

Sweep_13
Sweep_14
Sweep_30
Sweep_31
Sweep_32
Sweep_33
Sweep_34
Sweep_9
Sweep_91
Sweep_94
Sweep_95
Sweep_96
Sweep_97
Sweep_98
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_MM_A1_C08.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.85s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_30
Sweep_31
Sweep_32
Sweep_33
Sweep_34
Sweep_35
Sweep_36
Sweep_37
Sweep_38
Sweep_39
Sweep_40
Sweep_41
Sweep_44
Sweep_45
Sweep_48
Sweep_49
Sweep_51
Sweep_52
Sweep_53
Sweep_54
Sweep_56
Sweep_57
Sweep_58
Sweep_59
Sweep_60
Sweep_61
Sweep_62
Sweep_63
Sweep_64
Sweep_65
Sweep_66
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_MM_A1_C09.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_17
Sweep_18
Sweep_19
Sweep_20
Sweep_21
Sweep_22
Sweep_78
Sweep_79
Sweep_80
Sweep_81
Sweep_82
Sweep_83
Sweep_84
Sweep_85
Sweep_86
Sweep_87
Sweep_88
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_MM_A1_C10.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.39it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  4.27it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:02<00:00,  4.69it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.84it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.83it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.80s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.47it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_18
Sweep_19
Sweep_29
Sweep_30
Sweep_31
Sweep_32
Sweep_33
Sweep_34
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_MM_A1_C11.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.20it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_80
Sweep_82
Sweep_83
Sweep_84
Sweep_85
Sweep_86
Sweep_87
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_SA_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.47it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.81it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.34it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11
Sweep_12
Sweep_13
Sweep_14
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_SA_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_65
Sweep_66
Sweep_75
Sweep_76
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_SA_A1_C03.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.78s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.21it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.53it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  4.31it/s]

Sweep_6
Sweep_66
Sweep_67
Sweep_68
Sweep_69
Sweep_7
Sweep_70
Sweep_71
Sweep_72
Sweep_73
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_SA_A1_C05.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_6
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_SA_A1_C06.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.16it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_6
Sweep_84
Sweep_85
Sweep_86
Sweep_87
Sweep_88
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_SA_A1_C08.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_55
Sweep_56
Sweep_59
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_SA_A1_C09.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_SA_A1_C10.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.11it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:02<00:00,  4.50it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11
Sweep_12
Sweep_13
Sweep_14
file added

In [72]:
M19_df.tail()

,ramp_amp,inflection_time,inflection_amp,peak_amp,peak_width,peak_sharpness,exp_lambda,exp_const,isi,r_squared_ramp,r_squared_exp,Sweep_#,file_name,dendriticType,SomaLayerLoc,brainOrigin,Weight,Sex,Age,Species
8,1.006392,0.40,-32.806397,5.126953,0.40,6.530762,7.080046,-45.984471,179.90,0.909565,0.810322,Sweep_14,M19_SA_A1_C10,NA,NA,V1,14.6,M,14,Macaca fascicularis
9,1.422165,0.45,-30.914307,5.889893,0.40,5.783081,5.853469,-46.889182,56.20,0.907662,0.941953,Sweep_14,M19_SA_A1_C10,NA,NA,V1,14.6,M,14,Macaca fascicularis
10,1.713574,0.45,-29.846192,5.950928,0.40,5.493164,6.284264,-46.386262,263.10,0.955074,0.886901,Sweep_14,M19_SA_A1_C10,NA,NA,V1,14.6,M,14,Macaca fascicularis
11,1.909529,0.45,-30.212403,5.676270,0.35,5.187988,6.138267,-46.991332,138.65,0.989066,0.926262,Sweep_14,M19_SA_A1_C10,NA,NA,V1,14.6,M,14,Macaca fascicularis
12,1.524043,0.45,-30.059815,6.103516,0.40,5.844116,5.572046,-46.961211,NaN,0.885470,0.956144,Sweep_14,M19_SA_A1_C10,NA,NA,V1,14.6,M,14,Macaca fascicularis

In [73]:
file_paths10 = get_file_paths(r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20")
M20_df = monkey_df(file_paths10, 174)

save_dataframe_to_pickle(M20_df, r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20_df.pkl")

C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_JS_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.10it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:03<00:00,  5.92it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.81it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 45/45 [00:03<00:00, 13.87it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 108/108 [00:03<00:00, 30.93it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 130/130 [00:03<00:00, 35.21it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 151/151 [00:03<00:00, 39.40it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13
Sweep_14
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_JS_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.73it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 84/84 [00:03<00:00, 23.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 103/103 [00:03<00:00, 27.24it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 113/113 [00:03<00:00, 28.56it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 109/109 [00:03<00:00, 27.86it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 71/71 [00:03<00:00, 18.09it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:03<00:00,  6.38it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.85s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.19it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_50
Sweep_51
Sweep_52
Sweep_53
Sweep_54
Sweep_55
Sweep_56
Sweep_57
Sweep_58
Sweep_59
Sweep_60
Sweep_61
Sweep_62
Sweep_63
Sweep_64
Sweep_65
Sweep_66
Sweep_67
Sweep_68
Sweep_69
Sweep_70
Sweep_71
Sweep_72
Sweep_73
Sweep_74
Sweep_75
Sweep_76
Sweep_77
Sweep_78
Sweep_79
Sweep_80
Sweep_81
Sweep_82
Sweep_83
Sweep_84
Sweep_85
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_JS_A1_C03.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 119/119 [00:03<00:00, 35.65it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 153/153 [00:03<00:00, 45.49it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 56/56 [00:03<00:00, 17.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 104/104 [00:03<00:00, 31.20it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 137/137 [00:03<00:00, 38.51it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 168/168 [00:03<00:00, 44.53it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 188/188 [00:03<00:00, 48.36it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 205/205 [00:04<00:00, 50.79it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.88it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 81/81 [00:03<00:00, 24.83it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

Sweep_0
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_20
Sweep_21
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_45
Sweep_48
Sweep_50
Sweep_51
Sweep_52
Sweep_53
Sweep_54
Sweep_55
Sweep_56
Sweep_57
Sweep_58
Sweep_59
Sweep_60
Sweep_61
Sweep_62
Sweep_63
Sweep_64
Sweep_65
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_MM_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.67it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 174/174 [00:03<00:00, 50.06it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_14
Sweep_38
Sweep_39
Sweep_40
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_MM_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.88s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.76s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.81s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.70it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.76it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.20it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_151
Sweep_152
Sweep_153
Sweep_154
Sweep_155
Sweep_156
Sweep_157
Sweep_158
Sweep_159
Sweep_160
Sweep_161
Sweep_162
Sweep_163
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_30
Sweep_31
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_MM_A1_C03.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.79s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.88s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.80s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.82s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 50/50 [00:03<00:00, 15.21it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  3.93it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 49/49 [00:03<00:00, 14.98it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 62/62 [00:03<00:00, 18.58it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 64/64 [00:03<00:00, 18.48it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 79/79 [00:03<00:00, 22.04it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 90/90 [00:03<00:00, 23.83it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 101/101 [00:03<00:00, 25.78it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 110/110 [00:04<00:00, 27.49it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 121/121 [00:03<00:00, 30.92it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 133/133 [00:04<00:00, 32.79it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 142/142 [00:04<00:00, 34.66it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_115
Sweep_116
Sweep_118
Sweep_119
Sweep_120
Sweep_121
Sweep_122
Sweep_123
Sweep_13
Sweep_138
Sweep_139
Sweep_14
Sweep_140
Sweep_141
Sweep_142
Sweep_143
Sweep_144
Sweep_145
Sweep_146
Sweep_147
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_MM_A1_C04.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.09it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_18
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_MM_A1_C05.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.19it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.20it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_67
Sweep_68
Sweep_69
Sweep_70
Sweep_71
Sweep_72
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_MM_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.54it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.76it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.19it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.87it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_18
Sweep_19
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_SA_A1_C01.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.85it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.83it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.56it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.67it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]

Fitting failed for sweep Sweep_62: All fits failed.

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]

Fitting failed for sweep Sweep_63: All fits failed.

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.13it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.77it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  4.13it/s]

Sweep_0
Sweep_10
Sweep_11
Sweep_12
Sweep_5
Sweep_6
Sweep_64
Sweep_66
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_SA_A1_C02.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████| 216/216 [00:03<00:00, 55.50it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.22it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.71it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.71it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.26it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 56/56 [00:03<00:00, 14.35it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 102/102 [00:04<00:00, 25.00it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 141/141 [00:04<00:00, 34.00it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 172/172 [00:04<00:00, 40.71it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

Sweep_0
Sweep_1
Sweep_2
Sweep_3
Sweep_4
Sweep_5
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_SA_A1_C03.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 136/136 [00:04<00:00, 32.49it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.88s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 59/59 [00:03<00:00, 16.93it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 95/95 [00:03<00:00, 25.09it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 120/120 [00:04<00:00, 25.36it/s]

Sweep_10
Sweep_36
Sweep_37
Sweep_38
Sweep_39
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_SA_A1_C04.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.74it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.75it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.73it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_18
Sweep_19
Sweep_52
Sweep_53
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_SA_A1_C05.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.12it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:03<00:00,  6.32it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 22/22 [00:05<00:00,  3.97it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:05<00:00,  4.07it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:05<00:00,  3.64it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:05<00:00,  2.90it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.47it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.31it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.85s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_18
Sweep_19
Sweep_34
Sweep_35
Sweep_36
Sweep_37
Sweep_38
Sweep_39
Sweep_40
Sweep_41
Sweep_42
Sweep_43
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_SA_A1_C06.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.24it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 53/53 [00:05<00:00,  9.33it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 63/63 [00:05<00:00, 12.12it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 76/76 [00:04<00:00, 15.35it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.83it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_SA_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:02<00:00,  4.55it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 28/28 [00:04<00:00,  6.75it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 35/35 [00:04<00:00,  8.30it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_50
Sweep_52
Sweep_6
Sweep_7
Sweep_8
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_SA_A1_C08.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.43it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.05it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  3.56it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.54it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  2.99it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.84s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.86it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.29it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.79it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.09it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_27
Sweep_30
Sweep_31
Sweep_5
Sweep_6
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_SA_A1_C09.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 53/53 [00:03<00:00, 14.57it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 69/69 [00:04<00:00, 14.56it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 85/85 [00:04<00:00, 17.75it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 99/99 [00:04<00:00, 20.44it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 111/111 [00:04<00:00, 22.23it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 124/124 [00:05<00:00, 23.98it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 133/133 [00:05<00:00, 25.36it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 137/137 [00:05<00:00, 25.45it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 94/94 [00:05<00:00, 17.26it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 35/35 [00:05<00:00,  6.30it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 37/37 [00:04<00:00,  7.74it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_18
Sweep_19
Sweep_72
Sweep_73
Sweep_9
file added

In [74]:
M20_df.tail()

,ramp_amp,inflection_time,inflection_amp,peak_amp,peak_width,peak_sharpness,exp_lambda,exp_const,isi,r_squared_ramp,r_squared_exp,Sweep_#,file_name,dendriticType,SomaLayerLoc,brainOrigin,Weight,Sex,Age,Species
32,3.298193,0.50,-41.036865,6.662109,0.50,5.508423,5.109029,-60.165338,26.15,0.972683,0.945229,Sweep_9,M20_SA_A1_C09,NA,NA,V1,14.6,M,12.14,Macaca mulatta
33,2.921427,0.50,-42.013428,7.089355,0.45,5.905151,5.421238,-60.115780,27.80,0.950971,0.918817,Sweep_9,M20_SA_A1_C09,NA,NA,V1,14.6,M,12.14,Macaca mulatta
34,3.730946,0.50,-40.548584,6.417969,0.45,5.371094,4.958169,-59.693936,27.80,0.979412,0.957650,Sweep_9,M20_SA_A1_C09,NA,NA,V1,14.6,M,12.14,Macaca mulatta
35,3.103615,0.50,-41.891357,6.784180,0.45,5.844116,5.202848,-59.844698,7587.45,0.962617,0.944353,Sweep_9,M20_SA_A1_C09,NA,NA,V1,14.6,M,12.14,Macaca mulatta
36,0.036254,0.85,-67.068359,12.674072,0.45,10.284424,6.316283,-64.756362,NaN,0.094038,0.971125,Sweep_9,M20_SA_A1_C09,NA,NA,V1,14.6,M,12.14,Macaca mulatta

In [75]:
file_paths11 = get_file_paths(r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M21")
M21_df = monkey_df(file_paths11, 188)

save_dataframe_to_pickle(M21_df, r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M21_df.pkl")

C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M21\M21_MM_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 57/57 [00:06<00:00,  9.05it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 88/88 [00:06<00:00, 13.03it/s]

Fitting failed for sweep Sweep_11: could not broadcast input array from shape (15,) into shape (20,)

Spike: 100%|█████████████████████████████████████████████████████████████████████████| 156/156 [00:07<00:00, 21.33it/s]

Fitting failed for sweep Sweep_12: could not broadcast input array from shape (19,) into shape (20,)

Spike: 100%|███████████████████████████████████████████████████████████████████████████| 97/97 [00:07<00:00, 13.54it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Fitting failed for sweep Sweep_13: could not broadcast input array from shape (3,) into shape (20,)

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.26it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.41it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:05<00:00,  3.02it/s]

Sweep_10
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M21\M21_MM_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.78it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M21\M21_MM_A1_C04.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.73it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 36/36 [00:03<00:00, 10.53it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 46/46 [00:04<00:00, 10.00it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 46/46 [00:04<00:00, 10.37it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 77/77 [00:04<00:00, 17.93it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 97/97 [00:04<00:00, 22.53it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 107/107 [00:04<00:00, 25.57it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 120/120 [00:04<00:00, 29.08it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 131/131 [00:04<00:00, 31.64it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 140/140 [00:04<00:00, 32.57it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 149/149 [00:04<00:00, 33.41it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 164/164 [00:04<00:00, 36.80it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_18
Sweep_19
Sweep_20
Sweep_21
Sweep_22
Sweep_23
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M21\M21_MM_A1_C05.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_18
Sweep_19
Sweep_20
Sweep_21
Sweep_22
Sweep_23
Sweep_24
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M21\M21_MM_A1_C06.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.56it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 55/55 [00:03<00:00, 16.96it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 70/70 [00:03<00:00, 20.70it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 80/80 [00:03<00:00, 22.19it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 94/94 [00:03<00:00, 25.56it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 104/104 [00:03<00:00, 27.05it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.88it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_15
Sweep_16
Sweep_17
Sweep_18
Sweep_19
Sweep_20
Sweep_21
Sweep_23
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M21\M21_MM_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 36/36 [00:03<00:00,  9.60it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 40/40 [00:03<00:00, 10.42it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 49/49 [00:03<00:00, 12.46it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 53/53 [00:03<00:00, 13.40it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.59it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.66it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:03<00:00,  5.04it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 28/28 [00:04<00:00,  6.97it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_15
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M21\M21_SA_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.77it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.23it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 22/22 [00:04<00:00,  5.04it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 28/28 [00:04<00:00,  6.14it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 31/31 [00:04<00:00,  6.93it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 35/35 [00:04<00:00,  7.70it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 38/38 [00:04<00:00,  8.13it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 40/40 [00:04<00:00,  8.43it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 45/45 [00:04<00:00,  9.28it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 44/44 [00:04<00:00,  8.82it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.88s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_18
Sweep_19
Sweep_20
Sweep_21
Sweep_22
Sweep_23
Sweep_27
Sweep_28
Sweep_29
Sweep_30
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M21\M21_SA_A1_C02.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.47it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.52it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 101/101 [00:05<00:00, 19.90it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.44it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.11it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  2.84it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 47/47 [00:05<00:00,  8.10it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 68/68 [00:06<00:00, 10.80it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 91/91 [00:06<00:00, 14.36it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_2
Sweep_3
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M21\M21_SA_A1_C03.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.40it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.49it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:04<00:00,  2.05it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:06<00:00,  2.74it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 22/22 [00:06<00:00,  3.32it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_18
Sweep_19
Sweep_20
Sweep_21
Sweep_22
Sweep_23
Sweep_24
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M21\M21_SA_A1_C04.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 22/22 [00:06<00:00,  3.66it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 48/48 [00:05<00:00,  8.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 64/64 [00:05<00:00, 12.21it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 81/81 [00:05<00:00, 16.02it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 95/95 [00:04<00:00, 19.74it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 108/108 [00:04<00:00, 23.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 119/119 [00:04<00:00, 26.08it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 132/132 [00:04<00:00, 29.37it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 143/143 [00:04<00:00, 32.83it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 152/152 [00:04<00:00, 34.96it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_18
Sweep_19
Sweep_20
Sweep_21
Sweep_22
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M21\M21_SA_A1_C05.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  4.11it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 57/57 [00:04<00:00, 13.17it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 75/75 [00:04<00:00, 16.80it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 93/93 [00:04<00:00, 20.44it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 119/119 [00:04<00:00, 25.16it/s]

Fitting failed for sweep Sweep_9: could not broadcast input array from shape (5,) into shape (20,)
Sweep_4
Sweep_5
Sweep_6
Sweep_7
Sweep_8
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M21\M21_SA_A1_C06.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 38/38 [00:04<00:00,  8.29it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 56/56 [00:04<00:00, 11.63it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 73/73 [00:04<00:00, 14.70it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.78it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M21\M21_SA_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.27it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 27/27 [00:05<00:00,  5.22it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 29/29 [00:05<00:00,  5.25it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 38/38 [00:05<00:00,  7.01it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.45it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_8
Sweep_9
file added

In [76]:
M21_df.tail()

,ramp_amp,inflection_time,inflection_amp,peak_amp,peak_width,peak_sharpness,exp_lambda,exp_const,isi,r_squared_ramp,r_squared_exp,Sweep_#,file_name,dendriticType,SomaLayerLoc,brainOrigin,Weight,Sex,Age,Species
1,2.099518,1.45,-39.785645,42.367676,2.55,0.381470,0.299768,-84.266822,0.00,0.944645,0.994975,Sweep_9,M21_SA_A1_C07,S,3,V1,8.7,M,7.65,Macaca fascicularis
2,2.099518,1.45,-39.785645,42.367676,2.55,0.381470,0.299768,-84.266822,255.00,0.944645,0.994975,Sweep_9,M21_SA_A1_C07,S,3,V1,8.7,M,7.65,Macaca fascicularis
3,2.276198,1.55,-37.100098,40.139893,2.65,0.335693,0.304954,-81.487302,359.55,0.930923,0.994197,Sweep_9,M21_SA_A1_C07,S,3,V1,8.7,M,7.65,Macaca fascicularis
4,2.398728,1.60,-36.886475,38.888672,2.75,0.350952,0.279030,-85.988248,0.00,0.954351,0.993531,Sweep_9,M21_SA_A1_C07,S,3,V1,8.7,M,7.65,Macaca fascicularis
5,2.398728,1.60,-36.886475,38.888672,2.75,0.350952,0.279030,-85.988248,NaN,0.954351,0.993531,Sweep_9,M21_SA_A1_C07,S,3,V1,8.7,M,7.65,Macaca fascicularis

In [1]:
df11 = load_dataframe_from_pickle(r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M11_df.pkl")
df21.head()

NameError: name 'load_dataframe_from_pickle' is not defined