In [38]:
'''
Author: David Brin
Date Rewritten: 1/23/2025

This notebook is a repurposed notebook to recreate the data frame containing all the spikes and their features 
along with the dictionary containing all the spike waveforms that will correspond to the spikes in the data frame via spike ID. 
'''

'\nAuthor: David Brin\nDate Rewritten: 1/23/2025\n\nThis notebook is a repurposed notebook to recreate the data frame containing all the spikes and their features \nalong with the dictionary containing all the spike waveforms that will correspond to the spikes in the data frame via spike ID. \n'

In [39]:
#imports
%matplotlib inline
%config InlineBackend.figure_format = 'retina' # high res plotting

import sys
sys.path.append(r'..\..\..\spikeparam')

from spikeparam.patch.fit import Spike
from spikeparam.patch.fit import SpikeGroup

from neurodsp import spectral

from scipy import signal
import scipy

import h5py
from tqdm import tqdm

import numpy as np
import pandas as pd

from neurodsp import filt
from neurodsp.timefrequency import amp_by_time, phase_by_time
from neurodsp.plts import plot_time_series, plot_instantaneous_measure
from neurodsp.plts.time_series import plot_bursts
from neurodsp.burst import detect_bursts_dual_threshold, compute_burst_stats

from scipy.signal import sosfiltfilt, butter

from scipy.signal import find_peaks
from scipy.optimize import curve_fit
from scipy.stats import pearsonr
import statsmodels.api as sm
from sklearn.metrics.pairwise import cosine_similarity

import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import scipy.spatial as sp_spatial

import os

from fooof import FOOOF

sns.set(rc={'figure.figsize':(12,9)})
sns.set_style('whitegrid')
sns.set_style("whitegrid", {'axes.grid' : False})

import IProgress

import openpyxl
import pickle

## Defining useful functions

In [40]:
# Function to visualize sweep patch data
# no metadata, just the time series data
def extract_data(file_path, plot_data = False):
    # Open the HDF5 file
    with h5py.File(file_path, 'r') as f:
        # Initialize an empty list to store data arrays
        data = []

        # Iterate through keys in the 'acquisition' group
        for sweep_key in f['acquisition'].keys():
            dataset = f['acquisition'][sweep_key]['data'] 
            # Convert the dataset data into a NumPy array and append to the list
            data.append(np.array(dataset))

        # Plot the data
        if(plot_data):
            if all(d.ndim == 1 for d in data):
                for d in data:
                    plt.plot(d)
                plt.xlabel('time (ms)')
                plt.ylabel('mV')
                plt.title('1D Dataset Visualization')
                plt.show()
            elif all(d.ndim == 2 for d in data):
                for d in data:
                    plt.imshow(d, cmap='viridis')
                    plt.colorbar()
                    plt.xlabel('X-axis')
                    plt.ylabel('Y-axis')
                    plt.title('2D Dataset Visualization')
                    plt.show()
            else:
                print("Cannot visualize data with more than 2 dimensions.")



        return data

In [41]:
#collecting file paths

def get_file_paths(folder_path):
    """
    Function to loop through a folder and save file paths.
    
    Args:
    - folder_path (str): Path to the folder to loop through.
    
    Returns:
    - file_paths (list): List of file paths found in the folder.
    """
    file_paths = []
    for root, dirs, files in os.walk(folder_path):
        for file in files:
            file_paths.append(os.path.join(root, file))
    return file_paths

In [42]:
def update_columns_at_index(df, file_path):
    """
    Function to update columns in the DataFrame at a specific index with values from Excel metadata.
    
    Check if filename matches the string in the first cell of the row, drop row if not.

    Args:
    - df (pd.DataFrame): DataFrame to update.
    - file_path (str): Path to the Excel file containing metadata.
    
    Returns:
    - true if updated
    """
    # Extract filename from file_path
    filename = os.path.splitext(os.path.basename(file_path))[0]
    
    # Load the workbook
        #wb = openpyxl.load_workbook(r"C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\ephys_features_filenames (1).xlsx")
    metadf = pd.read_excel(r"C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\ephys_features_filenames (1).xlsx")
        # Select the active worksheet
        #ws = wb.active

    

    # Filter the metadata DataFrame to find the row associated with this file
    file_metadata = metadf[metadf['file_name'] == filename]
    #print(file_metadata.head())
    if not file_metadata.empty:    
        for col in file_metadata.columns:
            #print(col)
            df[col] = file_metadata[col].values[0]  # Assign metadata value to the entire column
 
        return True
    
    else:
        print(f"No metadata found for file: {filename}")
        return False

In [43]:
def monkey_df_and_dict(filepaths):
    """
    Creates a DataFrame and dictionary of spike data for all files in the given filepaths (Monkey Directoru.

    Parameters:
    - filepaths: List of file paths to process.
    - ind_start: Starting index for the metadata cols for 'update_columns_at_index' for the monkey data frame.

    Returns:
    - super_mega_df: A concatenated DataFrame of spike features for all files.
    """
    super_mega_df = pd.DataFrame()
    monkey_dict = {}  # Monkey dictionary
    file_num = 0

    for file in filepaths:
        print(file)
        # Extract data for all sweeps in the file
        data = extract_data(file, plot_data=False)  # Numpy array of all sweeps in the file
        spike_dir = {}  # Dictionary of sweeps with spikes
        i = 0
        monkey_id = os.path.basename(os.path.dirname(file))  # Extract Monkey_ID from the directory name
        fileName = os.path.splitext(os.path.basename(file))[0] 
        with h5py.File(file, 'r') as f:
            for sweep_key in f['acquisition'].keys():
                if i < len(data):
                    try:
                        # Fit spike data
                        sweep_key_obj = Spike(thresh_amp=0, window_length=(5., 5.), smooth_frac=.01)
                        sweep_key_obj.fit(data[i], 20000, n_jobs=-1, progress=tqdm)
                        if sweep_key_obj.n_spikes is not None:
                            spike_dir[sweep_key] = sweep_key_obj
                            #print(f'num spikes: {sweep_key_obj.n_spikes} and len df: {len(sweep_key_obj.df_features)}')
                            #print(f"Length of sweep_key_obj.spikes: {len(sweep_key_obj.spikes)}")
                    except ValueError as e:
                        print(f"Fitting failed for sweep {sweep_key}: {e}")
                i += 1

        # Create and concatenate DataFrame with all sweeps
        mega_df = pd.DataFrame()
        mega_dict = {}             #store all spikes in file and concatenate if file appears in metadata spreadsheet
        for i, (sweep_key, sweep_obj) in enumerate(spike_dir.items()):
            print(sweep_key, sweep_obj)
            df = sweep_obj.df_features.copy()  # Copy DataFrame to avoid modifying the original
            
            df['Sweep_#'] = sweep_key
            df['Spike_#'] = range(0, len(df))  # Add Spike_# as a column
            
            # Create Spike_IDs in the desired format
            df['Spike_ID'] = df.apply(
                lambda row: f"{monkey_id}f{file_num}Sw{sweep_key}Sp{row['Spike_#']}", axis=1
            )
            #display(df)
            for spike in range(len(df)):
                key = f"{monkey_id}f{file_num}Sw{sweep_key}Sp{spike}"                      
                mega_dict[key] = sweep_obj.spikes[spike]
            # Concatenate the current DataFrame to the mega DataFrame
            
            mega_df = pd.concat([mega_df, df], axis=0)
            #print(f'num spikes: {sweep_obj.n_spikes} and len df: {len(sweep_obj.df_features)}')

        # Update columns and append to the super_mega_df
        exists = update_columns_at_index(mega_df, file)
        if exists:
            super_mega_df = pd.concat([super_mega_df, mega_df], axis=0)
            monkey_dict.update(mega_dict)
            print("File added")
            print(f"\n\n\n\ndf length: {len(super_mega_df)} \n dict length: {len(monkey_dict.keys())} \n\n\n\n")
        
        file_num += 1

    return super_mega_df, monkey_dict

In [44]:
def create_allMonkey_data(file_paths):
    '''
    cohesive function that calls monkey_df_and_dict on all monkey folders, puts all data into allMonkey_df and combined_dict
    couldn't make it fully adaptable because of 'update_columns_at_index'
    
    returns allMonkey_df, combined_dict
    '''
    allMonkey_df = pd.DataFrame()
    combined_dict = {}
    print("Creating data frame and dictionary")
    for file in file_paths:
        file_list = [os.path.join(file, f) for f in os.listdir(file) if os.path.isfile(os.path.join(file, f))]
        monk_df,monk_dict = monkey_df_and_dict(file_list)     
        if not monk_df.empty:
            allMonkey_df = pd.concat([allMonkey_df, monk_df], axis=0, ignore_index=True)
        else:
            print(f"\n\n\n\n\nWarning: No data found in {file}\n\n\n\n\n\n\n\n\n") #run a check in case empty file
        combined_dict.update(monk_dict)
        print(f"\n\n\n\n\n\n\nconcat df length: {len(allMonkey_df)} \nconcat dict length: {len(combined_dict.keys())} \n\n\n\n\n\n\n")
    return allMonkey_df, combined_dict

In [45]:
# Functions to save a datrame to a pickle file and another to extract the data from the pickle file

def save_dataframe_to_pickle(dataframe, file_path):
    """
    Function to save a DataFrame as a pickle file.
    
    Args:
    - dataframe (pd.DataFrame): DataFrame to be saved.
    - file_path (str): Path to save the pickle file.
    """
    dataframe.to_pickle(file_path)
    print(f"Data frame saved to {file_path}")

def load_dataframe_from_pickle(file_path):
    """
    Function to extract a DataFrame from a pickle file.
    
    Args:
    - file_path (str): Path to the pickle file.
    
    Returns:
    - dataframe (pd.DataFrame): Loaded DataFrame.
    """
    dataframe = pd.read_pickle(file_path)
    return dataframe

def save_dict_to_pickle(dictionary, filepath):
    """
    Save a dictionary to a pickle file.

    Parameters:
        dictionary (dict): The dictionary to save.
        filepath (str): The path to the pickle file.
    """
    with open(filepath, 'wb') as f:
        pickle.dump(dictionary, f)
    print(f"Dictionary saved to {filepath}")


def load_dict_from_pickle(filepath):
    """
    Load a dictionary from a pickle file.

    Parameters:
        filepath (str): The path to the pickle file.

    Returns:
        dict: The loaded dictionary.
    """
    with open(filepath, 'rb') as f:
        dictionary = pickle.load(f)
    print(f"Dictionary loaded from {filepath}")
    return dictionary

## Extracting Data

In [46]:
file_paths = [r"C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M03", r"C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04", r"C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M05"
             ,r"C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M06", r"C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M08"
             , r"C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10", r"C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M11"
             , r"C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M12", r"C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19"
             , r"C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M20", r"C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M21"]

allMonkey_df, combined_dict = create_allMonkey_data(file_paths)
save_dataframe_to_pickle(allMonkey_df, r"C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\allMonkey_df.pkl")
save_dict_to_pickle(combined_dict, r"C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\combined_dict.pkl")

Creating data frame and dictionary
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M03\M03_JS_A1_C01.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:17<00:00,  4.28s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.01it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.87it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.35it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.01it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.85s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.33s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.76s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.11it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F9B2C0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C537D22D0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A0DDF0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58953200>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58952BD0>
Sweep_54 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313C680>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313C830>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F474A0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C531721B0>
File added




df length: 68
 dict length: 68




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M03\M03_JS_A1_C03.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.54it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.46it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.43it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.23it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.33it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.83s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.88s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.88s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F836B0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F4B530>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F821E0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B107D10>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C560A6000>
Sweep_38 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BD790>
Sweep_39 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BE900>
Sweep_40 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380CE30>
File added




df length: 143
 dict length: 143




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M03\M03_JS_A1_C04.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.21it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.81s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.40it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.17it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.38it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.42it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.05it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.44it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.44it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.78s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617F710>
Sweep_101 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBF9E0>
Sweep_102 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBEA20>
Sweep_103 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58945040>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589538C0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313D010>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5A030>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562BBAA0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F58C50>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380C650>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5A4E0>
Sweep_98 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5AC00>
Sweep_99 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F48B90>
File added




df length: 257
 dict length: 257




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M03\M03_JS_A1_C06.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.76s/it]

Fitting failed for sweep Sweep_1: All fits failed.

Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.33it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.37it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.38it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.25it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.40it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.81s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.83s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.34s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.40it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.45it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F55130>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C560A6840>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617F710>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BE8D0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54027EF0>
Sweep_36 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53747920>
Sweep_39 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58937860>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313D010>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894A510>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58955400>
File added




df length: 366
 dict length: 366




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M03\M03_JS_A1_C10.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.46it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.38it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B104C50>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58957980>
File added




df length: 389
 dict length: 389




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M03\M03_JS_A1_C14.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFC5700>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F12C380>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFC4FB0>
File added




df length: 392
 dict length: 392




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M03\M03_JS_A1_C18.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.43it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.51it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.45it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.50it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.20it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.81s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.26it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:04<00:00,  2.74it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.29it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5895C980>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5578F530>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58955520>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F19BD10>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313C830>
Sweep_59 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56287BC0>
Sweep_60 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562876E0>
Sweep_61 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380D3D0>
Sweep_62 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F4B110>
Sweep_63 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56284710>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53171C10>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53746E40>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F47650>
File added




df length: 511
 dict length: 511




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M03\M03_JS_A1_C19.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.37it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  3.00it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.96it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.91it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.33it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.83s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.80s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.34it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.81it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19D730>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53679460>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F591C0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F58C50>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C536519D0>
Sweep_61 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F12C380>
Sweep_62 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0EEAE0>
Sweep_63 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53073410>
Sweep_64 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F80EF0>
Sweep_65 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F802F0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894A5A0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F82300>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4ABA0>
File added




df length: 578
 dict length: 578




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M03\M03_JS_A1_C20.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.72s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.45it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.92it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.31it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.62it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.88it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:04<00:00,  2.42it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.06it/s]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5634CA70>
Sweep_1 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5A720>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894A360>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F49F10>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFC4EC0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F12CF20>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5895D8B0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1918B0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58937C80>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58949BB0>
File added




df length: 675
 dict length: 675




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M03\M03_MW_A1_C03.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:04<00:00,  2.65it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.90it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.28it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.42it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.53it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.37it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.14it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5895D8B0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53679460>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BE900>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC1160>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313C110>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BFF20>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58955520>
File added




df length: 756
 dict length: 756




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M03\M03_MW_A1_C04.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.21it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.81it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.98it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.05it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.99it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.27s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0EE090>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58946360>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384E180>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1075C0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A0AA0>
Sweep_45 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313C620>
Sweep_46 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313C110>
Sweep_50 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617DD30>
Sweep_51 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58936FC0>
Sweep_52 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F44F80>
Sweep_53 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A2600>
Sweep_54 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54C893D0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BD520>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617CE30>
File added




df length: 821
 dict length: 821




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M03\M03_MW_A1_C06.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.16it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.34it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.39it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.03it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.93it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.05it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.56it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313C620>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894AA20>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384E180>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F80230>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1075C0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A734830>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C560A6CF0>
File added




df length: 902
 dict length: 902




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M03\M03_MW_A1_C08.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.79it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.87it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.85it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.62it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.02it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.06it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.95it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.51it/s]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56285850>
Sweep_1 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5F410>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F63770>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5A4E0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F603E0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5B290>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5A720>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B106B70>
Sweep_70 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBEBA0>
Sweep_72 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F44F50>
Sweep_74 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F68E60>
Sweep_75 <spikeparam.patch.fit.fit.Spike object at 0x0000014C560A4620>
Sweep_76 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55799280>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F62840>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFC5AF0>
File added




df length: 984
 dict length: 984




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M03\M03_MW_A1_C09.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.08it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.04it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.66it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0ECB90>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58945A60>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58955520>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA13EC0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B105220>
Sweep_52 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589358B0>
Sweep_53 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F584A0>
Sweep_55 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5D490>
Sweep_56 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F49250>
Sweep_57 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5ED80>
Sweep_58 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53864890>
Sweep_59 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58936D80>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BBF9E80>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBF830>
File added




df length: 1006
 dict length: 1006




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M03\M03_MW_A1_C10.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19D730>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBE0F0>
File added




df length: 1008
 dict length: 1008




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M03\M03_MW_A1_C11.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.34it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:04<00:00,  2.69it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.78s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.13it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.38it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  3.71it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.04it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E4B30>
Sweep_105 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BFB30>
Sweep_107 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F46270>
Sweep_108 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B104B30>
Sweep_109 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F474A0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E7CE0>
Sweep_110 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA11AC0>
Sweep_111 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A3F20>
Sweep_112 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58948710>
Sweep_113 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F49730>
Sweep_114 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894AA20>
Sweep_115 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58949610>
Sweep_116 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5B620>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617EC60>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5A4E0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBD460>
Sweep_2 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5EFC0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A736780>
File added




df length: 1087
 dict length: 1087




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M03\M03_MW_A1_C15.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.67it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.05it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.40it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.46it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.67it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.18it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56287CE0>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C537D02C0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F49880>
Sweep_113 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58955580>
Sweep_118 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1905F0>
Sweep_119 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617F800>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B107E90>
Sweep_120 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1910A0>
Sweep_121 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BD400>
Sweep_122 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F45760>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F45C40>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F49250>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58943E60>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56286660>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFC42C0>
File added




df length: 1174
 dict length: 1174




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M03\M03_MW_A1_C16.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.68it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.01it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  3.92it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.41it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.31it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.06it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.89it/s]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BBF88C0>
Sweep_1 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F12C380>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58949610>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C537D02C0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5634F050>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58955520>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B191B20>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F4A360>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F47CE0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E7D10>
File added




df length: 1252
 dict length: 1252




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M03\M03_SM_A1_C02.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.76s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.81s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F49880>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A33B0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FC080>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BC1C3B0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BD400>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BE180>
File added




df length: 1259
 dict length: 1259




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M03\M03_SM_A1_C04.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:05<00:00,  3.06it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.05it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.78s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617CFE0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBF0E0>
Sweep_51 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBEFF0>
Sweep_52 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA13BC0>
Sweep_53 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5634EC90>
Sweep_54 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B190AA0>
File added




df length: 1294
 dict length: 1294




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M03\M03_SM_A1_C05.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.86s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.78s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.12s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.86s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.07s/it]

Sweep_102 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA11700>
Sweep_103 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F4A450>
Sweep_104 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBC0B0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894AA20>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBEFF0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F49250>
Sweep_97 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F45760>
Sweep_99 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58948710>
File added




df length: 1302
 dict length: 1302




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M03\M03_SM_A1_C07.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.80s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5ED80>
File added




df length: 1303
 dict length: 1303




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M03\M03_SM_A1_C09.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.90s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA13BC0>
File added




df length: 1304
 dict length: 1304




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M03\M03_SM_A1_C14.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.87s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1935C0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A737E60>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589591C0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BD400>
File added




df length: 1308
 dict length: 1308




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M03\M03_SM_A1_C15.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.90s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B105FA0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58936930>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0ED250>
File added




df length: 1311
 dict length: 1311




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M03\M03_SM_A1_C16.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.83s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.88s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.78s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.84s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.92s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1935C0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FC560>
Sweep_115 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFC6D20>
Sweep_116 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589591C0>
Sweep_117 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617E3F0>
Sweep_118 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58935BB0>
Sweep_119 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B69A330>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0EC140>
Sweep_120 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617C2F0>
Sweep_121 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BDA90>
Sweep_122 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562BBC20>
Sweep_123 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B9070>
Sweep_124 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589547A0>
Sweep_125 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C78F0>
Sweep_126 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBC0B0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E7650>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0CE6C0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E6F30>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F62DE0>
File added




df length: 1330
 dict length: 1330











concat df length: 1330
concat dict length: 1330







C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_JS_A1_C01.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.41s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.22it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.01it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.23it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589591C0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BBFAD80>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54C897F0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFC6B70>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F4A120>
File added




df length: 45
 dict length: 45




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_JS_A1_C02.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.37it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.40it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:04<00:00,  2.58it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.36it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.23it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.07it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C560A74A0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58935BB0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58937C50>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0CD040>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B107E90>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56285E50>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0CD760>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBC080>
File added




df length: 92
 dict length: 92




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_JS_A1_C03.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.81s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.83s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.25it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.38it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.76s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.89s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.76s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.92s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.76s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58951B50>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0CFA70>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C560A6660>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0CD040>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A3470>
Sweep_46 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F81A00>
Sweep_48 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5B8C0>
Sweep_50 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C05FF50>
Sweep_51 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F58500>
Sweep_53 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B69A540>
Sweep_54 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B69AF90>
Sweep_55 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B69AE10>
File added




df length: 133
 dict length: 133




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_JS_A1_C04.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.61it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.86it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.00it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.33it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.38it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.02it/s]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F44F80>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B191760>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894A540>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58948A10>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F60350>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC2A80>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B106270>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C70B0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F12C380>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A3290>
No metadata found for file: M04_JS_A1_C04
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_JS_A1_C05.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.85it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.65it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.31it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.94it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.17it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.81s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.91s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.40s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BC1C350>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54B22F30>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BDA90>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A7373B0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B106270>
Sweep_40 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F47350>
Sweep_41 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F474A0>
Sweep_42 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5ED20>
Sweep_43 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B106B40>
Sweep_44 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0EF0E0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E73E0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617C2F0>
No metadata found for file: M04_JS_A1_C05
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_JS_A1_C06.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.09it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.44s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.37s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.76s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.94s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.92s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.88s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.81s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.47s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.37s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B69AA50>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C05FF50>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589358B0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A7373B0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A734BC0>
Sweep_4 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56027650>
Sweep_5 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384E180>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56024B90>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E4F80>
Sweep_71 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FE120>
Sweep_73 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B190260>
Sweep_74 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A7344A0>
Sweep_75 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562865A0>
Sweep_76 <spikeparam.patch.fit.fit.Spike object at 0x0000014C560A45C0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5602C290>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F47A70>
File added




df length: 157
 dict length: 157




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_JS_A1_C07.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.09it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.39it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.67it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.76s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.60it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.62it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.75it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.23it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:04<00:00,  4.14it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.38it/s]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B190260>
Sweep_1 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A7373B0>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BD400>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384E180>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B106B70>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C78F0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F47350>
Sweep_2 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A0C50>
Sweep_3 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FEBD0>
Sweep_4 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58955520>
Sweep_5 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBC4D0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BBFA600>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58936930>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBC860>
No metadata found for file: M04_JS_A1_C07
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_JS_A1_C08.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.34it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.42it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.15it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.43it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  3.70it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.78s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.84it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.17it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.07it/s]

Sweep_1 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA12180>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BBFA600>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0CE2A0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BF920>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BBFA360>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0CFEF0>
Sweep_2 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F45C40>
Sweep_21 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BBF84A0>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C560A4050>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F48500>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313C3E0>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617C2F0>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5B620>
Sweep_3 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54C897F0>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894A540>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56286960>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B69BA10>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F68620>
File added




df length: 274
 dict length: 274




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_JS_A1_C09.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]

Fitting failed for sweep Sweep_1: All fits failed.

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.72s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]

Fitting failed for sweep Sweep_6: All fits failed.

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.80s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.80s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.81s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5634F770>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C78F0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58940A40>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BBFA600>
Sweep_75 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58951B50>
Sweep_77 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5602DA30>
Sweep_78 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589357F0>
Sweep_79 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313C0B0>
Sweep_80 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F467B0>
Sweep_81 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBC4D0>
Sweep_82 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617EA50>
Sweep_83 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BC1C3B0>
Sweep_84 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E7E00>
File added




df length: 287
 dict length: 287




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_JS_A1_C10.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.32s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.80s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C05FF50>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A735730>
Sweep_172 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5634C950>
Sweep_173 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5634F950>
Sweep_174 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B106B70>
Sweep_175 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589351F0>
Sweep_176 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBC8F0>
Sweep_177 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5B140>
Sweep_178 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F119E20>
Sweep_179 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F47A70>
Sweep_180 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BC1E390>
Sweep_181 <spikeparam.patch.fit.fit.Spike object at 0x0000014C560A6CF0>
Sweep_182 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5634CD70>
Sweep_183 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F61520>
Sweep_184 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5634C080>
Sweep_185 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0EF0E0>
Sweep_186 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A735B20>
Sweep_187 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BBF8650>
File added




df length: 306
 dict length: 306




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_JS_A1_C12.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  3.64it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:04<00:00,  2.64it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.99it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.79it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.76s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.90it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.83it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.32it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617E8D0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C05FF50>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A735B20>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894AA20>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC2AB0>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A735730>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA12180>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562BA240>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58957D10>
File added




df length: 406
 dict length: 406




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_JS_A1_C13.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.90it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.96it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.06it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.20it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.84it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.91it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C057920>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617C050>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBC8F0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53747D70>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58951B50>
Sweep_4 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5371B3B0>
Sweep_5 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A735A00>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A1460>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5F6B0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0CDA60>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58941700>
No metadata found for file: M04_JS_A1_C13
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_JS_A1_C14.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.46it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.73it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.99it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.85it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.22it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.03it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.99it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.37it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0CE8A0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58937C50>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5602FBF0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F474A0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F48C50>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5602F560>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617EA50>
Sweep_77 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E5760>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F49B50>
Sweep_81 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617C050>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F68D70>
File added




df length: 508
 dict length: 508




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_JS_A1_C15.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.36s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.05it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.14it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.28it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.34it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.19it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.37it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.18it/s]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0EED80>
Sweep_1 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBC8F0>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F48C50>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F631A0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C560A6630>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56286660>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A1100>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589547A0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C560A53D0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA10140>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58948A10>
File added




df length: 614
 dict length: 614




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_JS_A1_C16.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F4C0B0>
Sweep_1 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A0530>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A1460>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F4A5A0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC2AB0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FDC70>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F45D30>
Sweep_2 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589497C0>
Sweep_3 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A7357C0>
Sweep_4 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58937C50>
Sweep_41 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BBFB680>
Sweep_42 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0EFD70>
Sweep_44 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B699CD0>
Sweep_46 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B69AF90>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617D790>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BC1FD70>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5D100>
No metadata found for file: M04_JS_A1_C16
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_MJ_A1_C01.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F49B50>
No metadata found for file: M04_MJ_A1_C01
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_MW_A1_C01.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.40it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.39it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.02it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.30it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.14it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.33it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.79it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.98it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F68AA0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894E360>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F60E00>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B107E90>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C035F70>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FCA70>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BE570>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5EF60>
No metadata found for file: M04_MW_A1_C01
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_MW_A1_C02.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.76s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.57it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.85it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.88it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.29it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.85it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.33it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.48it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.42it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  3.67it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.24it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_19 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BD580>
Sweep_20 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B107E90>
Sweep_21 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B106B40>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E47A0>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F44F80>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F45D30>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A735E80>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894B800>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BD4C0>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626F770>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BDA90>
Sweep_30 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58937C50>
Sweep_31 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58959730>
Sweep_32 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F63740>
File added




df length: 732
 dict length: 732




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_MW_A1_C03.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.87it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.83it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]

Sweep_100 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58942030>
Sweep_101 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0EFD70>
Sweep_102 <spikeparam.patch.fit.fit.Spike object at 0x0000014C563A73E0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5E060>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BCA10>
Sweep_87 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BDEB0>
Sweep_89 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A737470>
Sweep_90 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FE720>
Sweep_91 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FDAC0>
Sweep_92 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C056540>
Sweep_93 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0EEAB0>
Sweep_94 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F45D00>
Sweep_95 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FF5F0>
Sweep_96 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53651AF0>
Sweep_97 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5634D4C0>
Sweep_98 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A737E60>
Sweep_99 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BE6C0>
File added




df length: 764
 dict length: 764




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_MW_A1_C06.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.72s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_41 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58937FE0>
Sweep_44 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E7830>
Sweep_45 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58959730>
Sweep_46 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B106B40>
Sweep_47 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589547A0>
Sweep_48 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58949820>
Sweep_49 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B191760>
Sweep_50 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B193920>
Sweep_51 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56287290>
Sweep_65 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BDEB0>
Sweep_66 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA12630>
File added




df length: 775
 dict length: 775




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_MW_A1_C07.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A734BC0>
File added




df length: 776
 dict length: 776




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_MW_A1_C08.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.66it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.21it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.34it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.06it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.20it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.82s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.48s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.38s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0D9370>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53651AF0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F60B30>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B6997C0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C051820>
Sweep_57 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F62D20>
Sweep_62 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56026F00>
Sweep_63 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C056450>
Sweep_64 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BBF9700>
Sweep_65 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F4F710>
Sweep_66 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F48B60>
Sweep_67 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0D9EE0>
Sweep_68 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0D9910>
Sweep_69 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B699220>
Sweep_70 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58948680>
Sweep_71 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0367E0>
Sweep_72 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A0AA0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626EC90>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F6B140>
File added




df length: 848
 dict length: 848




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_MW_A1_C09.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.26it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.64it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.84it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.29it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.28it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.35it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.95it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58942660>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C053860>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFC6930>
Sweep_123 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0CD460>
Sweep_125 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B191760>
Sweep_126 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F481A0>
Sweep_129 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0EEC00>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F637A0>
Sweep_131 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C052780>
Sweep_134 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617E2D0>
Sweep_138 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B69B380>
Sweep_139 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58940BF0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5634C230>
Sweep_140 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A734BC0>
Sweep_141 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58937FE0>
Sweep_142 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5634D8B0>
Sweep_143 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F61520>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B522FF0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C563A4170>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626E150>
File added




df length: 929
 dict length: 929




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_MW_A1_C10.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.76s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_149 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4E7FE0>
Sweep_150 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4E58E0>
Sweep_151 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58937FE0>
Sweep_152 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A27B0>
Sweep_153 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E6090>
Sweep_154 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C037650>
Sweep_155 <spikeparam.patch.fit.fit.Spike object at 0x0000014C563A4DA0>
Sweep_156 <spikeparam.patch.fit.fit.Spike object at 0x0000014C563A7F80>
Sweep_157 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BBFA840>
Sweep_158 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0512E0>
Sweep_159 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589412B0>
Sweep_160 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C036000>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A735580>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F4E510>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4E7E90>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56287FE0>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F1820>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F1BE0>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5B5F0>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4CA3C0>
Sweep_30 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C036AB0>
File added




df length: 950
 dict length: 950




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_SM_A1_C01.nwb

Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.17it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 29/29 [00:04<00:00,  6.24it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  3.71it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:04<00:00,  4.20it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  3.76it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:04<00:00,  4.59it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.13it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 32/32 [00:04<00:00,  6.95it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 36/36 [00:04<00:00,  7.66it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 39/39 [00:04<00:00,  8.45it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 33/33 [00:04<00:00,  7.00it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 30/30 [00:04<00:00,  6.55it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.39it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:04<00:00,  5.39it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.48it/s]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0343E0>
Sweep_1 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5D1C0>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5E240>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617FA10>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFC5040>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F6BBC0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E6090>
Sweep_2 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58937FE0>
Sweep_3 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56024710>
Sweep_4 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F199580>
Sweep_5 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1910A0>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA11AC0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BBF93A0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F695B0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F44F50>
No metadata found for file: M04_SM_A1_C01
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_SM_A1_C02.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.99s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B699A30>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFC6930>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFC5040>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA12390>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0CE8A0>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA11AC0>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C056A20>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0D9D90>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F6B770>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5634E6C0>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B69AE10>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F6A180>
Sweep_30 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B69B320>
Sweep_32 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617EA50>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A2C90>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A27B0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B522F90>
No metadata found for file: M04_SM_A1_C02
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_SM_A1_C03.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.33it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.98it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.40it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F695B0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A2C90>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BDBB0>
No metadata found for file: M04_SM_A1_C03
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_SM_A1_C04.nwb

Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.24it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:04<00:00,  4.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.51it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.40it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.11it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  3.73it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 22/22 [00:04<00:00,  4.69it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.53it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:04<00:00,  4.11it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:04<00:00,  4.95it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:04<00:00,  4.13it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:04<00:00,  4.20it/s]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A27B0>
Sweep_1 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58948860>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58948680>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58940FE0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F81430>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A736B10>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A1400>
Sweep_2 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5634F980>
Sweep_3 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0DAA50>
Sweep_4 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5634E630>
Sweep_5 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4E7170>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0D8B30>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58942480>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0328A0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5634E6C0>
No metadata found for file: M04_SM_A1_C04
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_SM_A1_C06.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.05it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.37it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.38it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.33s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.35it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.41it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.04it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.25it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.04it/s]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5634F980>
Sweep_1 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C054380>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0EEAB0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562847A0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F62810>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C053200>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BC1CE60>
Sweep_2 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F49B50>
Sweep_3 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0CD460>
Sweep_4 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BE0F0>
Sweep_5 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C057CE0>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5602D8E0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0EEC00>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BF740>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58943D70>
No metadata found for file: M04_SM_A1_C06
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_SM_A1_C07.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F3DA0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F3590>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F2AB0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F0470>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C2E91DA30>
Sweep_85 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4CA810>
Sweep_86 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53073410>
Sweep_88 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4CAB70>
Sweep_89 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F1490>
File added




df length: 959
 dict length: 959




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_SM_A1_C08.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  3.63it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 30/30 [00:04<00:00,  6.30it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 37/37 [00:04<00:00,  7.69it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 36/36 [00:04<00:00,  7.85it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 37/37 [00:04<00:00,  7.87it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]

Fitting failed for sweep Sweep_25: Length of values (2) does not match length of index (1)

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.33s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]

Fitting failed for sweep Sweep_32: Length of values (2) does not match length of index (1)

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.37it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.06it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.64it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.79it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.29it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.20it/s]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C032270>
Sweep_1 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0336E0>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F16A0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FC170>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FE060>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F1181D0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F119E20>
Sweep_15 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C052C30>
Sweep_16 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C7F50>
Sweep_17 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C052480>
Sweep_18 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FE4E0>
Sweep_19 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C052630>
Sweep_2 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FCE30>
Sweep_20 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C7A10>
Sweep_21 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C030A40>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F3830>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C050350>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F3740>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C032390>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F0D10>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FE750>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4CA5A0>
Sweep_3 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C031040>
Sweep_30 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F1E50>
Sweep_31 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4CA540>
Sweep_33 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0322D0>
Sweep_34 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FF200>
Sweep_4 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4C8290>
Sweep_5 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C052B40>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4CAF90>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E59A0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FDC10>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C050F50>
No metadata found for file: M04_SM_A1_C08
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_SM_A1_C09.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F35C0>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F119E20>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F1181D0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F1DC0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C78C0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F2960>
Sweep_44 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C032E70>
Sweep_45 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FF110>
Sweep_46 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F39B0>
Sweep_47 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FD700>
Sweep_48 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F2C90>
Sweep_49 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C033CB0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4C8740>
File added




df length: 972
 dict length: 972




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_SM_A1_C10.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B105A30>
Sweep_1 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1047A0>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1070E0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5578F260>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B105B80>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5578F920>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5578EC90>
Sweep_2 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0333B0>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBD760>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B106840>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C031310>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBDA90>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C030B90>
Sweep_3 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBE4E0>
Sweep_30 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C031DC0>
Sweep_31 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBD820>
Sweep_32 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C033B30>
Sweep_33 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBDA60>
Sweep_34 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1061E0>
Sweep_35 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C030E90>
Sweep_36 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B192600>
Sweep_37 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C030AD0>
Sweep_38 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E7B00>
Sweep_39 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C031A90>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B106AE0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BCE60>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBC200>
File added




df length: 999
 dict length: 999




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_SM_A1_C11.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.29it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.30it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.29it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.38it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.43it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.53it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  3.68it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.94it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.08it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.38it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  3.69it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.62it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.43it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.41it/s]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B192CC0>
Sweep_1 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F3D70>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F16A0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F0BC0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F37A0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53746F30>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E43B0>
Sweep_18 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0325A0>
Sweep_19 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FDA90>
Sweep_2 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C032ED0>
Sweep_20 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5519D6A0>
Sweep_21 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53171BE0>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F1EB0>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F118380>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F3D40>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C550FF4A0>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C550FF290>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F00B0>
Sweep_3 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FDCD0>
Sweep_30 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F2870>
Sweep_31 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FCAD0>
Sweep_32 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4CA630>
Sweep_33 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F1DC0>
Sweep_34 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FE990>
Sweep_4 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4CA6F0>
Sweep_5 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FD760>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53747C50>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FE5D0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B105C10>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FEE70>
No metadata found for file: M04_SM_A1_C11
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M04\M04_SM_A1_C13.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384F530>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C2EB6E690>
Sweep_200 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617F530>
Sweep_205 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5461F6E0>
Sweep_206 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384E540>
File added




df length: 1004
 dict length: 1004











concat df length: 2334
concat dict length: 2334







C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M05\M05_JS_A1_C01.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.08it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.78s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.34s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.72s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C51A721B0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384E540>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A0CCB0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A0C530>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EFC350>
Sweep_15 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58937E90>
Sweep_16 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A5E840>
Sweep_17 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384E240>
Sweep_18 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4C8650>
Sweep_19 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BC680>
Sweep_2 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380D3D0>
Sweep_20 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FD430>
Sweep_21 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4C9100>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C550FF860>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FD700>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5F7D0>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4CB8C0>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5CB60>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4C9E80>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5CAA0>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FC680>
Sweep_3 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5DC40>
Sweep_4 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FE2A0>
Sweep_5 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58956BD0>
Sweep_53 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5519DF40>
Sweep_55 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EF5700>
Sweep_56 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557470E0>
Sweep_57 <spikeparam.patch.fit.fit.Spike object at 0x0000014C585AFCB0>
Sweep_58 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58946750>
Sweep_59 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F9B2C0>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58946F60>
Sweep_60 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53744830>
Sweep_61 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380F830>
Sweep_62 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EF5E80>
Sweep_63 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EF5F70>
Sweep_64 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53745790>
Sweep_65 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B9490>
Sweep_66 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53747EF0>
Sweep_67 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533CF920>
Sweep_68 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384C0E0>
Sweep_69 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B107680>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F24E0>
Sweep_70 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B191400>
Sweep_71 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F3CB0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380F650>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58947DD0>
No metadata found for file: M05_JS_A1_C01
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M05\M05_JS_A1_C02.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.62it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.58it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.47it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.27it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.40s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.78s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5C5F0>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5E510>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E40E0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384F020>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384FE90>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C543BEED0>
Sweep_18 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B106F00>
Sweep_19 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EEEEA0>
Sweep_20 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5D400>
Sweep_21 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B107470>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4CA210>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C033770>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BE660>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C032630>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B106840>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C051880>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F45130>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F0380>
Sweep_3 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C050C50>
Sweep_4 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C053530>
Sweep_5 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C050F20>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C050DA0>
Sweep_66 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C030D10>
Sweep_67 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C050DD0>
Sweep_68 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C032C30>
Sweep_69 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C052000>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C033A70>
Sweep_70 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F44050>
Sweep_71 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4CB3E0>
Sweep_72 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E7AD0>
Sweep_73 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F44650>
Sweep_74 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5CA40>
Sweep_75 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E51F0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FCCB0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E5D60>
File added




df length: 79
 dict length: 79




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M05\M05_JS_A1_C03.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.37it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.82it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.28it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.16it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.58it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.09it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.88it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.33it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.86it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.40it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.47it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.27it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.90it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.47it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F0590>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557469F0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F53470>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C550FF4A0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C556F6690>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EDCB90>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B8B90>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A5E840>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54C82060>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384C320>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C51A721B0>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55A19220>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EEEEA0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53171C10>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617C6B0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F5EF830>
File added




df length: 265
 dict length: 265




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M05\M05_JS_A1_C04.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBE420>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55931F70>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55A1B350>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C537F1E50>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54C82090>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559329F0>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA23770>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533BFE00>
Sweep_56 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533BD3A0>
Sweep_57 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559C2BA0>
Sweep_58 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617E540>
Sweep_59 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384EBA0>
Sweep_60 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55A19070>
No metadata found for file: M05_JS_A1_C04
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M05\M05_JS_A1_C05.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.78s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.44s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.84it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.01it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.80it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.37it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.41s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.34it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.35it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.09it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.99it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.24it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.21it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.91it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.81it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.96it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.90it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C84D0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54C82090>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA223C0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55A1B350>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559329F0>
Sweep_17 <spikeparam.patch.fit.fit.Spike object at 0x0000014C537F1E50>
Sweep_18 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559C2630>
Sweep_19 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617D2B0>
Sweep_20 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F834A0>
Sweep_21 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533A17F0>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C537F37D0>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5519E390>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533A11F0>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5578F5F0>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55931F70>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533A03B0>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F2960>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A0D160>
Sweep_4 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589619A0>
Sweep_5 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617CA70>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B36D370>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399CDA0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA232C0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589474A0>
File added




df length: 406
 dict length: 406




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M05\M05_JS_A1_C06.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.85it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.47it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.81it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.13it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.96it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.38it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55931F70>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F53470>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55A1B350>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55ABFD40>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EEEEA0>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559329F0>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559EE2D0>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F40500>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C2DFC2390>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54B237A0>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5578DBB0>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53171BE0>
Sweep_75 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A0C530>
Sweep_76 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58960B60>
Sweep_77 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C84D0>
Sweep_78 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58962E10>
Sweep_79 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313C3E0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617D280>
Sweep_80 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54C82090>
Sweep_81 <spikeparam.patch.fit.fit.Spike object at 0x0000014C556F6690>
Sweep_82 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19C830>
Sweep_83 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380C800>
Sweep_84 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA232C0>
Sweep_85 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380D610>
Sweep_86 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBD3A0>
Sweep_87 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58962510>
Sweep_88 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384D2B0>
Sweep_89 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589628D0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F40860>
Sweep_90 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EDC0B0>
File added




df length: 488
 dict length: 488




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M05\M05_JS_A1_C07.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.76s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19D250>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EFDD00>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F2660>
Sweep_126 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0311F0>
Sweep_128 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589474A0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0325A0>
Sweep_130 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559C2900>
Sweep_131 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617F6E0>
Sweep_132 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA232C0>
Sweep_133 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F45C40>
Sweep_134 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55A19220>
Sweep_135 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1076B0>
Sweep_136 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA21310>
Sweep_137 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562BA8D0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58947440>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399C3E0>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C032150>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C030680>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399EF00>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FEE70>
File added




df length: 508
 dict length: 508




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M05\M05_JS_A1_C08.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.03it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.33it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.37it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.35it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534D4B60>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A5E840>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58965B50>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C8560>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58946BD0>
Sweep_16 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53781490>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380E750>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EEEEA0>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA21F70>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54B237A0>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B36D580>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BC170>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399FE90>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC0F80>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399C110>
File added




df length: 537
 dict length: 537




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M05\M05_JS_A1_C09.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.72s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.26s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F42510>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380DEE0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380D430>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58961580>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5519E270>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894E360>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384E180>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55BF76B0>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19E4B0>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617D2B0>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380D220>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533BFE00>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EF6030>
Sweep_60 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58961E20>
Sweep_61 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA207D0>
Sweep_62 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559EE2D0>
Sweep_63 <spikeparam.patch.fit.fit.Spike object at 0x0000014C537466C0>
Sweep_64 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54B23080>
Sweep_65 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54B23620>
Sweep_66 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA215E0>
Sweep_67 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F43890>
Sweep_68 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA229F0>
Sweep_69 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C033320>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F0950>
Sweep_70 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617CEF0>
Sweep_71 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19E6C0>
Sweep_72 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F43A10>
Sweep_73 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19C980>
Sweep_74 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F40BC0>
Sweep_75 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F40230>
Sweep_76 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399FE90>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBD760>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5E180>
File added




df length: 570
 dict length: 570




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M05\M05_JS_A1_C10.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F45FA0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399FE90>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B36DC40>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F481A0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F49A90>
Sweep_21 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BE270>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58962540>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B9760>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58961580>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA21310>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C542DA600>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55A4D850>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58962E10>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54B220F0>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58963FB0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589568D0>
Sweep_78 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A5F9B0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313C0B0>
Sweep_80 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617CA70>
Sweep_81 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC2EA0>
Sweep_82 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BC6E0>
Sweep_83 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBCF80>
Sweep_84 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BC3B0>
Sweep_85 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBD3D0>
Sweep_86 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BC680>
Sweep_87 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58962000>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA22C60>
File added




df length: 597
 dict length: 597




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M05\M05_JS_A1_C11.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.65it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.37it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.33it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.37s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.10it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.43it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.00it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.45it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.20it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:04<00:00,  2.73it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.21it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.20it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.86it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.50it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.03it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.95it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.93it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4A8D0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54B220F0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894D400>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EEEEA0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F53470>
Sweep_21 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5578EF60>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C537812E0>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384C140>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C542DA600>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C542D86B0>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A0F530>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F40AD0>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58910E30>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589601D0>
Sweep_5 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380EC60>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C539DA660>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559C2D80>
Sweep_79 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559C2870>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F43110>
Sweep_81 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BE0C0>
Sweep_82 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B36D580>
Sweep_83 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B9190>
Sweep_84 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58959C10>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B104CE0>
File added




df length: 763
 dict length: 763




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M05\M05_JS_A1_C13.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.61it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.85it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:04<00:00,  2.72it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.90it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.15it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.39s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.33s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.63it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.38it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.05it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.16it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.05it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.67it/s]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F42720>
Sweep_1 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55A19220>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55A1B350>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53171BE0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54B220F0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55A4D850>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58960050>
Sweep_17 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533A11F0>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533A12E0>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54B8EF60>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F43890>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B9190>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58961520>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F0E900>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58946BD0>
Sweep_5 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C84D0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589601A0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58910D10>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399DFD0>
File added




df length: 897
 dict length: 897




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M05\M05_JS_A1_C15.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.40it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.20it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.81it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.05it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.09it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.21it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.67it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.72s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.71it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.26it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.91it/s]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C537186E0>
Sweep_1 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58946BD0>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B36F230>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54B220F0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54B23080>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F9AA80>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53781490>
Sweep_2 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA229F0>
Sweep_3 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F0B60>
Sweep_30 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58944260>
Sweep_31 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58910EC0>
Sweep_32 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5578F920>
Sweep_4 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5519CB90>
Sweep_5 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380D430>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5608E210>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58960260>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F0800>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58955760>
No metadata found for file: M05_JS_A1_C15
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M05\M05_JS_A1_C16.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.40it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.07it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.27it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.31s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.33s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.59it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.03it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.18it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.28it/s]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58960260>
Sweep_1 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F0F50>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C537812E0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B8B90>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C553688F0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA207D0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A5F9B0>
Sweep_2 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55A19220>
Sweep_34 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559EE2D0>
Sweep_35 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F44290>
Sweep_36 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380DC40>
Sweep_37 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533A11F0>
Sweep_39 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380EAB0>
Sweep_40 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53781490>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EF5700>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BCE00>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58910D10>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F0E870>
File added




df length: 988
 dict length: 988




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M05\M05_MJ_A1_C01.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.72s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.34it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.32it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.24it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F0E990>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58966330>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C8560>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C556F6690>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53171BE0>
No metadata found for file: M05_MJ_A1_C01
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M05\M05_MJ_A1_C02.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.06it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.90it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.26it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.59it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.42it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.91it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.34it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.59it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.43it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.33s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.36it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.02it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.04it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.37it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.36it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313E540>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5608E630>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562BB6E0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F53470>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBE2D0>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313C0B0>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F40860>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53718200>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58910E00>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58961220>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589601D0>
Sweep_41 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F45100>
Sweep_42 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533A17F0>
Sweep_43 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A5E840>
Sweep_44 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58910E30>
Sweep_56 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399C8F0>
Sweep_57 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F0FAA0>
Sweep_58 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F44A40>
Sweep_59 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58959AC0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54B8E330>
No metadata found for file: M05_MJ_A1_C02
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M05\M05_MJ_A1_C04.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.41s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.65it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.49it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.84it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.05it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.91it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.02it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.39s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BCEF0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C556F6690>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399F200>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C031310>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F44860>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F1B50>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B36CCE0>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894D400>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BD460>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58944260>
Sweep_41 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53781490>
Sweep_42 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58947800>
Sweep_43 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54B23620>
Sweep_44 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F41160>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380DB20>
File added




df length: 1042
 dict length: 1042




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M05\M05_MW_A1_C04.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.14it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.46it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.30it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.43it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.38it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.68it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.05it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.40it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.43it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.33it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.96it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B107AA0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533A17F0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F3830>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BCEF0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54B8E330>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E5F70>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533A33E0>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894ED20>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54B237A0>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C8560>
Sweep_50 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBE510>
Sweep_51 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58961E20>
Sweep_54 <spikeparam.patch.fit.fit.Spike object at 0x0000014C551B7EC0>
Sweep_55 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EDE930>
Sweep_56 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562BBA40>
Sweep_57 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5371ABD0>
Sweep_58 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53718200>
Sweep_59 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B8E00>
Sweep_60 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E7200>
Sweep_61 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F989E0>
Sweep_62 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B107B00>
Sweep_63 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBD790>
Sweep_64 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399FFB0>
Sweep_65 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F42AB0>
Sweep_66 <spikeparam.patch.fit.fit.Spike object at 0x0000014C542D86B0>
Sweep_67 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC09E0>
Sweep_68 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399FE90>
Sweep_69 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5608E0F0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C032E70>
No metadata found for file: M05_MW_A1_C04
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M05\M05_MW_A1_C05.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.03it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:04<00:00,  3.91it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.99it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.38it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.28it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.35it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:04<00:00,  4.00it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 22/22 [00:04<00:00,  4.77it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  3.72it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 40/40 [00:04<00:00,  8.68it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.34it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.05it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 38/38 [00:04<00:00,  8.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.23it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.42s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.26it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.04it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.38it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.25it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.04it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.91it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.99it/s]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54B220F0>
Sweep_1 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B36CCE0>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559C2D80>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559C2630>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B9A90>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B9190>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54B8F860>
Sweep_18 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F478C0>
Sweep_2 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA229F0>
Sweep_20 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F9AA80>
Sweep_21 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA21190>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58956C60>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA21880>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559C2BA0>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19FC80>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53719010>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58960050>
Sweep_3 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53719B50>
Sweep_4 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19CC50>
Sweep_5 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F42510>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58948E90>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C050260>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58937F50>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C052B40>
No metadata found for file: M05_MW_A1_C05
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M05\M05_SM_A1_C01.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.98it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.25it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.11it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.35it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.39s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.35it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.06it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C551B7EC0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5578EF60>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58961A00>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F53470>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C8560>
Sweep_15 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5578DBB0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55368860>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58911220>
File added




df length: 1083
 dict length: 1083




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M05\M05_SM_A1_C02.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.19it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.63it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.29it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.37it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.05it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.83it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.03it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.74it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F53470>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533A33E0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C551B7EC0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B9A90>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C6DE0>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55368800>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617F6E0>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F99850>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55368860>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55BF76B0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5D9D0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399DFD0>
File added




df length: 1151
 dict length: 1151




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M05\M05_SM_A1_C03.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.12it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.21it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.45it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.21it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.20it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.46it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.30it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.33it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577CA10>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313E540>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EF5700>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58966330>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53171BE0>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577C2C0>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58944260>
Sweep_52 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B9A90>
Sweep_53 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534BAFC0>
Sweep_54 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F44860>
Sweep_55 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533BFE00>
Sweep_56 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533A2A50>
Sweep_57 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384D5E0>
Sweep_58 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F44110>
Sweep_59 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384EF00>
Sweep_60 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5371ABD0>
Sweep_69 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC1B50>
Sweep_70 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B36CCE0>
Sweep_71 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19F7D0>
Sweep_72 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384F4A0>
No metadata found for file: M05_SM_A1_C03
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M05\M05_SM_A1_C06.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.26it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.34it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.29s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.64it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.86it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.25it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.04it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.01it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.99it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.05it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F45AF0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5519CB90>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F45010>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58966330>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399EF00>
Sweep_19 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313C0B0>
Sweep_21 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54B23620>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EF5700>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58962C30>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F5EF830>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5578EF60>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BD310>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313C680>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53171BE0>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313C6B0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA21F40>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589442C0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F38C0>
File added




df length: 1229
 dict length: 1229




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M05\M05_SM_A1_C07.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58966330>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534D5E50>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5519E270>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53745E20>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53781490>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53171BE0>
No metadata found for file: M05_SM_A1_C07
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M05\M05_SM_A1_C13.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399DDC0>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399F200>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559C2D80>
File added




df length: 1232
 dict length: 1232











concat df length: 3566
concat dict length: 3566







C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M06\M06_MW_A1_C04.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.88it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.93it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.06it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.38it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.06it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.06it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.99it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.97it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.30it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.72s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.91it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.20it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.76s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58935EB0>
Sweep_1 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58934F50>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BE7E0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4A270>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5608DFD0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BDD30>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C6DE0>
Sweep_15 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58944260>
Sweep_16 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58946BD0>
Sweep_17 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399FD40>
Sweep_2 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C053860>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A5E840>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA21190>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA207D0>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384C320>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53718C20>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BC680>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5D8B0>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4A180>
Sweep_3 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F33B0>
Sweep_4 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589540B0>
Sweep_48 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F49B50>
Sweep_49 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F1B50>
Sweep_50 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F3200>
Sweep_58 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5C6B0>
Sweep_60 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FCE90>
Sweep_66 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F3740>
Sweep_67 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FD520>
Sweep_68 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5DD60>
Sweep_69 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E64E0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5F9B0>
Sweep_70 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5F020>
Sweep_71 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4B050>
Sweep_72 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5608E630>
Sweep_73 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C030470>
Sweep_74 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E7380>
Sweep_75 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534BA0F0>
Sweep_76 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589591C0>
Sweep_77 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4A960>
Sweep_78 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5895A6C0>
Sweep_79 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4AE70>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F3D70>
Sweep_80 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C053710>
Sweep_81 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4C9550>
Sweep_82 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C053740>
Sweep_83 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4C97F0>
Sweep_84 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C052BA0>
Sweep_85 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5D100>
Sweep_86 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380DA00>
Sweep_87 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56305970>
Sweep_88 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0511F0>
Sweep_89 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4CAFF0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5895AB40>
Sweep_90 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559C1910>
Sweep_91 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F42510>
Sweep_92 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58959FD0>
Sweep_93 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F48050>
Sweep_94 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4C8650>
Sweep_95 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19D610>
Sweep_96 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19F020>
Sweep_97 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589601D0>
Sweep_98 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F46870>
Sweep_99 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B9F10>
File added




df length: 140
 dict length: 140




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M06\M06_SM_A1_C01.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.78s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.72s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B105700>
Sweep_1 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559C1910>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B9190>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC0E90>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533A0890>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A5F9B0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5608E660>
Sweep_2 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4B050>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53718CB0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4A960>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562BBD10>
File added




df length: 151
 dict length: 151




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M06\M06_SM_A1_C07.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]

Fitting failed for sweep Sweep_16: All fits failed.

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380D610>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA22060>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C2E91DA30>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54B8F860>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C84D0>
Sweep_21 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894D130>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380EC60>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F9AA80>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5578DBB0>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EF5700>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B9760>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4AED0>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589347D0>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58962540>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5608E5D0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5DA30>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F34D0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894ED20>
File added




df length: 171
 dict length: 171




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M06\M06_SM_A1_C08.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_39 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B106030>
Sweep_40 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55A4D850>
Sweep_41 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58946BD0>
Sweep_42 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533A2A50>
Sweep_43 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5371ABD0>
Sweep_44 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5608E660>
Sweep_45 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C6DE0>
File added




df length: 178
 dict length: 178




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M06\M06_SM_A1_C12.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.35it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.93it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.33s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.01it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EDE930>
Sweep_1 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533A2A50>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533A33E0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55368860>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F498E0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B104380>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F9AA80>
Sweep_2 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1072C0>
Sweep_3 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4CBD70>
Sweep_4 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577D850>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384D610>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589601D0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589474A0>
File added




df length: 209
 dict length: 209











concat df length: 3775
concat dict length: 3775







C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M08\M08_JS_A1_C01.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.92it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.40it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.38it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.37it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.05it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.40it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  3.70it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617F6E0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54B237A0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B105AC0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F9B2C0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B93A0>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A5E840>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589585F0>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EF5700>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589442C0>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589474A0>
Sweep_84 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894B320>
Sweep_85 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA21880>
Sweep_86 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F44560>
Sweep_87 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533A39E0>
File added




df length: 118
 dict length: 118




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M08\M08_JS_A1_C02.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.29it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.37it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 44/44 [00:04<00:00,  9.50it/s]

Fitting failed for sweep Sweep_12: Length of values (45) does not match length of index (44)

Spike: 100%|███████████████████████████████████████████████████████████████████████████| 57/57 [00:04<00:00, 12.13it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 34/34 [00:04<00:00,  7.13it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.32s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.31it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.99it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.21it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.39it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54B237A0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559EE2D0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B93A0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F41040>
Sweep_4 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F44560>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F41BB0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C550FED20>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C2E91DA30>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C537185C0>
File added




df length: 287
 dict length: 287




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M08\M08_JS_A1_C03.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.21it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.21it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.36it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.42it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.39it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.05it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.20it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 41/41 [00:04<00:00,  8.84it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.55it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.03it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55A4D850>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559C2BA0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F49F40>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F49730>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384D610>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBD4F0>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EC3980>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F19BD10>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F12D400>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399DFD0>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577D6D0>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F49E80>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380EA20>
File added




df length: 461
 dict length: 461




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M08\M08_JS_A1_C04.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.40s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.48it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.20it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.05it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.13it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.81it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_16 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53782030>
Sweep_17 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A5E840>
Sweep_18 <spikeparam.patch.fit.fit.Spike object at 0x0000014C553688F0>
Sweep_21 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53718D70>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F0E990>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C030380>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F9AA80>
Sweep_30 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384D610>
Sweep_31 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EF67B0>
Sweep_32 <spikeparam.patch.fit.fit.Spike object at 0x0000014C2E91DA30>
Sweep_33 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617F6E0>
File added




df length: 523
 dict length: 523




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M08\M08_JS_A1_C06.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.06it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.84it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.11it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.33s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.81s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.46it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.02it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.61it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.87it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.92it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.09it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.37s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4C9700>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FEFC0>
Sweep_110 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589644A0>
Sweep_111 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC31A0>
Sweep_112 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F99850>
Sweep_113 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA21190>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B104140>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1043B0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F12FE60>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559C2870>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58961040>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B9190>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C030770>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F49760>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FE630>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F46360>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FE4E0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F49C70>
File added




df length: 614
 dict length: 614




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M08\M08_JS_A1_C07.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.36it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]

Fitting failed for sweep Sweep_18: All fits failed.

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.29s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58957440>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A5F9B0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589594F0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559EE2D0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589601D0>
Sweep_2 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534BBCE0>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534BA0F0>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589644A0>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA21190>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617C140>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C553688F0>
Sweep_4 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894ED20>
File added




df length: 630
 dict length: 630




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M08\M08_JS_A1_C08.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.33s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.44s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5578DBB0>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53745E20>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589594F0>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC03E0>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F440E0>
File added




df length: 637
 dict length: 637




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M08\M08_JS_A1_C09.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.30it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.03it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.42it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.13it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.39it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.31s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.76s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.78s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.38it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.00it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.35it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53171AC0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C553688F0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C550FED20>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C031730>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58956300>
Sweep_4 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A0D880>
Sweep_49 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B105460>
Sweep_5 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5895BE90>
Sweep_51 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559EE2D0>
Sweep_52 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B106930>
Sweep_53 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4A630>
Sweep_54 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C030BF0>
Sweep_55 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C031280>
Sweep_56 <spikeparam.patch.fit.fit.Spike object at 0x0000014C563073B0>
Sweep_57 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4A090>
Sweep_58 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4B980>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBC680>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4C8260>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58958E60>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617F6E0>
File added




df length: 766
 dict length: 766




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M08\M08_JS_A1_C10.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.72it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_101 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58934E00>
Sweep_102 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EC2C60>
Sweep_103 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4BB60>
Sweep_82 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54B220F0>
Sweep_83 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894B770>
Sweep_84 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58948920>
Sweep_85 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F40860>
Sweep_86 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C84D0>
Sweep_87 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B9190>
Sweep_88 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58961A00>
File added




df length: 780
 dict length: 780




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M08\M08_JS_A1_C12.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.32it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.61it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.02it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.48s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.37it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F12FE00>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C553688F0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBFF20>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B9190>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380EA20>
Sweep_20 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58936390>
Sweep_21 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5371B050>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F1B50>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19F650>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19DA00>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B107920>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53718260>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5D100>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54B237A0>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53745E20>
Sweep_3 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384F4A0>
Sweep_38 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FDA60>
Sweep_39 <spikeparam.patch.fit.fit.Spike object at 0x0000014C551B7EC0>
Sweep_40 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533CCAA0>
Sweep_41 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894DD30>
Sweep_42 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4CBBC0>
Sweep_5 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C033DA0>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B106930>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BC410>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B190BC0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BC9E0>
File added




df length: 822
 dict length: 822




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M08\M08_JS_A1_C14.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.47it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.36it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.42it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.42it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.46it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.50it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.11it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.28it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.39it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.35it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.37it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:04<00:00,  3.91it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.38it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.27it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.43it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.11it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.75it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.51it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.46it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.53it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.45it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577D310>
Sweep_100 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533CCAA0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F46270>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F46FF0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC03E0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B9190>
Sweep_15 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BDCD0>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58957230>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F3200>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399DFD0>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53718D70>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F12CA10>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBE060>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A5F9B0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F12FE00>
Sweep_83 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56286660>
Sweep_84 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F0590>
Sweep_85 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F0B60>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4CBB90>
Sweep_94 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562BAB10>
Sweep_95 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577D4F0>
Sweep_96 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BD8B0>
Sweep_97 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562BA600>
Sweep_98 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53719010>
Sweep_99 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4CA180>
File added




df length: 1137
 dict length: 1137




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M08\M08_JS_A1_C15.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.40s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533CCAA0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F99850>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC03E0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617C140>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC09B0>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C551B7EC0>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5F410>
File added




df length: 1147
 dict length: 1147




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M08\M08_JS_A1_C16.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.04it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.50it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.01it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.44it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  3.65it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.76s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EF5700>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894DD30>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384F4A0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894A7E0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F12D400>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F41E20>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BC200>
Sweep_30 <spikeparam.patch.fit.fit.Spike object at 0x0000014C537D22D0>
Sweep_31 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56304DD0>
Sweep_32 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54B8EF60>
File added




df length: 1216
 dict length: 1216




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M08\M08_MW_A1_C01.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.36s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 35/35 [00:04<00:00,  7.60it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380EA20>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894A7E0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58948A70>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0317F0>
Sweep_2 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4ACC0>
File added




df length: 1256
 dict length: 1256




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M08\M08_MW_A1_C02.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  3.65it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.84it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.67it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.04it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.35it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.33s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.39it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.04it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.46it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.48it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.63it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.35it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.58it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.24it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F46E40>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58948A70>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5895BE90>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58958830>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F43470>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5F860>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384FF80>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58962540>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FF770>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4BFE0>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C030680>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0333E0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577D490>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4C8260>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BD5B0>
File added




df length: 1420
 dict length: 1420




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M08\M08_MW_A1_C03.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.44it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.88it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.31it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.16it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.30it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.07it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.98it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.52it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.35it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.24it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.36it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.25it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FF140>
Sweep_100 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53718D70>
Sweep_101 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F3200>
Sweep_102 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EDE930>
Sweep_103 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C84D0>
Sweep_104 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384E180>
Sweep_105 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559C2870>
Sweep_106 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399DFD0>
Sweep_107 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894B320>
Sweep_108 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577E480>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F3AA0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53171AC0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58961220>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4BB60>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894B8F0>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F0380>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19EB40>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19F650>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F12CF20>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5D160>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589344D0>
Sweep_78 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C031A30>
Sweep_79 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399FD40>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B106570>
Sweep_80 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894B770>
Sweep_81 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4A090>
Sweep_82 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B9430>
Sweep_83 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577CA40>
Sweep_84 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562BA600>
Sweep_85 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0310A0>
Sweep_86 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4AA80>
Sweep_87 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19F6E0>
Sweep_88 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56305610>
Sweep_89 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5F110>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F2300>
Sweep_90 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F36E0>
Sweep_91 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B69B590>
Sweep_92 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F49C40>
Sweep_93 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C030770>
Sweep_94 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C052A20>
Sweep_95 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B69A390>
Sweep_96 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894BD40>
Sweep_97 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E5190>
Sweep_98 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5F6B0>
Sweep_99 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B8590>
File added




df length: 1636
 dict length: 1636




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M08\M08_MW_A1_C05.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56286DE0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19F6E0>
File added




df length: 1638
 dict length: 1638




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M08\M08_MW_A1_C06.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.76s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.39it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.46it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.85it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.82it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.44s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.37it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.83it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.91it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.08it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.28s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.94it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.48s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5DE20>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894BD40>
Sweep_100 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53745E20>
Sweep_101 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4B680>
Sweep_102 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399C3E0>
Sweep_103 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC05F0>
Sweep_104 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F49AC0>
Sweep_105 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4B4A0>
Sweep_106 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56306930>
Sweep_107 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5D100>
Sweep_108 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C033B60>
Sweep_109 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0333E0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56304110>
Sweep_110 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56306A80>
Sweep_111 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBDAF0>
Sweep_112 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FE4E0>
Sweep_113 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4CB6B0>
Sweep_114 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626EBD0>
Sweep_115 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5F500>
Sweep_116 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBC4D0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58957980>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626FF20>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5F7A0>
Sweep_30 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5E300>
Sweep_31 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4A630>
Sweep_32 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBDD30>
Sweep_33 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C050C80>
Sweep_34 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBE330>
Sweep_35 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBE4E0>
Sweep_36 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56306570>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626F8C0>
Sweep_72 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E4110>
Sweep_73 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B105460>
Sweep_74 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E5790>
Sweep_75 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E6780>
Sweep_76 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FF860>
Sweep_77 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58955040>
Sweep_78 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562BB7D0>
Sweep_79 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B107680>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBEC00>
Sweep_80 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58957440>
Sweep_81 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BD880>
Sweep_82 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5F410>
Sweep_83 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58935700>
Sweep_84 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56304DD0>
Sweep_85 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58956660>
Sweep_86 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0528D0>
Sweep_87 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B191E20>
Sweep_88 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B9370>
Sweep_89 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58960B60>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562BB410>
Sweep_90 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1932C0>
Sweep_91 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C050BF0>
Sweep_92 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626F080>
Sweep_93 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562BA3C0>
Sweep_94 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FE7E0>
Sweep_95 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C052000>
Sweep_96 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58936180>
Sweep_97 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56027A70>
Sweep_98 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589372F0>
Sweep_99 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58955D60>
File added




df length: 1777
 dict length: 1777




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M08\M08_MW_A1_C07.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.31it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:04<00:00,  2.48it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.36it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.88it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.38it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.23it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.31it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58955CA0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EF5700>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58947800>
Sweep_37 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53745E20>
Sweep_38 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F12FE00>
Sweep_39 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55A4D850>
Sweep_40 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5D490>
Sweep_41 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380F6E0>
Sweep_42 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BCE60>
Sweep_43 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BC980>
Sweep_44 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F11B830>
File added




df length: 1869
 dict length: 1869




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M08\M08_MW_A1_C08.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.93it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  3.00it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.32it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.27it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.21it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.06it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.66it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.96it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.31it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.46it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.48it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.09it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5C0E0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894B8F0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894D340>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B698BF0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53718D70>
Sweep_36 <spikeparam.patch.fit.fit.Spike object at 0x0000014C537194F0>
Sweep_37 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559C2BA0>
Sweep_38 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B698500>
Sweep_39 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EDE930>
Sweep_40 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894ED20>
Sweep_41 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BC1C920>
Sweep_42 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FCE00>
Sweep_43 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BC1CD70>
Sweep_44 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5895BF20>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B6987D0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F49AC0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BC1CD40>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56286AE0>
File added




df length: 2003
 dict length: 2003




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M08\M08_SM_A1_C03.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.43it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.42it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.34it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.41it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.43it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.28it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.41it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.48it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.38it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.42it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.34it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.43it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:04<00:00,  3.89it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.39it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.35it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BEA50>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313C6B0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B698110>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BFBC0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399DFD0>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BC1C9E0>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B6991C0>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BC1E120>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BCA70>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B69AF90>
Sweep_53 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BCA10>
Sweep_55 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B699A90>
Sweep_56 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534D5E50>
Sweep_57 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B698680>
Sweep_58 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894BF80>
Sweep_59 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BC1C4A0>
Sweep_71 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BDA90>
Sweep_72 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1933E0>
Sweep_73 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58948E90>
Sweep_74 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A0F530>
Sweep_75 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5371BB90>
Sweep_76 <spikeparam.patch.fit.fit.Spike object at 0x0000014C542DA600>
File added




df length: 2222
 dict length: 2222




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M08\M08_SM_A1_C04.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.33s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.03it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.11it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.35it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.78s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.38it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.40s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.34s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894B530>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53718E00>
Sweep_100 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5371BB90>
Sweep_101 <spikeparam.patch.fit.fit.Spike object at 0x0000014C585AFCB0>
Sweep_102 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BC1F1D0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F9B2C0>
Sweep_113 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B9400>
Sweep_114 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53171BE0>
Sweep_115 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559C2D80>
Sweep_116 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EDCB90>
Sweep_117 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA215E0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B80E0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA23D10>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC1340>
Sweep_15 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F44B30>
Sweep_16 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5608DFD0>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F44890>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA21010>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F45280>
Sweep_30 <spikeparam.patch.fit.fit.Spike object at 0x0000014C537186E0>
Sweep_31 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA23650>
Sweep_78 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B6989B0>
Sweep_81 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA23E00>
Sweep_82 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5578F920>
Sweep_84 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA21070>
Sweep_85 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399DFD0>
Sweep_86 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B69A6C0>
Sweep_87 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559C2870>
Sweep_98 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B69BE30>
Sweep_99 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC22D0>
File added




df length: 2269
 dict length: 2269




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M08\M08_SM_A1_C07.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.78s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.02it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C585AFCB0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55931F70>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EF5F70>
Sweep_15 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A0E720>
Sweep_16 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399F200>
Sweep_17 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EF5B80>
Sweep_18 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5578EA80>
Sweep_19 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533CDA60>
File added




df length: 2282
 dict length: 2282




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M08\M08_SM_A1_C09.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.35it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.92it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:04<00:00,  2.40it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.23it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.77it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.72s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.35s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.33s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5519E390>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399C200>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53171D00>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC3FE0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533CD5E0>
Sweep_186 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58950A10>
Sweep_187 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F810A0>
Sweep_188 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC1A60>
Sweep_189 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313E540>
Sweep_190 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58947290>
Sweep_191 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B36DAF0>
Sweep_192 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559C2870>
Sweep_193 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5608E180>
Sweep_194 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53866630>
Sweep_195 <spikeparam.patch.fit.fit.Spike object at 0x0000014C538651F0>
Sweep_196 <spikeparam.patch.fit.fit.Spike object at 0x0000014C550FF860>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B6980E0>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F80230>
Sweep_30 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58966330>
Sweep_31 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B699FD0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B36EA50>
File added




df length: 2346
 dict length: 2346











concat df length: 6121
concat dict length: 6121







C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_JS_A1_C03.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.42it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.42it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.30it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.36it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.38it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.29it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.34it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.29it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.42it/s]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B698DD0>
Sweep_1 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B69ABD0>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53866E10>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B699970>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B699790>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F99520>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F82F60>
Sweep_40 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F47110>
Sweep_41 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A0DDF0>
Sweep_42 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B192A20>
Sweep_43 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BDB80>
Sweep_44 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC2180>
Sweep_45 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B192E10>
Sweep_46 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC2480>
Sweep_47 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BC1F410>
Sweep_48 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B69A510>
Sweep_49 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58947950>
Sweep_50 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC3FE0>
Sweep_51 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC1C10>
Sweep_52 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58958EF0>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F802F0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58958830>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5371B3B0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B8860>
File added




df length: 147
 dict length: 147




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_JS_A1_C04.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.02it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.41s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.48s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.48s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.11it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  3.00it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.46it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.25it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BDC10>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54B23500>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F45A00>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B193050>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53718B30>
Sweep_35 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53780BC0>
Sweep_36 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380E870>
Sweep_37 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA23FE0>
Sweep_38 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F49910>
Sweep_39 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F496A0>
Sweep_40 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58933590>
Sweep_41 <spikeparam.patch.fit.fit.Spike object at 0x0000014C538651F0>
Sweep_42 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F80DA0>
Sweep_43 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC1BB0>
Sweep_44 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B698DD0>
Sweep_45 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58953BF0>
Sweep_46 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B69A510>
Sweep_47 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B69B6E0>
Sweep_48 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F81340>
Sweep_49 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F80140>
Sweep_50 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC0680>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B85F0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5895B980>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B80E0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E4FE0>
File added




df length: 234
 dict length: 234




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_JS_A1_C05.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.33s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.07it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.31s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.06it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.05it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.31s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58945C10>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894D280>
Sweep_113 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C7D40>
Sweep_114 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A0EF60>
Sweep_115 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC3C50>
Sweep_116 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BCA10>
Sweep_117 <spikeparam.patch.fit.fit.Spike object at 0x0000014C550FF3B0>
Sweep_118 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562BBA70>
Sweep_119 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F49730>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C033C80>
Sweep_120 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F99520>
Sweep_121 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B192BA0>
Sweep_122 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F82F60>
Sweep_123 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BCD40>
Sweep_124 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C032CF0>
Sweep_125 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC2B40>
Sweep_126 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F81EE0>
Sweep_127 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58931E80>
Sweep_128 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58951130>
Sweep_129 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58952990>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F82FF0>
Sweep_130 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F82480>
Sweep_131 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617D160>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC3FE0>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C7AD0>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC33E0>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C7B00>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B8800>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BFF20>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B8CE0>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53718200>
Sweep_62 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F49F10>
Sweep_63 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4BDA0>
Sweep_64 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58945C70>
Sweep_65 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B193110>
Sweep_66 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B95B0>
Sweep_67 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562BA7B0>
Sweep_68 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617CD10>
Sweep_69 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58945D30>
Sweep_70 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC2EA0>
Sweep_71 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F47E90>
Sweep_72 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617F410>
Sweep_73 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F45F70>
Sweep_74 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BC1F770>
Sweep_75 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B192F00>
Sweep_76 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BC1DD30>
Sweep_77 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1931D0>
Sweep_78 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399F500>
Sweep_79 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B191070>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5D520>
Sweep_80 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58945100>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617C200>
File added




df length: 302
 dict length: 302




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_JS_A1_C07.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.36s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_119 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56304D70>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B36CEF0>
Sweep_120 <spikeparam.patch.fit.fit.Spike object at 0x0000014C585AF5C0>
Sweep_121 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F468D0>
Sweep_122 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B9760>
Sweep_123 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58950C50>
Sweep_124 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58952990>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA23D10>
Sweep_137 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BCD40>
Sweep_138 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A0DDF0>
Sweep_139 <spikeparam.patch.fit.fit.Spike object at 0x0000014C558EAF60>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B107320>
File added




df length: 315
 dict length: 315




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_JS_A1_C08.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.41s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.39it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380D220>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399F500>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58951310>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617F590>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B69B3B0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53864320>
Sweep_89 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533A3B00>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53864050>
Sweep_90 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53780BC0>
Sweep_91 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B106150>
File added




df length: 334
 dict length: 334




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_JS_A1_C09.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.45it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.23it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.16it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.49it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.72s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:04<00:00,  2.49it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.31it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5E7E0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C558EAF60>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F12CA10>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F12FE90>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C550FED20>
Sweep_48 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA232C0>
Sweep_50 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B8EF0>
Sweep_51 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B36CA70>
Sweep_52 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894A5A0>
Sweep_53 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B192C30>
Sweep_54 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56305760>
Sweep_55 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5CB00>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B191A00>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58948A10>
File added




df length: 441
 dict length: 441




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_JS_A1_C11.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.08it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]

Sweep_100 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BCD40>
Sweep_101 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C030650>
Sweep_102 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4B890>
Sweep_103 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19E4B0>
Sweep_104 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58910E30>
Sweep_105 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58951820>
Sweep_106 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C031160>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53864050>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C033980>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19FC80>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589628D0>
Sweep_97 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19C440>
Sweep_98 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58960CB0>
Sweep_99 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC00E0>
File added




df length: 458
 dict length: 458




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_JS_A1_C13.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.01it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.41it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.29it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5F770>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533A3B00>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5C440>
Sweep_69 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58959E50>
Sweep_70 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4BDA0>
Sweep_71 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4A060>
Sweep_72 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5D310>
File added




df length: 504
 dict length: 504




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_JS_A1_C14.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.05it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.36it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.92it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F46390>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58910E30>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5FCE0>
File added




df length: 517
 dict length: 517




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_JS_A1_C15.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.16it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.15it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.27it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.47it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.30it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.34s/it]

Sweep_1 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B107320>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54B23500>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58933740>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FE000>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C538675C0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53864050>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380EC60>
File added




df length: 591
 dict length: 591




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_JS_A1_C16.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53718FE0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA232C0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534D4B60>
File added




df length: 594
 dict length: 594




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_JS_A1_C17.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.05it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.79it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.42it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.85it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.17it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589309B0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5578F6E0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F454C0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58933110>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA23C80>
File added




df length: 636
 dict length: 636




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_JS_A1_C18.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.96it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.36s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C7A40>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58951310>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313C620>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EDC0B0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BCD40>
Sweep_51 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58950C50>
Sweep_52 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BC8F0>
Sweep_53 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F12D430>
Sweep_54 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F44620>
Sweep_55 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562BBC20>
No metadata found for file: M10_JS_A1_C18
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_JS_A1_C19.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.21it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.39it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.20it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.82it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.09it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.33it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.37it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC1C10>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399F500>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A0F470>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5371B5C0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F99520>
Sweep_49 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589601A0>
Sweep_50 <spikeparam.patch.fit.fit.Spike object at 0x0000014C550FED20>
Sweep_51 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F81430>
Sweep_52 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA215E0>
Sweep_53 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F829F0>
Sweep_54 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58962960>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC16A0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58962E10>
File added




df length: 722
 dict length: 722




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_JS_A1_C20.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.37it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.24it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.51it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.17it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.48it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.66s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.60s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  4.32it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  4.18it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.58it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534D4B60>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C2E91DA30>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589378C0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313C620>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B86B0>
Sweep_56 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589601D0>
Sweep_57 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562856A0>
Sweep_58 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C7A10>
Sweep_59 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5602C260>
Sweep_60 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA215E0>
Sweep_61 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54B23500>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58935970>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58931E80>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5578F5F0>
File added




df length: 839
 dict length: 839




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_JS_A1_C21.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.20it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.60s/it]

Sweep_100 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58960050>
Sweep_101 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BC1DB20>
Sweep_102 <spikeparam.patch.fit.fit.Spike object at 0x0000014C550FF3E0>
Sweep_103 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559C2870>
Sweep_104 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559C1A30>
Sweep_105 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B106720>
Sweep_106 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C032630>
Sweep_107 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894D190>
Sweep_108 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894D280>
Sweep_109 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562BA450>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F46F60>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C7A10>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F12CCE0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C73B0>
Sweep_96 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B106150>
Sweep_97 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19C5C0>
Sweep_98 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F450A0>
Sweep_99 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19C3E0>
File added




df length: 858
 dict length: 858




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_JS_A1_C22.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.52it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.56it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.53it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.25it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.23it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.78s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.60s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.36it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.35it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399D7F0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54B23500>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F99520>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BC1DDF0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BCAA0>
Sweep_51 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5371B5C0>
Sweep_52 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617F410>
Sweep_53 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617D460>
Sweep_54 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19EBA0>
Sweep_55 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F44860>
Sweep_56 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53864320>
Sweep_57 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F45AF0>
Sweep_58 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894A060>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559C2630>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC16A0>
File added




df length: 963
 dict length: 963




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_JS_A1_C23.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.31it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.83it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  3.89it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.10it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.76s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.72s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.56it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19E000>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5602C260>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A0F470>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562BB1D0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58951130>
Sweep_69 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C7C80>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C033F20>
Sweep_70 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C7A70>
Sweep_71 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5895B1A0>
Sweep_72 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19E660>
Sweep_73 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617E0C0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19C7D0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C538675C0>
File added




df length: 1037
 dict length: 1037




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_JS_A1_C24.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.58it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.89it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.86it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  2.92it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.72s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.84it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.75s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.70s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C550FF3B0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B192810>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F99940>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313C620>
Sweep_137 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58946000>
Sweep_138 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589596D0>
Sweep_139 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5578F5F0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313E540>
Sweep_140 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534D4B60>
Sweep_141 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53718E00>
Sweep_142 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FDC10>
Sweep_143 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FF590>
Sweep_144 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BCD40>
Sweep_145 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58910E30>
Sweep_146 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56305370>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC1820>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5895B500>
File added




df length: 1082
 dict length: 1082




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_JS_A1_C25.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5578F5F0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53EEEA80>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399D7F0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55BF7F20>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894D190>
File added




df length: 1088
 dict length: 1088




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_JS_A1_C26.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.66s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.32it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  4.18it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.18it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.33it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:03<00:00,  4.36it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.76s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.76s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.68s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  4.01it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.19it/s]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19E4B0>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F83890>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F12C380>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58956D20>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B9C10>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC0140>
Sweep_57 <spikeparam.patch.fit.fit.Spike object at 0x0000014C538675C0>
Sweep_58 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F9BA10>
Sweep_59 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F81D90>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F440E0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4BCE0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC1F70>
File added




df length: 1194
 dict length: 1194




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_JS_A1_C27.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.72s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.66s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.66s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.04it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.27it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.11it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.60s/it]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589309B0>
Sweep_1 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577D130>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5578F5F0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B8A70>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E4830>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562BA180>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894D190>
Sweep_2 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58931F40>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894D280>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58933C80>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56304EC0>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56286A20>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19D5E0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58952990>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B191910>
No metadata found for file: M10_JS_A1_C27
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_JS_A1_C28.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  3.72it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  4.02it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:03<00:00,  4.32it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.11it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  3.95it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.69s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.83it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.09it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  3.33it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FD0A0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC3FE0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399D7F0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC31D0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56285220>
Sweep_58 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC0770>
Sweep_59 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562BB620>
Sweep_60 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F12C260>
Sweep_61 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC1310>
Sweep_62 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53866E10>
Sweep_63 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58963EF0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FE990>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4BF80>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5371B3B0>
File added




df length: 1299
 dict length: 1299




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_JS_A1_C30.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.64s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.63s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B107320>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399D7F0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F47860>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58946E70>
Sweep_62 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC1310>
Sweep_63 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58962A80>
Sweep_64 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534D4B60>
Sweep_65 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384D1C0>
Sweep_66 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F81430>
Sweep_67 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380EC60>
Sweep_68 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58962000>
File added




df length: 1310
 dict length: 1310




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_JS_A1_C32.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.07it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.66it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.61s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.57s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.48it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  2.80it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.57s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.66s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4A3F0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B9190>
Sweep_110 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19E510>
Sweep_112 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E6AE0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384C320>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19FE00>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA232C0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58960050>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577DA00>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5EEA0>
File added




df length: 1348
 dict length: 1348




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_MJ_A1_C01.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

No metadata found for file: M10_MJ_A1_C01
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_MJ_A1_C02.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.25it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.54it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.20it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.49it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626DF40>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55BF7F20>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577D790>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5895A390>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58934050>
Sweep_63 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F81340>
Sweep_64 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F445F0>
Sweep_65 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589579E0>
Sweep_66 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B190680>
Sweep_67 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589453D0>
Sweep_68 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577F290>
Sweep_69 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58944CE0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19FFB0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B9C40>
No metadata found for file: M10_MJ_A1_C02
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_MJ_A1_C03.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.19it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.66s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.29it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.26it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.36it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.84it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.85it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.83it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.51it/s]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B9A60>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BE8A0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BEF30>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C51D04CB0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589619A0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55BF7F20>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58961220>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58933830>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53866630>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BFB30>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399D7F0>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC1820>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F42C60>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5602C260>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58948350>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58960470>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA215E0>
File added




df length: 1404
 dict length: 1404




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_MJ_A1_C06.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.55it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.71it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  3.98it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.04it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  2.71it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.25it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.04it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.14it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.42it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.04it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.60s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  2.85it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:05<00:00,  2.55it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:05<00:00,  2.53it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:06<00:00,  2.38it/s]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577D580>
Sweep_1 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B8EF0>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F802F0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA232C0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559C1A30>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380D220>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58957500>
Sweep_2 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562BA420>
Sweep_3 <spikeparam.patch.fit.fit.Spike object at 0x0000014C51D04CB0>
Sweep_4 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F42AB0>
Sweep_42 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B96A0>
Sweep_44 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B69B6E0>
Sweep_45 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617FDD0>
Sweep_46 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58958080>
Sweep_47 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577C5F0>
Sweep_48 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58944C50>
Sweep_49 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B192630>
Sweep_50 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562BBF80>
Sweep_52 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B193DD0>
Sweep_53 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FCA10>
Sweep_54 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1919A0>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B8B60>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC2780>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58933EC0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC0230>
File added




df length: 1549
 dict length: 1549




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_MJ_A1_C10.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.76s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.77s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313C620>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5F440>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384FE90>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53867CE0>
No metadata found for file: M10_MJ_A1_C10
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_MJ_A1_C11.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

No metadata found for file: M10_MJ_A1_C11
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_MJ_A1_C12.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.07s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380D220>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313E540>
No metadata found for file: M10_MJ_A1_C12
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_SA_A1_C01.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.21it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:06<00:00,  2.23it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:06<00:00,  2.21it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.30it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:05<00:00,  2.53it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.71s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.20it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.39it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.08it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.24it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  3.48it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.63it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.75s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.65it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  3.81it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA232C0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BEF90>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56284830>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C73E0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617E4E0>
Sweep_140 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B8500>
Sweep_141 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626D7C0>
Sweep_142 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58952990>
Sweep_143 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617F380>
Sweep_144 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F83890>
Sweep_21 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C7D40>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626F470>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626D9A0>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C033AA0>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58954680>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56285580>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58955B80>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56285D90>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC0770>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58960050>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58962C30>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B9220>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589365D0>
File added




df length: 1722
 dict length: 1722




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_SA_A1_C02.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  3.83it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.72it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  3.53it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.47it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.63it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.69s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.29it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.37it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C73E0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA232C0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BD070>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399D5B0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B698920>
Sweep_57 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559C1A30>
Sweep_58 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562BA840>
Sweep_59 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53867CE0>
Sweep_60 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577D6A0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C7D40>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589442C0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BE480>
File added




df length: 1833
 dict length: 1833




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_SA_A1_C03.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.02it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.32it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.79it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.07it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.08it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.47it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.68it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.89it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617F9B0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA232C0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C7D40>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C73E0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56026840>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53864230>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F12FE00>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56284E90>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C051B80>
File added




df length: 1877
 dict length: 1877




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_SA_A1_C05.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.63s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.66s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.68s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4C9310>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C7D40>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4CBEF0>
Sweep_15 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4CA7E0>
Sweep_16 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58956300>
Sweep_68 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC2600>
Sweep_70 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58951820>
File added




df length: 1884
 dict length: 1884




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_SA_A1_C06.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.04it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:05<00:00,  2.65it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.45it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:05<00:00,  2.49it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.23it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.85s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.88s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:04<00:00,  1.95it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.79s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.77it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:05<00:00,  2.97it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.81s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 26/26 [00:04<00:00,  5.37it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.90it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.18it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  3.38it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  3.55it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.66it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.37it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.40it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.79it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.27it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.11it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.42it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.77it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.76s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.71s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.97it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.20it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.02it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.17it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.06it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.00it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:05<00:00,  2.96it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:04<00:00,  2.43it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.36it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.58it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.22it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F49AC0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C73E0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562841D0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53864AD0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EEEEA0>
Sweep_15 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC0770>
Sweep_16 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B8E30>
Sweep_17 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5EFC0>
Sweep_18 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C052E70>
Sweep_19 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F46E40>
Sweep_2 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F12CCE0>
Sweep_20 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53867CE0>
Sweep_3 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58954AA0>
Sweep_4 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53867860>
Sweep_64 <spikeparam.patch.fit.fit.Spike object at 0x0000014C563047A0>
Sweep_66 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B8320>
Sweep_72 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58957FB0>
Sweep_73 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562BAED0>
Sweep_74 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626E090>
Sweep_75 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC1C10>
Sweep_76 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626E870>
Sweep_77 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626FE60>
Sweep_78 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5CDA0>
Sweep_79 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5E7E0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C050E60>
Sweep_80 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C051A90>
Sweep_81 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C054AD0>
Sweep_82 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56024680>
Sweep_83 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C055C70>
Sweep_84 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4CB170>
Sweep_85 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C055CD0>
Sweep_87 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4CA8D0>
Sweep_88 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0542F0>
Sweep_89 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4C8B00>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0544D0>
Sweep_90 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56287950>
Sweep_91 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0551F0>
Sweep_92 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56285160>
Sweep_93 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56024DA0>
Sweep_94 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562BA7B0>
Sweep_95 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B9460>
Sweep_96 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C051250>
File added




df length: 2244
 dict length: 2244




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_SA_A1_C07.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.31it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:06<00:00,  2.60it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:05<00:00,  2.54it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:06<00:00,  2.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:06<00:00,  2.23it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.43it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.75s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  2.91it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  2.93it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.14it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.24it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.38it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.66s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.70s/it]

Sweep_100 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58934350>
Sweep_101 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58935FD0>
Sweep_102 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56305370>
Sweep_103 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EEEEA0>
Sweep_104 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA215E0>
Sweep_105 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56307C20>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F44380>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F49700>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B191B20>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4BCE0>
Sweep_15 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58959AF0>
Sweep_16 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56307050>
Sweep_17 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FC4A0>
Sweep_88 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B106900>
Sweep_89 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B107320>
Sweep_90 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380D220>
Sweep_99 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559C2630>
File added




df length: 2406
 dict length: 2406




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_SA_A1_C08.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.60it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.57it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.68it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.77it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.80it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.67it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  3.61it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.72s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.26it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.64it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.49it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399C8F0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B107320>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53864230>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577CD70>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626FAA0>
Sweep_15 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58952990>
Sweep_16 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FDC70>
Sweep_46 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313E540>
Sweep_47 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58937BF0>
Sweep_48 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC3FE0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19F0B0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56287B60>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C7770>
File added




df length: 2558
 dict length: 2558




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_SA_A1_C10.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████| 105/105 [00:04<00:00, 22.92it/s]

Fitting failed for sweep Sweep_0: Length of values (106) does not match length of index (105)

Spike: 100%|███████████████████████████████████████████████████████████████████████████| 87/87 [00:04<00:00, 18.55it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 49/49 [00:04<00:00, 10.47it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  3.53it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.32it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.26it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:05<00:00,  3.11it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:05<00:00,  3.11it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:05<00:00,  3.17it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:05<00:00,  3.01it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 111/111 [00:05<00:00, 19.72it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.05it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.76s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.66s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 41/41 [00:05<00:00,  7.06it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 78/78 [00:06<00:00, 12.45it/s]

Sweep_1 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58952990>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C7D40>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399C8F0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53EEEA80>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F46C00>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B9190>
Sweep_15 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562BA450>
Sweep_16 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5DE50>
Sweep_17 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B80E0>
Sweep_2 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562BA180>
Sweep_3 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589476E0>
Sweep_39 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19EBA0>
Sweep_4 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC31D0>
Sweep_40 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F82E40>
Sweep_41 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F80A10>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C051250>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC2600>
No metadata found for file: M10_SA_A1_C10
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_SA_A1_C11.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.16it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.32it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:04<00:00,  1.83it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.18it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.22it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.72s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.68s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.73s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.39it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589489E0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FEBD0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C7FB0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562867E0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C560252B0>
Sweep_151 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FDC70>
Sweep_157 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5ECF0>
Sweep_158 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577D7F0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC0770>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626C3B0>
File added




df length: 2606
 dict length: 2606




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_SA_A1_C14.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.75s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.73s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA215E0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589476E0>
Sweep_115 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56026300>
Sweep_116 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56025580>
Sweep_119 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58931F40>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C033830>
Sweep_120 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C032810>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56027440>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5EFC0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBE1E0>
File added




df length: 2616
 dict length: 2616




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M10\M10_SA_A1_C15.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.72s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.75s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.80s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.76s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.57s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.63s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_101 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4C8140>
Sweep_102 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B8EF0>
Sweep_103 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F01D0>
Sweep_104 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589493A0>
Sweep_105 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626DDF0>
Sweep_106 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626E270>
Sweep_107 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B8CB0>
Sweep_108 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC00E0>
Sweep_109 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5895ACF0>
Sweep_110 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC2480>
Sweep_111 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B9820>
Sweep_112 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C030B30>
Sweep_113 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0300B0>
Sweep_114 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0337A0>
Sweep_115 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B8C80>
Sweep_116 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B9760>
Sweep_117 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BEFC0>
Sweep_118 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5AEA0>
Sweep_119 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F4AC60>
Sweep_120 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58957500>
Sweep_121 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5895A870>
Sweep_122 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626FEC0>
Sweep_123 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C054320>
Sweep_124 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BE630>
Sweep_125 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C055C70>
Sweep_126 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BE570>
Sweep_127 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C054C80>
Sweep_128 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BCCB0>
Sweep_129 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BD190>
Sweep_18 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5A780>
Sweep_97 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C054680>
Sweep_98 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BC380>
File added




df length: 2648
 dict length: 2648











concat df length: 8769
concat dict length: 8769







C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M11\M11_SA_A1_C02.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.54it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.09it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.11it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.72s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.88it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.02it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19E420>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C563048C0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399C8F0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562862A0>
Sweep_42 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BC1F9B0>
Sweep_43 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5634E810>
Sweep_44 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5895ACF0>
Sweep_45 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E5D60>
Sweep_46 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C033830>
Sweep_47 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E5430>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53EEEA80>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58952F00>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5602C260>
File added




df length: 29
 dict length: 29











concat df length: 8798
concat dict length: 8798







C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M12\M12_JS_A1_C01.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.69it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.47it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.35it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.14it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  3.90it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.69s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.72s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.64s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.63it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.38it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.54it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626FE60>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C540274A0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F0C20>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534719D0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0ECBC0>
Sweep_41 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B106DE0>
Sweep_42 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58954890>
Sweep_43 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B106900>
Sweep_44 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54B23CE0>
Sweep_45 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58951100>
Sweep_46 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19CC80>
Sweep_47 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B9190>
Sweep_48 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1924E0>
Sweep_49 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5C680>
Sweep_50 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F12CD70>
Sweep_51 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19F6E0>
Sweep_52 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F4AE10>
Sweep_53 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F44E00>
Sweep_54 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562BA420>
Sweep_55 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BC9E0>
Sweep_56 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577CFE0>
Sweep_57 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B107320>
Sweep_58 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B8CB0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B9820>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BC1E720>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F1310>
File added




df length: 125
 dict length: 125




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M12\M12_JS_A1_C02.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.25it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.29it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.05it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  3.85it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  3.68it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.68s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.80it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  3.46it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  3.86it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58949A30>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589464E0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534719D0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5634CEF0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313C680>
Sweep_154 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5602C260>
Sweep_155 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C051730>
Sweep_156 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4CA570>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E5280>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E44A0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5E7E0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F81EE0>
File added




df length: 234
 dict length: 234




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M12\M12_JS_A1_C04.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.64s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.72s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.73s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.60s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626ED80>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F1993D0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53864230>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B193C20>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626FE60>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BF110>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F82C30>
Sweep_30 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B193A70>
Sweep_31 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5CD70>
Sweep_32 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53653770>
Sweep_33 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58933EC0>
Sweep_34 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58936B40>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC33E0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589574A0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4A210>
File added




df length: 249
 dict length: 249




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M12\M12_JS_A1_C05.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.56s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.82s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5367B320>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C051730>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577D7F0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626FE60>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C536508C0>
Sweep_55 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1050D0>
Sweep_56 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BDC10>
Sweep_57 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F442C0>
Sweep_58 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1055E0>
Sweep_59 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562862A0>
Sweep_60 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4C9EE0>
Sweep_61 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F59760>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626DDF0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F12B0>
File added




df length: 263
 dict length: 263




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M12\M12_JS_A1_C08.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.70s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53651D60>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0515E0>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399C8F0>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5895ACF0>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626FE60>
Sweep_4 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FEBD0>
File added




df length: 269
 dict length: 269




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M12\M12_JS_A1_C11.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.69it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.33it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  3.87it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.54it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.09it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.76s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.58s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.30it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.18it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.12it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.02it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A2420>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C030470>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B107320>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B36D370>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58933EC0>
Sweep_30 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0337A0>
Sweep_32 <spikeparam.patch.fit.fit.Spike object at 0x0000014C563048C0>
Sweep_33 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E75C0>
Sweep_34 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53867680>
Sweep_5 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F82E40>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BCC80>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894A300>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54027950>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58948170>
File added




df length: 389
 dict length: 389




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M12\M12_JS_A1_C12.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.31it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.01it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  3.88it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  3.74it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.45it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626C140>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58950260>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F12FE00>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19E420>
Sweep_5 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B8320>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C563048C0>
File added




df length: 444
 dict length: 444




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M12\M12_JS_A1_C14.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.04it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.04it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.87it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.00it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.55it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  3.80it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.86it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.08s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F595B0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577D7F0>
Sweep_3 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F12FE00>
Sweep_4 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC39E0>
Sweep_5 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F1E20>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA11550>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBD5B0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58950260>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589349E0>
File added




df length: 513
 dict length: 513




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M12\M12_SA_A1_C02.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.68s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.70s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.72s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.71s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.78s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.60s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F4E4B0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA115B0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F81340>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA137A0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B193C20>
Sweep_47 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B88F0>
Sweep_48 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F12CD70>
Sweep_49 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589537D0>
Sweep_50 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5EC60>
Sweep_51 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BE8D0>
Sweep_52 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E5BB0>
Sweep_53 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19E270>
Sweep_54 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384F020>
Sweep_55 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589483E0>
Sweep_56 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BF110>
Sweep_57 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5DB20>
Sweep_58 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562862A0>
Sweep_59 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BFB30>
Sweep_60 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626E270>
Sweep_61 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC1820>
Sweep_62 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E70E0>
Sweep_63 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C030AD0>
Sweep_64 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F58C50>
Sweep_65 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B106540>
Sweep_66 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA10770>
Sweep_67 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0ED070>
Sweep_68 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F442C0>
Sweep_69 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589575F0>
Sweep_70 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5F560>
Sweep_71 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B193830>
Sweep_72 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA13740>
File added




df length: 544
 dict length: 544




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M12\M12_SA_A1_C07.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.69s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589575F0>
Sweep_84 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53718E00>
Sweep_85 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F455B0>
Sweep_86 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F99940>
Sweep_87 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F442C0>
Sweep_88 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B106150>
File added




df length: 550
 dict length: 550




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M12\M12_SA_A1_C08.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.78s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.88s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.85s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F49250>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F4DB20>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4C9760>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA11550>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B106DE0>
Sweep_57 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BD7F0>
Sweep_58 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0EEE70>
Sweep_59 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F595B0>
File added




df length: 558
 dict length: 558




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M12\M12_SA_A1_C09.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.74s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F99F10>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53718E00>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F12D460>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F99940>
File added




df length: 562
 dict length: 562




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M12\M12_SA_A1_C10.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.60s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.42it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BC1FBF0>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C537466C0>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58933830>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0538F0>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589465A0>
File added




df length: 575
 dict length: 575




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M12\M12_SA_A1_C11.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.75s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.61it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.59it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.41it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.74s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.55it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BDEB0>
Sweep_102 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58950770>
Sweep_103 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53651AF0>
Sweep_104 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC39E0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58950C50>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562BB1A0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4CAEA0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0376B0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577D730>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589575F0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5367B8F0>
File added




df length: 596
 dict length: 596




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M12\M12_SA_A1_C13.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.61s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_21 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F81340>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F12CD70>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0515E0>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562B9D00>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F46CC0>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FF470>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626DDF0>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F496A0>
File added




df length: 604
 dict length: 604




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M12\M12_SA_A1_C14.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F1993D0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F45E20>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58937D70>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577D730>
File added




df length: 608
 dict length: 608











concat df length: 9406
concat dict length: 9406







C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_JS_A1_C01.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.72s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.72s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.69s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.68s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.68s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.60s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58936D20>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5608DFD0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F2CC0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0576B0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56307050>
Sweep_36 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53864230>
Sweep_39 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E6840>
Sweep_44 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA13830>
Sweep_45 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C053B00>
Sweep_46 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BC1D460>
Sweep_47 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F6AF90>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589349E0>
File added




df length: 12
 dict length: 12




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_JS_A1_C02.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.59s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.72s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0EF3E0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5ECC0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4A930>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53652AB0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FF470>
Sweep_5 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EF5B80>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58949040>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577D7F0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589476E0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C563A7EF0>
No metadata found for file: M19_JS_A1_C02
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_JS_A1_C03.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.64s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F81850>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B69B2F0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F12D460>
File added




df length: 15
 dict length: 15




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_JS_A1_C04.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.60s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FC4A0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589476E0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C035D60>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5608DFD0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5367BCB0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C75C0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894B3E0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577F4D0>
File added




df length: 31
 dict length: 31




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_JS_A1_C05.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.71s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.79s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.72s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.74s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F4CA40>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EF5B80>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F62FF0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F48C50>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56285730>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58942210>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C056060>
Sweep_87 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562840B0>
Sweep_88 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58960260>
Sweep_89 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626E090>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C056720>
Sweep_90 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C056AB0>
Sweep_91 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F61910>
Sweep_92 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4C85C0>
Sweep_93 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BC860>
File added




df length: 49
 dict length: 49




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_JS_A1_C06.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.95s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58933830>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B69BB90>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53678B60>
File added




df length: 52
 dict length: 52




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_JS_A1_C07.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.42s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.48s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.25s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.81s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  5.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.57s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589465A0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626F0B0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F2270>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E4B60>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F54470>
Sweep_60 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C051B20>
Sweep_62 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBC530>
Sweep_63 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534BBCE0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F1100>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BC0B0>
File added




df length: 63
 dict length: 63




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_JS_A1_C08.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.78s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_175 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BCF20>
Sweep_176 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBE4E0>
Sweep_177 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56287470>
Sweep_178 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBD070>
Sweep_179 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBE9C0>
Sweep_30 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54027EF0>
Sweep_31 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53747530>
Sweep_32 <spikeparam.patch.fit.fit.Spike object at 0x0000014C542DA600>
Sweep_33 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EF4E00>
Sweep_34 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589658E0>
Sweep_35 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55A4D850>
Sweep_36 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53051D60>
Sweep_37 <spikeparam.patch.fit.fit.Spike object at 0x0000014C2DFC2390>
Sweep_38 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EF7170>
Sweep_39 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559329F0>
File added




df length: 78
 dict length: 78




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_JS_A1_C09.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559C1910>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55A4D850>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A5F0E0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F53470>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58966330>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C558EB320>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EDC0B0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FFD70>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5519DE50>
File added




df length: 87
 dict length: 87




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_JS_A1_C10.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.42it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.60it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.60it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.56it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.83it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.07s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.76s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.76s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.61it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.83s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.83s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.00s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53EED280>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C2DFC2390>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5893BEC0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C563A55B0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5519DD60>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBF0E0>
Sweep_87 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53EEEA80>
Sweep_88 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53EEE8A0>
Sweep_89 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A5C470>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5893BD70>
Sweep_90 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5893A690>
Sweep_91 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617ED20>
Sweep_92 <spikeparam.patch.fit.fit.Spike object at 0x0000014C51D050D0>
Sweep_93 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5893B7A0>
Sweep_94 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5579AFC0>
File added




df length: 130
 dict length: 130




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_JS_A1_C11.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.78s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.88s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577CC20>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53051D60>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5608DFD0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A5C470>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBC1A0>
Sweep_15 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A5F140>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C73B0>
File added




df length: 137
 dict length: 137




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_JS_A1_C13.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.35it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.40it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.28it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.30it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.37it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.72s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.72it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.42it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589658E0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577E510>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534D5E50>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53652390>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53653020>
Sweep_53 <spikeparam.patch.fit.fit.Spike object at 0x0000014C2EB6E690>
Sweep_54 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58938410>
Sweep_55 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577D790>
Sweep_56 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380D250>
Sweep_57 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5893ABD0>
Sweep_58 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577C7D0>
Sweep_59 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EDC0B0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577D100>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53745790>
File added




df length: 240
 dict length: 240




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_JS_A1_C14.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.78s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_1 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894D400>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C551B7EC0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5893A5D0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C537812E0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53EEE8A0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53EEE870>
Sweep_15 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559EE2D0>
Sweep_16 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58946DE0>
Sweep_17 <spikeparam.patch.fit.fit.Spike object at 0x0000014C585AFCB0>
Sweep_18 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A0F530>
Sweep_65 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58950260>
Sweep_66 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534BB7A0>
Sweep_67 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58952BD0>
Sweep_68 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58951310>
Sweep_69 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617E630>
Sweep_70 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589456D0>
Sweep_71 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54C82090>
Sweep_72 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58938170>
Sweep_73 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA23C80>
Sweep_74 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589628D0>
Sweep_75 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53780BC0>
Sweep_76 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5371BB90>
File added




df length: 262
 dict length: 262




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_JS_A1_C15.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.05it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.65it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.04it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.01it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.06it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.44s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_18 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBFAD0>
Sweep_19 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FE480>
Sweep_20 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577D640>
Sweep_21 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577D0D0>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B36CCE0>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559EE2D0>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533BEC30>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58952990>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F9BA10>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557470E0>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5461F6E0>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894CFE0>
Sweep_30 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0D6AF770>
Sweep_31 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B69B950>
Sweep_32 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C7DA0>
Sweep_33 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B8B90>
Sweep_34 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54C82090>
File added




df length: 286
 dict length: 286




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_MM_A1_C01.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  2.79it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  4.04it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.60it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.38it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.90it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.87it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.40it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.94it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.53it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.29it/s]

Sweep_1 <spikeparam.patch.fit.fit.Spike object at 0x0000014C537D11F0>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EC2C60>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53460A70>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58939010>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53745E20>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58962510>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B36CCE0>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C558CA4E0>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A5D700>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557996A0>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533CDA60>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5461FF20>
File added




df length: 386
 dict length: 386




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_MM_A1_C02.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58931100>
No metadata found for file: M19_MM_A1_C02
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_MM_A1_C03.nwb
No metadata found for file: M19_MM_A1_C03
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_MM_A1_C05.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.48s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.06it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.72it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.50it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.98it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.07it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B36CCE0>
Sweep_17 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534C0110>
Sweep_18 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589619A0>
Sweep_19 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533CDA60>
Sweep_20 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FD670>
Sweep_21 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B8E30>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557996A0>
File added




df length: 406
 dict length: 406




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_MM_A1_C06.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.81it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.23it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  4.04it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.16it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.05it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.80s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.91s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.48s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.02s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  4.07it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  4.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.94it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53460A70>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534B8E30>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58950C50>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5895AC30>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534C1070>
Sweep_67 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55799340>
Sweep_68 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399CD70>
Sweep_69 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55763830>
Sweep_70 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58946C90>
Sweep_71 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53EEE8A0>
Sweep_72 <spikeparam.patch.fit.fit.Spike object at 0x0000014C560A4080>
Sweep_73 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5602F6E0>
Sweep_74 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A0DDF0>
Sweep_85 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533BE120>
Sweep_86 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5893B0E0>
Sweep_87 <spikeparam.patch.fit.fit.Spike object at 0x0000014C563A4680>
Sweep_88 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5519DE50>
Sweep_89 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58946F30>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58952B10>
File added




df length: 519
 dict length: 519




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_MM_A1_C07.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.46it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.47it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.95it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.48s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]

Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5380D250>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C560A66F0>
Sweep_30 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5578F290>
Sweep_31 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5519E420>
Sweep_32 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54D7DC70>
Sweep_33 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58952BD0>
Sweep_34 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5893A690>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58937E60>
Sweep_91 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C7590>
Sweep_94 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58953170>
Sweep_95 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA21C40>
Sweep_96 <spikeparam.patch.fit.fit.Spike object at 0x0000014C563A5520>
Sweep_97 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F99730>
Sweep_98 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58952990>
File added




df length: 572
 dict length: 572




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_MM_A1_C08.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.76s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_30 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5895D8B0>
Sweep_31 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A5F140>
Sweep_32 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EF5700>
Sweep_33 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53171BE0>
Sweep_34 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53EEE870>
Sweep_35 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534C0110>
Sweep_36 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F484A0>
Sweep_37 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A2F90>
Sweep_38 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E6CF0>
Sweep_39 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FD8B0>
Sweep_40 <spikeparam.patch.fit.fit.Spike object at 0x0000014C536793D0>
Sweep_41 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C74D0>
Sweep_44 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533BFE00>
Sweep_45 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F4B530>
Sweep_48 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C6C30>
Sweep_49 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58963EF0>
Sweep_51 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58938B00>
Sweep_52 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A0C530>
Sweep_53 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A3590>
Sweep_54 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58954050>
Sweep_56 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBDFD0>
Sweep_57 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58955FA0>
Sweep_58 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBC3E0>
Sweep_59 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBE840>
Sweep_60 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A0110>
Sweep_61 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E57C0>
Sweep_62 <spikeparam.patch.fit.fit.Spike object at 0x0000014C563A4860>
Sweep_63 <spikeparam.patch.fit.fit.Spike object at 0x0000014C563A71D0>
Sweep_64 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A1A90>
Sweep_65 <spikeparam.patch.fit.fit.Spike object at 0x0000014C560A43B0>
Sweep_66 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B69BDD0>
File added




df length: 603
 dict length: 603




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_MM_A1_C09.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.44s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.44s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_17 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557469F0>
Sweep_18 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B36F230>
Sweep_19 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58950B00>
Sweep_20 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5578F260>
Sweep_21 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4A2D0>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A5F140>
Sweep_78 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A5D700>
Sweep_79 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5519DE50>
Sweep_80 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EF5700>
Sweep_81 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534C0110>
Sweep_82 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B69ABD0>
Sweep_83 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894CFE0>
Sweep_84 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5578ED20>
Sweep_85 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53EED280>
Sweep_86 <spikeparam.patch.fit.fit.Spike object at 0x0000014C563A7110>
Sweep_87 <spikeparam.patch.fit.fit.Spike object at 0x0000014C563A71D0>
Sweep_88 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53EEE8A0>
File added




df length: 620
 dict length: 620




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_MM_A1_C10.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.65it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.08it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.21it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.65it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.52it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.82s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.85s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.83s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.22it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BC1FF20>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5514B050>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C51D050D0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58938170>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55799B20>
Sweep_15 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4A2D0>
Sweep_16 <spikeparam.patch.fit.fit.Spike object at 0x0000014C560A79B0>
Sweep_17 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55A7CBC0>
Sweep_18 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53867680>
Sweep_19 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53864320>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54C82090>
Sweep_30 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58950B00>
Sweep_31 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C75C0>
Sweep_32 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5519DE50>
Sweep_33 <spikeparam.patch.fit.fit.Spike object at 0x0000014C560A6F60>
Sweep_34 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0D6AF770>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53746B70>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589348F0>
File added




df length: 670
 dict length: 670




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_MM_A1_C11.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.72s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.72s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533F6270>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58938170>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53171BE0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A3890>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F499A0>
Sweep_80 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5893A690>
Sweep_82 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F4B500>
Sweep_83 <spikeparam.patch.fit.fit.Spike object at 0x0000014C550FF4A0>
Sweep_84 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53EEF860>
Sweep_85 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384F530>
Sweep_86 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5367B320>
Sweep_87 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A19A0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A0B00>
File added




df length: 683
 dict length: 683




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_SA_A1_C01.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.21it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.62it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.65it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5371BC80>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53171BE0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5399C110>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B699D60>
File added




df length: 701
 dict length: 701




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_SA_A1_C02.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBC7D0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5519DE50>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBEAB0>
Sweep_65 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5578F4A0>
Sweep_66 <spikeparam.patch.fit.fit.Spike object at 0x0000014C537D1EE0>
Sweep_75 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5895CFB0>
Sweep_76 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58947800>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577CB30>
File added




df length: 709
 dict length: 709




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_SA_A1_C03.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.01it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.02it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.26it/s]

Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E4FE0>
Sweep_66 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54C897F0>
Sweep_67 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384C140>
Sweep_68 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBC680>
Sweep_69 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53678A40>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58939340>
Sweep_70 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5893A690>
Sweep_71 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F48F50>
Sweep_72 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557989B0>
Sweep_73 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557996D0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384F530>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F49370>
File added




df length: 727
 dict length: 727




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_SA_A1_C05.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4AED0>
No metadata found for file: M19_SA_A1_C05
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_SA_A1_C06.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.06it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.44s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A2720>
Sweep_84 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534BBCE0>
Sweep_85 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FD8B0>
Sweep_86 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4B050>
Sweep_87 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F47830>
Sweep_88 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B69AAB0>
File added




df length: 736
 dict length: 736




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_SA_A1_C08.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58954350>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55799B20>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894CFE0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F49DC0>
Sweep_55 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5634EAE0>
Sweep_56 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C7E00>
Sweep_59 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A7366C0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52EF67B0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F49AF0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F4A9F0>
File added




df length: 746
 dict length: 746




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_SA_A1_C09.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

No metadata found for file: M19_SA_A1_C09
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M19\M19_SA_A1_C10.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.59it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.23it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.88it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54D7DC70>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C7CE0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C536789E0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C563A5340>
File added




df length: 762
 dict length: 762











concat df length: 10168
concat dict length: 10168







C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M20\M20_JS_A1_C01.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.99it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.17it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.43it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.40it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.31it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54C897F0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5895CFB0>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5895B320>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A5F140>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C537194F0>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5894CFE0>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A7347A0>
File added




df length: 62
 dict length: 62




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M20\M20_JS_A1_C02.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.20it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.07it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  3.82it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  3.52it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.99it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.48s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.48s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.44s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C7CE0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C537D2360>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FE0F0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B104B00>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FF0B0>
Sweep_15 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5367B650>
Sweep_16 <spikeparam.patch.fit.fit.Spike object at 0x0000014C563A5400>
Sweep_50 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B107320>
Sweep_51 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58959EB0>
Sweep_52 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533BFE00>
Sweep_53 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617D8E0>
Sweep_54 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53653770>
Sweep_55 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589543E0>
Sweep_56 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4A9C0>
Sweep_57 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4A990>
Sweep_58 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58934A40>
Sweep_59 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626CB90>
Sweep_60 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F499A0>
Sweep_61 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C052ED0>
Sweep_62 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C053DD0>
Sweep_63 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC03E0>
Sweep_64 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5D100>
Sweep_65 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E6D20>
Sweep_66 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617F560>
Sweep_67 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1077D0>
Sweep_68 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5CB90>
Sweep_69 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BC1EDE0>
Sweep_70 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F11B830>
Sweep_71 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E6930>
Sweep_72 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A2AB0>
Sweep_73 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1057C0>
Sweep_74 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58956870>
Sweep_75 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F4B980>
Sweep_76 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E5EB0>
Sweep_77 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589338F0>
Sweep_78 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBDA00>
Sweep_79 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B698C50>
Sweep_80 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58956B40>
Sweep_81 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F46F60>
Sweep_82 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5CEF0>
Sweep_83 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F47A70>
Sweep_84 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5EB10>
Sweep_85 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5C9E0>
File added




df length: 173
 dict length: 173




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M20\M20_JS_A1_C03.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.36it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.47it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.45it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.35it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.39it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.24it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  3.96it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  3.98it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.44s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.02s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  4.15it/s]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A12E0>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C537185C0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5519DE50>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C550FF4A0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577E480>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A7366C0>
Sweep_20 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58959EB0>
Sweep_21 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617D8E0>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533BFE00>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F48BC0>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617F560>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56305F70>
Sweep_45 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F4BDD0>
Sweep_48 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBF7A0>
Sweep_50 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19D760>
Sweep_51 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53653770>
Sweep_52 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C7710>
Sweep_53 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1051C0>
Sweep_54 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5895F560>
Sweep_55 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589316A0>
Sweep_56 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FE330>
Sweep_57 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617E870>
Sweep_58 <spikeparam.patch.fit.fit.Spike object at 0x0000014C563A4320>
Sweep_59 <spikeparam.patch.fit.fit.Spike object at 0x0000014C51D050D0>
Sweep_60 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58958CB0>
Sweep_61 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FDFD0>
Sweep_62 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0EE2A0>
Sweep_63 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58960B60>
Sweep_64 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B698A10>
Sweep_65 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E5FD0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F492B0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F80BC0>
File added




df length: 330
 dict length: 330




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M20\M20_MM_A1_C01.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  4.11it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E4BC0>
Sweep_38 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C7710>
Sweep_39 <spikeparam.patch.fit.fit.Spike object at 0x0000014C563A5400>
Sweep_40 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5577E480>
No metadata found for file: M20_MM_A1_C01
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M20\M20_MM_A1_C02.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.44s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_151 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53867680>
Sweep_152 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0509B0>
Sweep_153 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B69B6E0>
Sweep_154 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4ACC0>
Sweep_155 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53EEF860>
Sweep_156 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5634EB70>
Sweep_157 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589543E0>
Sweep_158 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B107410>
Sweep_159 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0EE2A0>
Sweep_160 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58940620>
Sweep_161 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B699130>
Sweep_162 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBF320>
Sweep_163 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58959B80>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBEC90>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589575F0>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C053B00>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F44200>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E6F30>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBE270>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5E420>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F40A40>
Sweep_30 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5602D430>
Sweep_31 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A02F0>
File added




df length: 353
 dict length: 353




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M20\M20_MM_A1_C03.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.28it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.16it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.31it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  4.20it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.30it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.22it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.03it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  3.86it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  3.95it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  3.99it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.98it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.85it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_115 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A3440>
Sweep_116 <spikeparam.patch.fit.fit.Spike object at 0x0000014C537D1EE0>
Sweep_118 <spikeparam.patch.fit.fit.Spike object at 0x0000014C563A4320>
Sweep_119 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F4BB60>
Sweep_120 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBEC90>
Sweep_121 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54026480>
Sweep_122 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F428D0>
Sweep_123 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A18B0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FE0F0>
Sweep_138 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5602C3B0>
Sweep_139 <spikeparam.patch.fit.fit.Spike object at 0x0000014C560A7290>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C536789E0>
Sweep_140 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B699BE0>
Sweep_141 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B106C90>
Sweep_142 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A2B10>
Sweep_143 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56284380>
Sweep_144 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53651D60>
Sweep_145 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B5231A0>
Sweep_146 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0509B0>
Sweep_147 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384FF80>
File added




df length: 530
 dict length: 530




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M20\M20_MM_A1_C04.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C537D1EE0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FE0F0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53651D60>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617EA20>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C537194F0>
Sweep_15 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617CCB0>
Sweep_16 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589309B0>
Sweep_17 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53653770>
Sweep_18 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F82C30>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F80350>
File added




df length: 540
 dict length: 540




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M20\M20_MM_A1_C05.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.81s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B5202F0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53653770>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1077D0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58956540>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C540274A0>
Sweep_67 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58959BE0>
Sweep_68 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53745A30>
Sweep_69 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0EEC60>
Sweep_70 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617EDB0>
Sweep_71 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BC1CCE0>
Sweep_72 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FF0E0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626CE60>
File added




df length: 552
 dict length: 552




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M20\M20_MM_A1_C07.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.06it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.66it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C051220>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5895B3B0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C536793D0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F467B0>
Sweep_15 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA21880>
Sweep_16 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B36F230>
Sweep_17 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5602E660>
Sweep_18 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533BFE00>
Sweep_19 <spikeparam.patch.fit.fit.Spike object at 0x0000014C55799B20>
File added




df length: 565
 dict length: 565




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M20\M20_SA_A1_C01.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.74it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.94it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.09it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.08it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]

Fitting failed for sweep Sweep_62: All fits failed.

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]

Fitting failed for sweep Sweep_63: All fits failed.

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.92it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.76it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.38it/s]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F1640>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53A5F0E0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B69A630>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1911F0>
Sweep_5 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F4A930>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B521460>
Sweep_64 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FF6E0>
Sweep_66 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FF320>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C563A54C0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F82F60>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C031AF0>
File added




df length: 603
 dict length: 603




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M20\M20_SA_A1_C02.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████| 105/105 [00:04<00:00, 26.04it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.57it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.70it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.52it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.50it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:03<00:00,  4.57it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:03<00:00,  4.40it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.06it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  3.90it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5634F260>
Sweep_1 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58931F40>
Sweep_2 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F00E0>
Sweep_3 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58954920>
Sweep_4 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53678CB0>
Sweep_5 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E6A50>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384F020>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58959BE0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58956B40>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F404A0>
No metadata found for file: M20_SA_A1_C02
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M20\M20_SA_A1_C03.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.00it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.07it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  3.70it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.00it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A0530>
Sweep_36 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53678CB0>
Sweep_37 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA21F40>
Sweep_38 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58959BE0>
Sweep_39 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBFEF0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C7C20>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C052B10>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5602FF80>
File added




df length: 666
 dict length: 666




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M20\M20_SA_A1_C04.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B105BB0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F4A930>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617E360>
Sweep_15 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617EDB0>
Sweep_16 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FF0B0>
Sweep_17 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0ECFE0>
Sweep_18 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A735460>
Sweep_19 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0EEC60>
Sweep_52 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F43BF0>
Sweep_53 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E55B0>
No metadata found for file: M20_SA_A1_C04
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M20\M20_SA_A1_C05.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.02it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.63it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.65it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.05it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.05it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0EEC60>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C537185C0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F80860>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56284440>
Sweep_15 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58931F40>
Sweep_16 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C053A70>
Sweep_17 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5634F260>
Sweep_18 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B104BC0>
Sweep_19 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B107F20>
Sweep_34 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B105D30>
Sweep_35 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617C3E0>
Sweep_36 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F43BF0>
Sweep_37 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B106600>
Sweep_38 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56287C50>
Sweep_39 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F40AA0>
Sweep_40 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F810A0>
Sweep_41 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5634D730>
Sweep_42 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56285790>
Sweep_43 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53679C70>
No metadata found for file: M20_SA_A1_C05
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M20\M20_SA_A1_C06.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.24it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.38it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.34it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.39it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.55it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C536793D0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617D100>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53679340>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5634D730>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C563A5340>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5634C4A0>
File added




df length: 719
 dict length: 719




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M20\M20_SA_A1_C07.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.27it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.16it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  3.81it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_50 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E54C0>
Sweep_52 <spikeparam.patch.fit.fit.Spike object at 0x0000014C537185C0>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626C4A0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B19D760>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A737DA0>
File added




df length: 745
 dict length: 745




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M20\M20_SA_A1_C08.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.05it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.05it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.06it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.58it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.01it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.05it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C053DD0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA21F40>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384FF80>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A7366C0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53678CB0>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4ADE0>
Sweep_30 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5602E660>
Sweep_31 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B104230>
Sweep_5 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56284C80>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5EBA0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562878C0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5EA50>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0CDAF0>
File added




df length: 767
 dict length: 767




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M20\M20_SA_A1_C09.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.39it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  4.16it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.20it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.15it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.03it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.04it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  3.79it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  4.18it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  3.38it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.87it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:03<00:00,  4.64it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1921B0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A7366C0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C550FF4A0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617EA20>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5634EAE0>
Sweep_15 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E6F30>
Sweep_16 <spikeparam.patch.fit.fit.Spike object at 0x0000014C538236E0>
Sweep_17 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626F170>
Sweep_18 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626E8A0>
Sweep_19 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617E780>
Sweep_72 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A2DE0>
Sweep_73 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E6E70>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C563A5340>
File added




df length: 919
 dict length: 919











concat df length: 11087
concat dict length: 11087







C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M21\M21_MM_A1_C01.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.10it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:04<00:00,  5.99it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 29/29 [00:07<00:00,  3.68it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:07<00:00,  3.11it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.44s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:04<00:00,  2.02it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0EE9F0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5893AF30>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A7366C0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53718200>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534BBCE0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F4A360>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58936570>
File added




df length: 109
 dict length: 109




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M21\M21_MM_A1_C02.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54D7DC70>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56285DF0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559C2630>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4A300>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4A180>
Sweep_15 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384D2B0>
Sweep_16 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E7170>
Sweep_17 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58931A90>
File added




df length: 117
 dict length: 117




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M21\M21_MM_A1_C04.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.04it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 26/26 [00:03<00:00,  7.14it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:04<00:00,  4.53it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.96it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 34/34 [00:04<00:00,  7.31it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 34/34 [00:04<00:00,  7.16it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 32/32 [00:04<00:00,  7.04it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 32/32 [00:04<00:00,  7.30it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 37/37 [00:04<00:00,  8.49it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 41/41 [00:04<00:00,  9.84it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 34/34 [00:04<00:00,  8.45it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 33/33 [00:04<00:00,  7.61it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C540274A0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617C3E0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F80860>
Sweep_15 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617F4D0>
Sweep_16 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E7170>
Sweep_17 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C7CE0>
Sweep_18 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5A7366C0>
Sweep_19 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589321B0>
Sweep_20 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F5E2D0>
Sweep_21 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F46ED0>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0CE8A0>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F45F70>
File added




df length: 463
 dict length: 463




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M21\M21_MM_A1_C05.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.83s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C7CE0>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53651730>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562868D0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F484D0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C534BBCE0>
Sweep_15 <spikeparam.patch.fit.fit.Spike object at 0x0000014C537466C0>
Sweep_16 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589322D0>
Sweep_17 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5634F260>
Sweep_18 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E6D80>
Sweep_19 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617DAF0>
Sweep_20 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617F4D0>
Sweep_21 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562879E0>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384D2B0>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0ECFE0>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5367A5A0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589355B0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F431D0>
No metadata found for file: M21_MM_A1_C05
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M21\M21_MM_A1_C06.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.05it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  3.54it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 27/27 [00:03<00:00,  7.62it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 30/30 [00:03<00:00,  8.60it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 34/34 [00:03<00:00,  9.21it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 38/38 [00:03<00:00,  9.93it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 32/32 [00:03<00:00,  8.26it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.77it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_15 <spikeparam.patch.fit.fit.Spike object at 0x0000014C559C2630>
Sweep_16 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BDAF0>
Sweep_17 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589322D0>
Sweep_18 <spikeparam.patch.fit.fit.Spike object at 0x0000014C54D7DC70>
Sweep_19 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0ECFE0>
Sweep_20 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5384F020>
Sweep_21 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562868D0>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B4F0920>
File added




df length: 644
 dict length: 644




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M21\M21_MM_A1_C07.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 31/31 [00:04<00:00,  7.71it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 36/36 [00:04<00:00,  8.74it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 39/39 [00:04<00:00,  9.13it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 39/39 [00:04<00:00,  9.20it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.46it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.65it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:04<00:00,  4.46it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 27/27 [00:04<00:00,  6.49it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C563A5220>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA23E00>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C537466C0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C56286A20>
Sweep_15 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E6270>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BA21880>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F60EC0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58957C50>
File added




df length: 840
 dict length: 840




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M21\M21_SA_A1_C01.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.47it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  3.90it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.85it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:04<00:00,  5.38it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:04<00:00,  5.68it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 29/29 [00:04<00:00,  6.46it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 30/30 [00:04<00:00,  6.79it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 31/31 [00:04<00:00,  7.15it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 33/33 [00:04<00:00,  7.48it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 34/34 [00:04<00:00,  7.73it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5367A5A0>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5895AFC0>
Sweep_15 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5602C3B0>
Sweep_16 <spikeparam.patch.fit.fit.Spike object at 0x0000014C536791F0>
Sweep_17 <spikeparam.patch.fit.fit.Spike object at 0x0000014C589322D0>
Sweep_18 <spikeparam.patch.fit.fit.Spike object at 0x0000014C563A5220>
Sweep_19 <spikeparam.patch.fit.fit.Spike object at 0x0000014C563A4E60>
Sweep_20 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626FAD0>
Sweep_21 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B520DD0>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5367ADB0>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F6A750>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4AA80>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BC1C290>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626F6B0>
Sweep_30 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBE270>
File added




df length: 1090
 dict length: 1090




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M21\M21_SA_A1_C02.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.92it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.96it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 33/33 [00:03<00:00,  8.37it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.01it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  3.59it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 34/34 [00:03<00:00,  8.71it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:04<00:00,  6.06it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 29/29 [00:04<00:00,  6.82it/s]

Sweep_0 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0CEFC0>
Sweep_1 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B104CE0>
Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C7260>
Sweep_2 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0A2D80>
Sweep_3 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1FF320>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58960860>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F80DA0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1904D0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F40BC0>
No metadata found for file: M21_SA_A1_C02
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M21\M21_SA_A1_C03.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.02s/it]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.61it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.96it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.65it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  3.79it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:04<00:00,  4.22it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_18 <spikeparam.patch.fit.fit.Spike object at 0x0000014C562870E0>
Sweep_19 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58F4A360>
Sweep_20 <spikeparam.patch.fit.fit.Spike object at 0x0000014C560A4230>
Sweep_21 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5895F560>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F45B80>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5BDC3FB0>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B0CDF70>
File added




df length: 1139
 dict length: 1139




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M21\M21_SA_A1_C04.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.72s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:03<00:00,  5.36it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 36/36 [00:04<00:00,  8.62it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 29/29 [00:04<00:00,  6.78it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 37/37 [00:04<00:00,  8.61it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 38/38 [00:04<00:00,  8.88it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 30/30 [00:04<00:00,  6.78it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 32/32 [00:04<00:00,  7.18it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 38/38 [00:04<00:00,  8.27it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 40/40 [00:04<00:00,  8.70it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 34/34 [00:04<00:00,  7.64it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617F830>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53651D60>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F404A0>
Sweep_15 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B522B40>
Sweep_16 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533A17F0>
Sweep_17 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5C0ED880>
Sweep_18 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BD880>
Sweep_19 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B1BC0B0>
Sweep_20 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5895B080>
Sweep_21 <spikeparam.patch.fit.fit.Spike object at 0x0000014C533A2A50>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F40BC0>
No metadata found for file: M21_SA_A1_C04
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M21\M21_SA_A1_C05.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.66it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 36/36 [00:04<00:00,  8.56it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 31/31 [00:04<00:00,  7.18it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 29/29 [00:04<00:00,  6.72it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 30/30 [00:04<00:00,  6.69it/s]

Sweep_4 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B523B60>
Sweep_5 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F494C0>
Sweep_6 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5AFBCD10>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5617EFC0>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58956450>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C58931A90>
File added




df length: 1273
 dict length: 1273




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M21\M21_SA_A1_C06.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:04<00:00,  5.74it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 36/36 [00:04<00:00,  8.06it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 38/38 [00:04<00:00,  8.55it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.01it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.29it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C552C7260>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5B2E42C0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F80410>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5895F560>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5634D730>
File added




df length: 1380
 dict length: 1380




C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\M21\M21_SA_A1_C07.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.39it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:04<00:00,  4.38it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 22/22 [00:04<00:00,  5.09it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:04<00:00,  5.68it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.98it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F83350>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5602C3B0>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5626D370>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C59F4AA80>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C557BE090>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53F80410>
File added




df length: 1463
 dict length: 1463











concat df length: 12550
concat dict length: 12550







Data frame saved to C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\allMonkey_df.pkl
Dictionary saved to C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\combined_dict.pkl

In [47]:
allMonkey_df.head()

,ramp_amp,inflection_time,inflection_amp,peak_amp,peak_width,peak_sharpness,exp_lambda,exp_const,isi,r_squared_ramp,...,Spike_#,Spike_ID,file_name,dendriticType,SomaLayerLoc,brainOrigin,Weight,Sex,Age,Species
0,2.612488,0.45,-45.858766,15.164185,0.50,6.445313,6.970228,-56.733916,88.40,0.996142,...,0,M03f0SwSweep_10Sp0,M03_JS_A1_C01,A,3.0,PFC,6.3,F,9.96,Macaca fascicularis
1,1.832248,0.60,-38.827516,11.984253,0.55,3.929138,5.981717,-53.646425,56.35,0.950116,...,1,M03f0SwSweep_10Sp1,M03_JS_A1_C01,A,3.0,PFC,6.3,F,9.96,Macaca fascicularis
2,1.725643,0.60,-38.571168,11.453247,0.55,3.533936,6.194347,-53.275150,56.20,0.969743,...,2,M03f0SwSweep_10Sp2,M03_JS_A1_C01,A,3.0,PFC,6.3,F,9.96,Macaca fascicularis
3,1.762723,0.60,-39.727784,11.669922,0.60,3.567505,5.819483,-53.277108,NaN,0.975530,...,3,M03f0SwSweep_10Sp3,M03_JS_A1_C01,A,3.0,PFC,6.3,F,9.96,Macaca fascicularis
4,2.534657,0.50,-46.746827,15.621949,0.50,6.254578,7.821646,-56.351455,90.70,0.982983,...,0,M03f0SwSweep_11Sp0,M03_JS_A1_C01,A,3.0,PFC,6.3,F,9.96,Macaca fascicularis

In [31]:
save_dataframe_to_pickle(allMonkey_df, r"C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\allMonkey_df.pkl")

Data frame saved to C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\allMonkey_df.pkl

**OLD CODE:**

In [14]:
file_path = [r"C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\Test"]
test_df, test_dict = create_allMonkey_data(file_path)
test_df.head()

Creating data frame and dictionary
C:\Users\david\Documents\Voytek Research\spike_proj\primate Dataset\Test\M05_JS_A1_C03.nwb

C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:06<00:00,  2.13it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:06<00:00,  1.77it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:07<00:00,  2.00it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:06<00:00,  2.05it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:07<00:00,  2.27it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:04<00:00,  1.63s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:05<00:00,  1.86it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:06<00:00,  2.20it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:05<00:00,  1.87it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:06<00:00,  2.01it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:06<00:00,  2.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:06<00:00,  2.18it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:06<00:00,  2.27it/s]
C:\Users\david\Documents\Voytek Research\spikeparam\datasets\primate_dataset\..\..\..\spikeparam\spikeparam\patch\fit\fit.py:242: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:04<00:00,  2.42s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:05<00:00,  1.03it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:06<00:00,  2.37it/s]

Sweep_10 <spikeparam.patch.fit.fit.Spike object at 0x0000014C530AD670>
Sweep_11 <spikeparam.patch.fit.fit.Spike object at 0x0000014C51D06180>
Sweep_12 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53053DD0>
Sweep_13 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52F79F70>
Sweep_14 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5302A300>
Sweep_22 <spikeparam.patch.fit.fit.Spike object at 0x0000014C2DFC2390>
Sweep_23 <spikeparam.patch.fit.fit.Spike object at 0x0000014C530E0230>
Sweep_24 <spikeparam.patch.fit.fit.Spike object at 0x0000014C516DA3C0>
Sweep_25 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52E735F0>
Sweep_26 <spikeparam.patch.fit.fit.Spike object at 0x0000014C0F12D8B0>
Sweep_27 <spikeparam.patch.fit.fit.Spike object at 0x0000014C53052030>
Sweep_28 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52F8A630>
Sweep_29 <spikeparam.patch.fit.fit.Spike object at 0x0000014C52F8B4D0>
Sweep_7 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313C350>
Sweep_8 <spikeparam.patch.fit.fit.Spike object at 0x0000014C51CBA1E0>
Sweep_9 <spikeparam.patch.fit.fit.Spike object at 0x0000014C5313C290>
File added




df length: 186
 dict length: 186











concat df length: 186
concat dict length: 186

,ramp_amp,inflection_time,inflection_amp,peak_amp,peak_width,peak_sharpness,exp_lambda,exp_const,isi,r_squared_ramp,r_squared_exp,Sweep_#,Spike_#,Spike_ID,file_name
0,3.007244,0.55,-42.572022,35.583497,0.85,4.592896,2.412379,-51.655136,80.95,0.953042,0.992757,Sweep_10,0,Testf0SwSweep_10Sp0,M05_JS_A1_C03
1,2.759432,0.70,-37.170411,33.142091,1.00,2.136231,1.831402,-52.007353,68.75,0.952943,0.996262,Sweep_10,1,Testf0SwSweep_10Sp1,M05_JS_A1_C03
2,2.428557,0.70,-36.895753,32.653809,1.00,1.403809,1.822783,-51.590403,77.10,0.909808,0.997062,Sweep_10,2,Testf0SwSweep_10Sp2,M05_JS_A1_C03
3,2.990264,0.75,-36.132813,32.287598,1.00,1.434326,1.759038,-52.521420,78.40,0.953441,0.997450,Sweep_10,3,Testf0SwSweep_10Sp3,M05_JS_A1_C03
4,3.344084,0.70,-36.102296,32.135010,0.95,1.525879,1.818987,-52.357826,85.60,0.955121,0.996327,Sweep_10,4,Testf0SwSweep_10Sp4,M05_JS_A1_C03

In [12]:
file_paths = get_file_paths(r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03")
M03_df = monkey_df(file_paths, 2)

save_dataframe_to_pickle(M03_df, r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03_df.pkl")

C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_JS_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:04<00:00,  2.11it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 42/42 [00:04<00:00,  9.62it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 43/43 [00:04<00:00,  9.69it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 59/59 [00:04<00:00, 13.10it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 67/67 [00:04<00:00, 14.38it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.44s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.75it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_54
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_JS_A1_C03.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 46/46 [00:04<00:00, 10.34it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 108/108 [00:04<00:00, 23.94it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 128/128 [00:04<00:00, 28.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 150/150 [00:04<00:00, 32.90it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 166/166 [00:04<00:00, 34.97it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.48s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_38
Sweep_39
Sweep_40
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_JS_A1_C04.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 69/69 [00:04<00:00, 15.20it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 80/80 [00:04<00:00, 17.69it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 89/89 [00:04<00:00, 19.36it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 98/98 [00:04<00:00, 20.88it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 108/108 [00:04<00:00, 23.15it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.64it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 37/37 [00:04<00:00,  8.29it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 54/54 [00:04<00:00, 12.01it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.96s/it]

Sweep_10
Sweep_101
Sweep_102
Sweep_103
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_7
Sweep_8
Sweep_9
Sweep_98
Sweep_99
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_JS_A1_C06.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.37s/it]

Fitting failed for sweep Sweep_1: All fits failed.

Spike: 100%|███████████████████████████████████████████████████████████████████████████| 69/69 [00:04<00:00, 15.09it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 84/84 [00:04<00:00, 18.81it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 95/95 [00:04<00:00, 21.20it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 107/107 [00:04<00:00, 22.74it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 117/117 [00:04<00:00, 25.77it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.07it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 36/36 [00:04<00:00,  8.11it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 58/58 [00:04<00:00, 12.91it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_36
Sweep_39
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_JS_A1_C10.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 59/59 [00:04<00:00, 13.20it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 115/115 [00:04<00:00, 25.39it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13
Sweep_14
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_JS_A1_C14.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.81s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12
Sweep_13
Sweep_14
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_JS_A1_C18.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 34/34 [00:04<00:00,  7.40it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 38/38 [00:04<00:00,  8.34it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 40/40 [00:04<00:00,  8.90it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 42/42 [00:04<00:00,  9.01it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 41/41 [00:04<00:00,  9.05it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.54it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:04<00:00,  5.31it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 30/30 [00:04<00:00,  6.63it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_59
Sweep_60
Sweep_61
Sweep_62
Sweep_63
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_JS_A1_C19.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 49/49 [00:04<00:00, 10.76it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 40/40 [00:04<00:00,  9.01it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 27/27 [00:04<00:00,  6.10it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 26/26 [00:04<00:00,  5.77it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.50it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.44s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.43it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.95it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 34/34 [00:04<00:00,  7.46it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_61
Sweep_62
Sweep_63
Sweep_64
Sweep_65
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_JS_A1_C20.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 38/38 [00:04<00:00,  8.25it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 42/42 [00:04<00:00,  9.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 46/46 [00:04<00:00, 10.46it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 49/49 [00:04<00:00, 10.91it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 34/34 [00:04<00:00,  7.51it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.18it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:04<00:00,  5.10it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 31/31 [00:04<00:00,  6.74it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_MW_A1_C03.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.15it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.48it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.54it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:04<00:00,  3.95it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:04<00:00,  4.17it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.75it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.35it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_MW_A1_C04.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.53it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.23it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:04<00:00,  3.89it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.87it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:06<00:00,  3.49it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.91s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.96s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.06it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_45
Sweep_46
Sweep_50
Sweep_51
Sweep_52
Sweep_53
Sweep_54
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_MW_A1_C06.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.53it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:04<00:00,  4.30it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:05<00:00,  3.64it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:06<00:00,  3.64it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:06<00:00,  3.80it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.06it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.51it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_MW_A1_C08.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  3.38it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:05<00:00,  2.78it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:06<00:00,  2.69it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:06<00:00,  3.41it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:06<00:00,  3.96it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.48s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 1/1 [1:33:49<00:00, 5629.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:01<00:00,  3.45it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.84it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_7
Sweep_70
Sweep_72
Sweep_74
Sweep_75
Sweep_76
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_MW_A1_C09.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.85s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.09it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.56it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.36it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.93s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.58s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_52
Sweep_53
Sweep_55
Sweep_56
Sweep_57
Sweep_58
Sweep_59
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_MW_A1_C10.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13
Sweep_14
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_MW_A1_C11.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.48it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.42it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.58it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:04<00:00,  4.02it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.10it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_105
Sweep_107
Sweep_108
Sweep_109
Sweep_11
Sweep_110
Sweep_111
Sweep_112
Sweep_113
Sweep_114
Sweep_115
Sweep_116
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_MW_A1_C15.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.70it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.08it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.82s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.30it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.85s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.30it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  3.55it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.57it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:04<00:00,  1.89it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_0
Sweep_10
Sweep_11
Sweep_113
Sweep_118
Sweep_119
Sweep_12
Sweep_120
Sweep_121
Sweep_122
Sweep_13
Sweep_14
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_MW_A1_C16.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.44s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.72it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  3.27it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  2.95it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.24it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  3.73it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:04<00:00,  1.48it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_SM_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.23s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_SM_A1_C04.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 100/100 [00:04<00:00, 21.26it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 112/112 [00:04<00:00, 23.53it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13
Sweep_14
Sweep_51
Sweep_52
Sweep_53
Sweep_54
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_SM_A1_C05.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]

Sweep_102
Sweep_103
Sweep_104
Sweep_12
Sweep_13
Sweep_14
Sweep_97
Sweep_99
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_SM_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_14
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_SM_A1_C09.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_SM_A1_C14.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11
Sweep_12
Sweep_13
Sweep_14
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_SM_A1_C15.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12
Sweep_13
Sweep_14
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M03\M03_SM_A1_C16.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
Spike: 100%|████████████████████████████████████████████████████████████████████████████| 2/2 [16:00<00:00, 480.17s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.44s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.45s/it]

Sweep_10
Sweep_11
Sweep_115
Sweep_116
Sweep_117
Sweep_118
Sweep_119
Sweep_12
Sweep_120
Sweep_121
Sweep_122
Sweep_123
Sweep_124
Sweep_125
Sweep_126
Sweep_13
Sweep_14
Sweep_8
Sweep_9

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

In [14]:
M03_df.head()

,ramp_amp,inflection_time,inflection_amp,peak_amp,peak_width,peak_sharpness,exp_lambda,exp_const,isi,r_squared_ramp,r_squared_exp,Sweep_#,file_name,dendriticType,SomaLayerLoc,brainOrigin,Weight,Sex,Age,Species
0,2.612488,0.45,-45.858766,15.164185,0.50,6.445313,6.970228,-56.733916,19.45,0.996142,0.739826,Sweep_10,M03_JS_A1_C01,A,3,PFC,6.3,F,9.96,Macaca fascicularis
1,2.116406,0.55,-42.507936,13.681031,0.50,5.018616,7.193608,-54.574427,20.15,0.998421,0.688264,Sweep_10,M03_JS_A1_C01,A,3,PFC,6.3,F,9.96,Macaca fascicularis
2,2.044173,0.60,-41.433717,12.530518,0.55,3.962708,6.693805,-54.071263,24.25,0.984082,0.725384,Sweep_10,M03_JS_A1_C01,A,3,PFC,6.3,F,9.96,Macaca fascicularis
3,1.850421,0.60,-38.183595,11.666870,0.55,3.634644,6.344601,-53.386135,24.55,0.994742,0.774003,Sweep_10,M03_JS_A1_C01,A,3,PFC,6.3,F,9.96,Macaca fascicularis
4,1.832248,0.60,-38.827516,11.984253,0.55,3.929138,5.981717,-53.646425,26.60,0.950116,0.831859,Sweep_10,M03_JS_A1_C01,A,3,PFC,6.3,F,9.96,Macaca fascicularis

In [15]:
M03_df.tail()

,ramp_amp,inflection_time,inflection_amp,peak_amp,peak_width,peak_sharpness,exp_lambda,exp_const,isi,r_squared_ramp,r_squared_exp,Sweep_#,file_name,dendriticType,SomaLayerLoc,brainOrigin,Weight,Sex,Age,Species
0,3.532513,0.50,-41.070558,34.521485,0.60,9.402466,5.926023,-41.947774,NaN,0.990231,0.869755,Sweep_13,M03_SM_A1_C16,NA,NA,PFC,6.3,F,9.96,Macaca fascicularis
0,3.611996,0.50,-41.882325,35.430909,0.55,8.175659,7.009688,-41.227819,6.55,0.979050,0.715464,Sweep_14,M03_SM_A1_C16,NA,NA,PFC,6.3,F,9.96,Macaca fascicularis
1,2.420113,1.15,-35.577393,14.031983,0.90,1.815796,3.344942,-40.903731,NaN,0.992774,0.984037,Sweep_14,M03_SM_A1_C16,NA,NA,PFC,6.3,F,9.96,Macaca fascicularis
0,3.556652,0.60,-29.888917,27.313233,0.70,3.521729,3.635624,-45.651009,NaN,0.986556,0.996845,Sweep_8,M03_SM_A1_C16,NA,NA,PFC,6.3,F,9.96,Macaca fascicularis
0,2.805506,0.55,-37.921143,33.331300,0.60,6.616211,4.633209,-44.813706,NaN,0.988634,0.978401,Sweep_9,M03_SM_A1_C16,NA,NA,PFC,6.3,F,9.96,Macaca fascicularis

**M04**

In [60]:
file_paths2 = get_file_paths(r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04")
M04_df = monkey_df(file_paths2, 28)

save_dataframe_to_pickle(M04_df, r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04_df.pkl")

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C01.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 82/82 [00:03<00:00, 25.12it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 80/80 [00:03<00:00, 23.38it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 104/104 [00:03<00:00, 30.74it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.66it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.62it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:03<00:00,  6.94it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.70it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 30/30 [00:03<00:00,  8.32it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.99it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C03.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.06it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.08it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 137/137 [00:03<00:00, 38.77it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 146/146 [00:03<00:00, 40.56it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.44s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_46
Sweep_48
Sweep_50
Sweep_51
Sweep_53
Sweep_54
Sweep_55
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C04.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.75it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  3.91it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.78it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.54it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.46it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.82it/s]

Sweep_0
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C05.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  3.97it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.04it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 26/26 [00:03<00:00,  7.35it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 29/29 [00:03<00:00,  7.86it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.11it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_40
Sweep_41
Sweep_42
Sweep_43
Sweep_44
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C06.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.04it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  4.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.52it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.73it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:04<00:00,  2.70it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.11it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.67it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.77it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.90it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_4
Sweep_5
Sweep_6
Sweep_7
Sweep_71
Sweep_73
Sweep_74
Sweep_75
Sweep_76
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C07.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.94it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:04<00:00,  4.62it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.22it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.23it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.98it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.64it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  3.29it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.44it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.00it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  3.70it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 31/31 [00:05<00:00,  5.99it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 42/42 [00:04<00:00,  8.57it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_3
Sweep_4
Sweep_5
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C08.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 44/44 [00:03<00:00, 11.97it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 52/52 [00:05<00:00,  9.43it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 57/57 [00:04<00:00, 12.34it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 65/65 [00:04<00:00, 13.75it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 70/70 [00:04<00:00, 14.18it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.62it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 30/30 [00:03<00:00,  9.11it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 36/36 [00:05<00:00,  6.51it/s]

Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_21
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_3
Sweep_6
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C09.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]

Fitting failed for sweep Sweep_1: All fits failed.

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.12it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]

Fitting failed for sweep Sweep_6: All fits failed.

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.48s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_75
Sweep_77
Sweep_78
Sweep_79
Sweep_80
Sweep_81
Sweep_82
Sweep_83
Sweep_84
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C10.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.12it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.48s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13
Sweep_14
Sweep_172
Sweep_173
Sweep_174
Sweep_175
Sweep_176
Sweep_177
Sweep_178
Sweep_179
Sweep_180
Sweep_181
Sweep_182
Sweep_183
Sweep_184
Sweep_185
Sweep_186
Sweep_187
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C12.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:03<00:00,  5.52it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  6.09it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:03<00:00,  7.10it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:03<00:00,  7.52it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 26/26 [00:03<00:00,  7.61it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.10it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  3.95it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.31it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_6
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C13.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.17it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  3.72it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.15it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:03<00:00,  4.56it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  3.55it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.80s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.08it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.69it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.00it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_4
Sweep_5
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C14.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:05<00:00,  3.54it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 22/22 [00:06<00:00,  3.62it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:05<00:00,  4.33it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 26/26 [00:05<00:00,  4.73it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 28/28 [00:05<00:00,  5.10it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.12it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.83it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:05<00:00,  2.60it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_6
Sweep_7
Sweep_77
Sweep_8
Sweep_81
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C15.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.05s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:06<00:00,  3.80it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 31/31 [00:06<00:00,  4.64it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 33/33 [00:07<00:00,  4.61it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 36/36 [00:07<00:00,  4.95it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 40/40 [00:07<00:00,  5.63it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:06<00:00,  2.42it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.04it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_6
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_JS_A1_C16.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.06it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.44s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_3
Sweep_4
Sweep_41
Sweep_42
Sweep_44
Sweep_46
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_MJ_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_MW_A1_C01.nwb

Spike: 100%|███████████████████████████████████████████████████████████████████████████| 35/35 [00:03<00:00, 10.34it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 41/41 [00:03<00:00, 12.10it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 44/44 [00:03<00:00, 12.73it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 48/48 [00:03<00:00, 13.59it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 51/51 [00:03<00:00, 13.06it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  3.75it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:04<00:00,  5.55it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 29/29 [00:04<00:00,  6.33it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_MW_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.47it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.75it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.05it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.83it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.63it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  3.78it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:04<00:00,  3.88it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.57it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.92it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_19
Sweep_20
Sweep_21
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_30
Sweep_31
Sweep_32
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_MW_A1_C03.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.14it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 64/64 [00:05<00:00, 11.80it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]

Sweep_100
Sweep_101
Sweep_102
Sweep_13
Sweep_14
Sweep_87
Sweep_89
Sweep_90
Sweep_91
Sweep_92
Sweep_93
Sweep_94
Sweep_95
Sweep_96
Sweep_97
Sweep_98
Sweep_99
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_MW_A1_C06.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.78s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_41
Sweep_44
Sweep_45
Sweep_46
Sweep_47
Sweep_48
Sweep_49
Sweep_50
Sweep_51
Sweep_65
Sweep_66
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_MW_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_14
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_MW_A1_C08.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.83it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.61it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:05<00:00,  3.48it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.09it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:04<00:00,  4.86it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.44s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.12it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_57
Sweep_62
Sweep_63
Sweep_64
Sweep_65
Sweep_66
Sweep_67
Sweep_68
Sweep_69
Sweep_70
Sweep_71
Sweep_72
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_MW_A1_C09.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.83it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  3.99it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  4.07it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.74it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.98it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.08it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.76it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_123
Sweep_125
Sweep_126
Sweep_129
Sweep_13
Sweep_131
Sweep_134
Sweep_138
Sweep_139
Sweep_14
Sweep_140
Sweep_141
Sweep_142
Sweep_143
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_MW_A1_C10.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_149
Sweep_150
Sweep_151
Sweep_152
Sweep_153
Sweep_154
Sweep_155
Sweep_156
Sweep_157
Sweep_158
Sweep_159
Sweep_160
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_30
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_SM_A1_C01.nwb

Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.66it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 30/30 [00:03<00:00,  9.10it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:03<00:00,  5.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.84it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:03<00:00,  4.81it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:03<00:00,  5.80it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  3.91it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 33/33 [00:03<00:00,  8.56it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 37/37 [00:03<00:00,  9.50it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 40/40 [00:04<00:00, 10.00it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 33/33 [00:03<00:00,  8.39it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 33/33 [00:03<00:00,  8.28it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:03<00:00,  4.57it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 26/26 [00:04<00:00,  6.43it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.96it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_3
Sweep_4
Sweep_5
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_SM_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.98s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.05it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_22
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_30
Sweep_32
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_SM_A1_C03.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 268/268 [00:04<00:00, 60.29it/s]
Spike: 100%|██████████████████████████████████████████████████████████████████████| 3553/3553 [00:27<00:00, 127.82it/s]

Fitting failed for sweep Sweep_13: could not broadcast input array from shape (18,) into shape (20,)

Spike: 100%|██████████████████████████████████████████████████████████████████████| 5972/5972 [00:50<00:00, 118.04it/s]

Fitting failed for sweep Sweep_14: could not broadcast input array from shape (9,) into shape (20,)
Sweep_12
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_SM_A1_C04.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:02<00:00,  4.48it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:03<00:00,  5.73it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 62/62 [00:03<00:00, 17.84it/s]

Fitting failed for sweep Sweep_10: could not broadcast input array from shape (19,) into shape (20,)

Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:04<00:00,  5.31it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.64it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  4.31it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  4.08it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 22/22 [00:04<00:00,  5.33it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.73it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:04<00:00,  4.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 41/41 [00:04<00:00,  9.22it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 48/48 [00:04<00:00, 10.86it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 56/56 [00:04<00:00, 12.53it/s]

Sweep_0
Sweep_1
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_3
Sweep_4
Sweep_5
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_SM_A1_C06.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.65it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  3.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.11it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.28it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.06it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.02it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.96it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.65it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.54it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.90it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.77it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_3
Sweep_4
Sweep_5
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_SM_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_85
Sweep_86
Sweep_88
Sweep_89
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_SM_A1_C08.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 59/59 [00:03<00:00, 17.70it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 83/83 [00:06<00:00, 12.11it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 101/101 [00:06<00:00, 15.00it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 108/108 [00:06<00:00, 16.62it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 68/68 [00:06<00:00, 10.65it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]

Fitting failed for sweep Sweep_25: Length of values (2) does not match length of index (1)

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]

Fitting failed for sweep Sweep_32: Length of values (2) does not match length of index (1)

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.11it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.74it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.81it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:03<00:00,  7.29it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 35/35 [00:03<00:00, 10.47it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 46/46 [00:03<00:00, 13.31it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_18
Sweep_19
Sweep_2
Sweep_20
Sweep_21
Sweep_22
Sweep_23
Sweep_24
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_3
Sweep_30
Sweep_31
Sweep_33
Sweep_34
Sweep_4
Sweep_5
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_SM_A1_C09.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.48s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]

Sweep_0
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_44
Sweep_45
Sweep_46
Sweep_47
Sweep_48
Sweep_49
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_SM_A1_C10.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_3
Sweep_30
Sweep_31
Sweep_32
Sweep_33
Sweep_34
Sweep_35
Sweep_36
Sweep_37
Sweep_38
Sweep_39
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_SM_A1_C11.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.34it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 54/54 [00:03<00:00, 16.48it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 62/62 [00:03<00:00, 18.54it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 70/70 [00:03<00:00, 20.66it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 79/79 [00:03<00:00, 22.67it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 88/88 [00:03<00:00, 23.80it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:03<00:00,  5.00it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.81it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.72it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.11it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:03<00:00,  5.20it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 22/22 [00:03<00:00,  6.66it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 35/35 [00:03<00:00,  9.87it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 43/43 [00:03<00:00, 11.88it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_18
Sweep_19
Sweep_2
Sweep_20
Sweep_21
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_3
Sweep_30
Sweep_31
Sweep_32
Sweep_33
Sweep_34
Sweep_4
Sweep_5
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04\M04_SM_A1_C13.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]

Sweep_13
Sweep_14
Sweep_200
Sweep_205
Sweep_206
file added

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

In [61]:
M04_df.head()

,ramp_amp,inflection_time,inflection_amp,peak_amp,peak_width,peak_sharpness,exp_lambda,exp_const,isi,r_squared_ramp,r_squared_exp,Sweep_#,file_name,dendriticType,SomaLayerLoc,brainOrigin,Weight,Sex,Age,Species
0,4.387923,0.45,-40.768434,24.624634,0.40,9.146118,7.228195,-61.191912,3141.0,0.988773,0.670360,Sweep_10,M04_JS_A1_C01,NA,NA,PFC,6.5,F,11.58,Macaca fascicularis
1,4.833480,0.40,-41.177369,25.955201,0.40,10.462952,8.280124,-59.228859,NaN,0.990291,0.534707,Sweep_10,M04_JS_A1_C01,NA,NA,PFC,6.5,F,11.58,Macaca fascicularis
0,3.545225,0.40,-40.933228,24.578858,0.40,10.218811,7.681916,-60.576132,13.8,0.985757,0.618962,Sweep_11,M04_JS_A1_C01,NA,NA,PFC,6.5,F,11.58,Macaca fascicularis
1,3.574366,0.45,-38.961793,22.283936,0.45,8.531189,6.139406,-60.119660,15.2,0.983322,0.773941,Sweep_11,M04_JS_A1_C01,NA,NA,PFC,6.5,F,11.58,Macaca fascicularis
2,4.571855,0.45,-35.510255,20.413208,0.40,6.814575,5.891516,-59.775511,13.5,0.987037,0.753234,Sweep_11,M04_JS_A1_C01,NA,NA,PFC,6.5,F,11.58,Macaca fascicularis

In [62]:
M04_df = load_dataframe_from_pickle(r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M04_df.pkl")

M04_df.tail()

,ramp_amp,inflection_time,inflection_amp,peak_amp,peak_width,peak_sharpness,exp_lambda,exp_const,isi,r_squared_ramp,r_squared_exp,Sweep_#,file_name,dendriticType,SomaLayerLoc,brainOrigin,Weight,Sex,Age,Species
0,0.672305,0.80,-41.328373,41.478031,0.95,2.859497,2.601819,-48.453468,NaN,0.865878,0.998288,Sweep_13,M04_SM_A1_C13,NA,NA,PFC,6.5,F,11.58,Macaca fascicularis
0,0.870738,0.80,-42.854252,41.923588,0.90,3.094482,2.641498,-48.066803,NaN,0.978995,0.998324,Sweep_14,M04_SM_A1_C13,NA,NA,PFC,6.5,F,11.58,Macaca fascicularis
0,6.746175,0.75,-47.212162,41.520756,0.85,3.582764,2.447608,-56.480353,NaN,0.998580,0.991162,Sweep_200,M04_SM_A1_C13,NA,NA,PFC,6.5,F,11.58,Macaca fascicularis
0,7.036114,0.75,-46.192875,42.369144,0.85,3.350830,2.516052,-55.528810,NaN,0.998975,0.991049,Sweep_205,M04_SM_A1_C13,NA,NA,PFC,6.5,F,11.58,Macaca fascicularis
0,7.153687,0.75,-46.510258,42.546146,0.85,3.405762,2.494742,-55.589845,NaN,0.999300,0.990622,Sweep_206,M04_SM_A1_C13,NA,NA,PFC,6.5,F,11.58,Macaca fascicularis

In [63]:
file_paths3 = get_file_paths(r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05")
M05_df = monkey_df(file_paths3, 49)

save_dataframe_to_pickle(M05_df, r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05_df.pkl")

C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_JS_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.68it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.67it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.52it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.36it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.15it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.20it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.81s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.28s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_18
Sweep_19
Sweep_2
Sweep_20
Sweep_21
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_3
Sweep_4
Sweep_5
Sweep_53
Sweep_55
Sweep_56
Sweep_57
Sweep_58
Sweep_59
Sweep_6
Sweep_60
Sweep_61
Sweep_62
Sweep_63
Sweep_64
Sweep_65
Sweep_66
Sweep_67
Sweep_68
Sweep_69
Sweep_7
Sweep_70
Sweep_71
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_JS_A1_C02.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.91it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.25it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.41it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:03<00:00,  7.20it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.44it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.09it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:03<00:00,  5.35it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 47/47 [00:03<00:00, 12.94it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.22it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.29it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.02it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.06it/s]

Sweep_0
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_18
Sweep_19
Sweep_20
Sweep_21
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_3
Sweep_4
Sweep_5
Sweep_6
Sweep_66
Sweep_67
Sweep_68
Sweep_69
Sweep_7
Sweep_70
Sweep_71
Sweep_72
Sweep_73
Sweep_74
Sweep_75
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_JS_A1_C03.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:03<00:00,  6.80it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  7.43it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 33/33 [00:04<00:00,  7.79it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 36/36 [00:04<00:00,  8.35it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 40/40 [00:04<00:00,  9.73it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.59it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.48it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:03<00:00,  4.75it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:04<00:00,  5.76it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 30/30 [00:04<00:00,  7.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 32/32 [00:04<00:00,  7.25it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 38/38 [00:05<00:00,  7.56it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 39/39 [00:04<00:00,  8.22it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.05it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.47it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:05<00:00,  3.56it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_JS_A1_C04.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_0
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_56
Sweep_57
Sweep_58
Sweep_59
Sweep_60
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_JS_A1_C05.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.77it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.67it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.66it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.11it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.11it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.93it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 30/30 [00:07<00:00,  3.91it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 48/48 [00:07<00:00,  6.55it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 75/75 [00:07<00:00,  9.38it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 94/94 [00:07<00:00, 12.06it/s]

Fitting failed for sweep Sweep_22: could not broadcast input array from shape (13,) into shape (20,)

Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:06<00:00,  1.65it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.30it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.82it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.65it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.66it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.64it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:04<00:00,  2.09it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:04<00:00,  2.14it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.84it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 27/27 [00:06<00:00,  3.98it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 51/51 [00:06<00:00,  7.74it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 63/63 [00:06<00:00,  9.62it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 47/47 [00:06<00:00,  7.22it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_17
Sweep_18
Sweep_19
Sweep_20
Sweep_21
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_4
Sweep_5
Sweep_6
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_JS_A1_C06.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.30it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.22it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.06it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.07it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 28/28 [00:04<00:00,  6.40it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 52/52 [00:04<00:00, 10.62it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 64/64 [00:05<00:00, 12.25it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 83/83 [00:05<00:00, 15.10it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 78/78 [00:05<00:00, 13.27it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 27/27 [00:06<00:00,  4.42it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.80s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.80s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_75
Sweep_76
Sweep_77
Sweep_78
Sweep_79
Sweep_8
Sweep_80
Sweep_81
Sweep_82
Sweep_83
Sweep_84
Sweep_85
Sweep_86
Sweep_87
Sweep_88
Sweep_89
Sweep_9
Sweep_90
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_JS_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.06it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_126
Sweep_128
Sweep_13
Sweep_130
Sweep_131
Sweep_132
Sweep_133
Sweep_134
Sweep_135
Sweep_136
Sweep_137
Sweep_14
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_JS_A1_C08.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.57it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.61it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.61it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  4.28it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.51it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.47it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.01it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.55it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_16
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_JS_A1_C09.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.21it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.72it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.09it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.63it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.69it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_60
Sweep_61
Sweep_62
Sweep_63
Sweep_64
Sweep_65
Sweep_66
Sweep_67
Sweep_68
Sweep_69
Sweep_7
Sweep_70
Sweep_71
Sweep_72
Sweep_73
Sweep_74
Sweep_75
Sweep_76
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_JS_A1_C10.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.11it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.05it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_21
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_6
Sweep_7
Sweep_78
Sweep_8
Sweep_80
Sweep_81
Sweep_82
Sweep_83
Sweep_84
Sweep_85
Sweep_86
Sweep_87
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_JS_A1_C11.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:03<00:00,  6.95it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:03<00:00,  7.28it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  6.08it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.66it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  4.31it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.67it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.56it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  7.70it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 43/43 [00:03<00:00, 11.17it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 45/45 [00:03<00:00, 11.59it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 48/48 [00:04<00:00, 11.93it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 47/47 [00:03<00:00, 11.96it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 36/36 [00:03<00:00,  9.09it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 37/37 [00:04<00:00,  9.24it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:04<00:00,  5.75it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 47/47 [00:04<00:00, 11.53it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 22/22 [00:04<00:00,  5.44it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 29/29 [00:03<00:00,  7.72it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 35/35 [00:03<00:00, 10.06it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_21
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_5
Sweep_6
Sweep_7
Sweep_79
Sweep_8
Sweep_81
Sweep_82
Sweep_83
Sweep_84
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_JS_A1_C13.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  4.24it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:03<00:00,  5.80it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:04<00:00,  5.28it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 29/29 [00:04<00:00,  5.86it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 32/32 [00:05<00:00,  6.35it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.07it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.53it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:05<00:00,  3.12it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 26/26 [00:05<00:00,  4.77it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 29/29 [00:05<00:00,  4.99it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 32/32 [00:05<00:00,  5.44it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:05<00:00,  2.68it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.99it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:04<00:00,  2.23it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_17
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_5
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_JS_A1_C15.nwb

Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:04<00:00,  2.30it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:04<00:00,  2.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:04<00:00,  2.41it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.93it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.54it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.56it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:04<00:00,  2.24it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.92it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.11it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.84it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.69it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.59it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_3
Sweep_30
Sweep_31
Sweep_32
Sweep_4
Sweep_5
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_JS_A1_C16.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.31it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.46it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 70/70 [00:04<00:00, 14.10it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:05<00:00,  4.58it/s]

Fitting failed for sweep Sweep_11: could not broadcast input array from shape (11,) into shape (20,)

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.99it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.75it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.48s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.84it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 31/31 [00:06<00:00,  4.90it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 43/43 [00:06<00:00,  6.22it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 52/52 [00:06<00:00,  8.06it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_34
Sweep_35
Sweep_36
Sweep_37
Sweep_39
Sweep_40
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_MJ_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.33it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.31it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:04<00:00,  1.80it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_MJ_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.54it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:04<00:00,  1.70it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:05<00:00,  1.94it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:07<00:00,  2.30it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.50it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:04<00:00,  2.04it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:04<00:00,  2.31it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:04<00:00,  2.34it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.58it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.50it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.87it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.84it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.66it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_41
Sweep_42
Sweep_43
Sweep_44
Sweep_56
Sweep_57
Sweep_58
Sweep_59
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_MJ_A1_C04.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.11it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.54it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:04<00:00,  2.73it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.09it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.41it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.41it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.81s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.11it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_41
Sweep_42
Sweep_43
Sweep_44
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_MW_A1_C04.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 80/80 [00:03<00:00, 20.19it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 100/100 [00:05<00:00, 16.71it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 120/120 [00:06<00:00, 19.28it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 138/138 [00:06<00:00, 21.22it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 141/141 [00:06<00:00, 21.28it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:06<00:00,  2.89it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 74/74 [00:06<00:00, 11.85it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 97/97 [00:06<00:00, 14.19it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 124/124 [00:06<00:00, 19.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 122/122 [00:06<00:00, 19.08it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:02<00:00,  4.49it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_50
Sweep_51
Sweep_54
Sweep_55
Sweep_56
Sweep_57
Sweep_58
Sweep_59
Sweep_60
Sweep_61
Sweep_62
Sweep_63
Sweep_64
Sweep_65
Sweep_66
Sweep_67
Sweep_68
Sweep_69
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_MW_A1_C05.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.69it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:03<00:00,  5.92it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.87it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:03<00:00,  5.68it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:03<00:00,  5.87it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:03<00:00,  6.57it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 30/30 [00:03<00:00,  7.83it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 26/26 [00:03<00:00,  7.31it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:03<00:00,  5.54it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 50/50 [00:03<00:00, 12.83it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.01it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.08it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 57/57 [00:03<00:00, 15.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.33it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.05it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.79it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.23it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.00it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.80it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.63it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.44it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_18
Sweep_2
Sweep_20
Sweep_21
Sweep_22
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_3
Sweep_4
Sweep_5
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_SM_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 26/26 [00:04<00:00,  5.98it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 34/34 [00:04<00:00,  7.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 26/26 [00:04<00:00,  5.78it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:04<00:00,  4.08it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.95it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.44it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.21it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:04<00:00,  3.89it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_SM_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:05<00:00,  3.11it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.89it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:05<00:00,  4.58it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:05<00:00,  4.63it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 28/28 [00:05<00:00,  5.06it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.63it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.12it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:05<00:00,  2.68it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 22/22 [00:08<00:00,  2.74it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:08<00:00,  3.03it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.11it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_SM_A1_C03.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 123/123 [00:06<00:00, 19.87it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 140/140 [00:06<00:00, 20.31it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 126/126 [00:06<00:00, 20.78it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 142/142 [00:06<00:00, 20.31it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 109/109 [00:03<00:00, 32.05it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 131/131 [00:05<00:00, 23.52it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 149/149 [00:05<00:00, 28.60it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 164/164 [00:05<00:00, 32.36it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_0
Sweep_12
Sweep_13
Sweep_14
Sweep_27
Sweep_28
Sweep_29
Sweep_52
Sweep_53
Sweep_54
Sweep_55
Sweep_56
Sweep_57
Sweep_58
Sweep_59
Sweep_60
Sweep_69
Sweep_70
Sweep_71
Sweep_72
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_SM_A1_C06.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 62/62 [00:04<00:00, 13.31it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 61/61 [00:04<00:00, 12.57it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 37/37 [00:05<00:00,  7.38it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.08it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.28it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.45it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 41/41 [00:05<00:00,  7.14it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 57/57 [00:06<00:00,  9.30it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 56/56 [00:06<00:00,  9.08it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.07it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:04<00:00,  2.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.46it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.73it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.04it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 37/37 [00:06<00:00,  5.77it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 49/49 [00:06<00:00,  7.45it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_19
Sweep_21
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_SM_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.20it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.68it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.78s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05\M05_SM_A1_C13.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]

Sweep_27
Sweep_28
Sweep_29

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

In [64]:
M05_df = load_dataframe_from_pickle(r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M05_df.pkl")

M05_df.tail()

,ramp_amp,inflection_time,inflection_amp,peak_amp,peak_width,peak_sharpness,exp_lambda,exp_const,isi,r_squared_ramp,r_squared_exp,Sweep_#,file_name,dendriticType,SomaLayerLoc,brainOrigin,Weight,Sex,Age,Species
4,1.787917,1.20,-35.691650,26.594727,1.45,0.610352,1.165553,-47.850570,43.70,0.908361,0.997375,Sweep_9,M05_JS_A1_C13,NA,NA,PFC,7.4,M,4.39,Macaca fascicularis
5,1.474022,1.15,-35.691650,27.632324,1.40,0.946045,1.132225,-48.452109,51.80,0.890761,0.998009,Sweep_9,M05_JS_A1_C13,NA,NA,PFC,7.4,M,4.39,Macaca fascicularis
6,0.966466,1.20,-35.416992,25.740234,1.50,0.549316,1.122565,-47.547140,0.00,0.796952,0.997495,Sweep_9,M05_JS_A1_C13,NA,NA,PFC,7.4,M,4.39,Macaca fascicularis
7,0.966466,1.20,-35.416992,25.740234,1.50,0.549316,1.122565,-47.547140,52.15,0.796952,0.997495,Sweep_9,M05_JS_A1_C13,NA,NA,PFC,7.4,M,4.39,Macaca fascicularis
8,1.377192,1.30,-34.135254,24.824707,1.50,0.915527,1.099463,-47.206315,NaN,0.774453,0.998393,Sweep_9,M05_JS_A1_C13,NA,NA,PFC,7.4,M,4.39,Macaca fascicularis

In [22]:
file_paths4 = get_file_paths(r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M06")
M06_df = monkey_df(file_paths4, 66)

save_dataframe_to_pickle(M06_df, r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M06_df.pkl")

C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M06\M06_MW_A1_C04.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.85s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.34it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  4.11it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  4.14it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  4.26it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 27/27 [00:03<00:00,  7.84it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.79s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.72it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.57it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.73it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  3.89it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  4.02it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.88s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.76it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.46it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_2
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_3
Sweep_4
Sweep_48
Sweep_49
Sweep_50
Sweep_58
Sweep_60
Sweep_66
Sweep_67
Sweep_68
Sweep_69
Sweep_7
Sweep_70
Sweep_71
Sweep_72
Sweep_73
Sweep_74
Sweep_75
Sweep_76
Sweep_77
Sweep_78
Sweep_79
Sweep_8
Sweep_80
Sweep_81
Sweep_82
Sweep_83
Sweep_84
Sweep_85
Sweep_86
Sweep_87
Sweep_88
Sweep_89
Sweep_9
Sweep_90
Sweep_91
Sweep_92
Sweep_93
Sweep_94
Sweep_95
Sweep_96
Sweep_97
Sweep_98
Sweep_99
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M06\M06_SM_A1_C01.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.68it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.75it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.69it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.72it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.42it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M06\M06_SM_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.69it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.77it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.71it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.69it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.68it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]

Fitting failed for sweep Sweep_16: All fits failed.

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.71it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.71it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.74it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.02it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.71it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_21
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M06\M06_SM_A1_C08.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_39
Sweep_40
Sweep_41
Sweep_42
Sweep_43
Sweep_44
Sweep_45
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M06\M06_SM_A1_C12.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  4.26it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  4.04it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.95it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.94it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.83it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.70it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.32it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.55it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.31it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.02it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_3
Sweep_4
Sweep_7
Sweep_8
Sweep_9

In [23]:
M06_df.head()

,ramp_amp,inflection_time,inflection_amp,peak_amp,peak_width,peak_sharpness,exp_lambda,exp_const,isi,r_squared_ramp,r_squared_exp,Sweep_#,file_name,dendriticType,SomaLayerLoc,brainOrigin,Weight,Sex,Age,Species
0,3.015504,0.55,-44.738771,25.451661,0.65,4.821777,2.929958,-52.918481,NaN,0.986424,0.999387,Sweep_0,M06_MW_A1_C04,A,2,PFC,5,M,4.76,Macaca fascicularis
0,2.926016,0.55,-44.158937,26.306153,0.65,4.699707,3.093520,-53.003746,NaN,0.992559,0.998917,Sweep_1,M06_MW_A1_C04,A,2,PFC,5,M,4.76,Macaca fascicularis
0,3.816762,0.50,-41.717530,30.761719,0.60,6.072998,4.063969,-48.254377,14.90,0.994712,0.966464,Sweep_10,M06_MW_A1_C04,A,2,PFC,5,M,4.76,Macaca fascicularis
1,2.270233,0.55,-34.454346,27.465821,0.70,4.013062,2.560024,-48.684115,241.55,0.973479,0.996839,Sweep_10,M06_MW_A1_C04,A,2,PFC,5,M,4.76,Macaca fascicularis
2,1.096338,0.75,-29.998780,28.442383,0.95,1.831055,1.656402,-48.861020,174.35,0.933462,0.998526,Sweep_10,M06_MW_A1_C04,A,2,PFC,5,M,4.76,Macaca fascicularis

In [43]:
M06_df = load_dataframe_from_pickle(r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M06_df.pkl")
M06_df.tail()

,ramp_amp,inflection_time,inflection_amp,peak_amp,peak_width,peak_sharpness,exp_lambda,exp_const,isi,r_squared_ramp,r_squared_exp,Sweep_#,file_name,dendriticType,SomaLayerLoc,brainOrigin,Weight,Sex,Age,Species
3,3.509292,0.35,-39.459229,18.096924,0.35,13.931275,10.0,-37.692262,4.60,0.968336,3.119926e-31,Sweep_9,M06_SM_A1_C12,NA,NA,PFC,5,M,4.76,Macaca fascicularis
4,3.587307,0.45,-37.902833,17.181397,0.40,10.894776,10.0,-39.810521,4.95,0.970636,2.524654e-03,Sweep_9,M06_SM_A1_C12,NA,NA,PFC,5,M,4.76,Macaca fascicularis
5,3.275706,0.45,-36.834718,15.563965,0.40,10.421753,10.0,-38.339234,4.85,0.943536,2.168229e-31,Sweep_9,M06_SM_A1_C12,NA,NA,PFC,5,M,4.76,Macaca fascicularis
6,3.401448,0.50,-37.261964,14.373780,0.40,9.506226,10.0,-41.364146,6.50,0.974846,2.094324e-02,Sweep_9,M06_SM_A1_C12,NA,NA,PFC,5,M,4.76,Macaca fascicularis
7,1.979283,0.50,-33.447266,12.359619,0.40,7.080078,10.0,-40.974258,NaN,0.922619,1.694799e-02,Sweep_9,M06_SM_A1_C12,NA,NA,PFC,5,M,4.76,Macaca fascicularis

In [10]:
file_paths5 = get_file_paths(r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08")
M08_df = monkey_df(file_paths5, 71)

save_dataframe_to_pickle(M06_df, r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08_df.pkl")

C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_JS_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.13s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:05<00:00,  4.50it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 59/59 [00:05<00:00, 10.70it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 69/69 [00:04<00:00, 14.48it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 76/76 [00:04<00:00, 15.24it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.43s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 45/45 [00:04<00:00,  9.52it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 59/59 [00:04<00:00, 12.42it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 67/67 [00:04<00:00, 13.97it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 75/75 [00:05<00:00, 14.96it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_84
Sweep_85
Sweep_86
Sweep_87
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_JS_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 46/46 [00:04<00:00,  9.78it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 52/52 [00:04<00:00, 11.37it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 162/162 [00:04<00:00, 33.59it/s]

Fitting failed for sweep Sweep_12: Length of values (163) does not match length of index (162)

Spike: 100%|█████████████████████████████████████████████████████████████████████████| 173/173 [00:04<00:00, 36.24it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 102/102 [00:04<00:00, 21.74it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.02it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.51it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:04<00:00,  4.56it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 31/31 [00:04<00:00,  6.67it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 38/38 [00:04<00:00,  8.36it/s]

Sweep_10
Sweep_11
Sweep_13
Sweep_14
Sweep_4
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_JS_A1_C03.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:04<00:00,  4.46it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 56/56 [00:04<00:00, 12.11it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 64/64 [00:04<00:00, 14.07it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 77/77 [00:04<00:00, 16.92it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 86/86 [00:04<00:00, 18.62it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.10it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 39/39 [00:04<00:00,  8.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 55/55 [00:04<00:00, 11.98it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 168/168 [00:04<00:00, 35.26it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 96/96 [00:04<00:00, 20.74it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 101/101 [00:04<00:00, 21.51it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.09it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_JS_A1_C04.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.76s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.36s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.09it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 63/63 [00:04<00:00, 13.60it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 59/59 [00:04<00:00, 12.83it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 63/63 [00:04<00:00, 13.85it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 53/53 [00:04<00:00, 11.48it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_16
Sweep_17
Sweep_18
Sweep_21
Sweep_27
Sweep_28
Sweep_29
Sweep_30
Sweep_31
Sweep_32
Sweep_33
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_JS_A1_C06.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.70it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.41it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.52it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:04<00:00,  4.50it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.46it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.31s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:04<00:00,  3.90it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:04<00:00,  4.89it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.06it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.15it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 39/39 [00:04<00:00,  8.17it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.39s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_110
Sweep_111
Sweep_112
Sweep_113
Sweep_12
Sweep_13
Sweep_14
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_JS_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.03it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.45it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.85it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]

Fitting failed for sweep Sweep_18: All fits failed.

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.72s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.35s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_4
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_JS_A1_C08.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.76s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.37it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.70it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_JS_A1_C09.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 44/44 [00:04<00:00,  9.59it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 49/49 [00:04<00:00, 10.68it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 57/57 [00:04<00:00, 12.28it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 61/61 [00:04<00:00, 13.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 66/66 [00:04<00:00, 13.81it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.48s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.96s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.23s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.34it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.05it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 28/28 [00:05<00:00,  5.25it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 36/36 [00:04<00:00,  7.73it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_4
Sweep_49
Sweep_5
Sweep_51
Sweep_52
Sweep_53
Sweep_54
Sweep_55
Sweep_56
Sweep_57
Sweep_58
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_JS_A1_C10.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.10it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 41/41 [00:04<00:00,  8.94it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.88s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_101
Sweep_102
Sweep_103
Sweep_82
Sweep_83
Sweep_84
Sweep_85
Sweep_86
Sweep_87
Sweep_88
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_JS_A1_C12.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.57it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.37it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.39it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.28s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.34it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.59it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:04<00:00,  5.41it/s]

Fitting failed for sweep Sweep_23: could not broadcast input array from shape (18,) into shape (20,)

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.67it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.68it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.11it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.04it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.06it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.94it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.48it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.50it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.92it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_20
Sweep_21
Sweep_22
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_3
Sweep_38
Sweep_39
Sweep_40
Sweep_41
Sweep_42
Sweep_5
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_JS_A1_C14.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 75/75 [00:04<00:00, 16.43it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 92/92 [00:04<00:00, 19.72it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 87/87 [00:05<00:00, 17.15it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 96/96 [00:04<00:00, 20.36it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 105/105 [00:04<00:00, 22.60it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 110/110 [00:04<00:00, 23.31it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.12it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 43/43 [00:04<00:00,  9.15it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 59/59 [00:04<00:00, 12.35it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 71/71 [00:04<00:00, 15.30it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 83/83 [00:04<00:00, 16.83it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 96/96 [00:05<00:00, 19.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 101/101 [00:04<00:00, 21.09it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 109/109 [00:04<00:00, 22.57it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 31/31 [00:04<00:00,  6.34it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.01s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 61/61 [00:04<00:00, 12.91it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:05<00:00,  4.56it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 46/46 [00:04<00:00,  9.30it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 57/57 [00:05<00:00, 11.20it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 69/69 [00:06<00:00, 10.02it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 78/78 [00:06<00:00, 11.99it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 86/86 [00:06<00:00, 13.00it/s]

Sweep_10
Sweep_100
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_8
Sweep_83
Sweep_84
Sweep_85
Sweep_9
Sweep_94
Sweep_95
Sweep_96
Sweep_97
Sweep_98
Sweep_99
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_JS_A1_C15.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.05it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.07it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.30s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_27
Sweep_28
Sweep_29
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_JS_A1_C16.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.42it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.91it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  3.32it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.34it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:04<00:00,  3.61it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 55/55 [00:04<00:00, 11.09it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.32s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.67it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_27
Sweep_29
Sweep_30
Sweep_31
Sweep_32
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_MW_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.30s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 52/52 [00:04<00:00, 11.52it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_2
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_MW_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.39it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:04<00:00,  4.81it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:04<00:00,  5.41it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 29/29 [00:04<00:00,  5.87it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 31/31 [00:04<00:00,  6.28it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.43s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.41it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.13it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:04<00:00,  3.73it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.15it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:04<00:00,  4.85it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:05<00:00,  4.79it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.31it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.61it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.17it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_MW_A1_C03.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 40/40 [00:04<00:00,  8.73it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.91s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 46/46 [00:04<00:00,  9.73it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 52/52 [00:04<00:00, 11.16it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 53/53 [00:04<00:00, 11.56it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 56/56 [00:04<00:00, 12.20it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.48it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:07<00:00,  2.94it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 29/29 [00:07<00:00,  4.13it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 35/35 [00:06<00:00,  5.07it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 40/40 [00:07<00:00,  5.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 44/44 [00:08<00:00,  5.47it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.23it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.83s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 22/22 [00:05<00:00,  4.38it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.85s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.25s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 33/33 [00:04<00:00,  7.22it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]

Sweep_10
Sweep_100
Sweep_101
Sweep_102
Sweep_103
Sweep_104
Sweep_105
Sweep_106
Sweep_107
Sweep_108
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_7
Sweep_78
Sweep_79
Sweep_8
Sweep_80
Sweep_81
Sweep_82
Sweep_83
Sweep_84
Sweep_85
Sweep_86
Sweep_87
Sweep_88
Sweep_89
Sweep_9
Sweep_90
Sweep_91
Sweep_92
Sweep_93
Sweep_94
Sweep_95
Sweep_96
Sweep_97
Sweep_98
Sweep_99
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_MW_A1_C05.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13
Sweep_14
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_MW_A1_C06.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.29it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.72s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.40it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.86s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.64it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.07it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.04it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.44s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.31it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.91it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.28it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.37it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.31it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.78s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.72s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.88s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.83s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.89s/it]

Sweep_0
Sweep_10
Sweep_100
Sweep_101
Sweep_102
Sweep_103
Sweep_104
Sweep_105
Sweep_106
Sweep_107
Sweep_108
Sweep_109
Sweep_11
Sweep_110
Sweep_111
Sweep_112
Sweep_113
Sweep_114
Sweep_115
Sweep_116
Sweep_12
Sweep_13
Sweep_14
Sweep_30
Sweep_31
Sweep_32
Sweep_33
Sweep_34
Sweep_35
Sweep_36
Sweep_7
Sweep_72
Sweep_73
Sweep_74
Sweep_75
Sweep_76
Sweep_77
Sweep_78
Sweep_79
Sweep_8
Sweep_80
Sweep_81
Sweep_82
Sweep_83
Sweep_84
Sweep_85
Sweep_86
Sweep_87
Sweep_88
Sweep_89
Sweep_9
Sweep_90
Sweep_91
Sweep_92
Sweep_93
Sweep_94
Sweep_95
Sweep_96
Sweep_97
Sweep_98
Sweep_99
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_MW_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:04<00:00,  2.74it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.38it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.80it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.56it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.32it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:04<00:00,  4.08it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:04<00:00,  4.97it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:04<00:00,  5.18it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12
Sweep_13
Sweep_14
Sweep_37
Sweep_38
Sweep_39
Sweep_40
Sweep_41
Sweep_42
Sweep_43
Sweep_44
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_MW_A1_C08.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.85it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.97it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.21it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:04<00:00,  3.88it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:04<00:00,  4.61it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.06it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.69it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  3.26it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.43it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:04<00:00,  4.18it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.34it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.05it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_36
Sweep_37
Sweep_38
Sweep_39
Sweep_40
Sweep_41
Sweep_42
Sweep_43
Sweep_44
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_SM_A1_C03.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 71/71 [00:04<00:00, 15.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 90/90 [00:04<00:00, 19.23it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 107/107 [00:04<00:00, 23.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 117/117 [00:04<00:00, 25.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 126/126 [00:04<00:00, 26.33it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 68/68 [00:04<00:00, 14.85it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 86/86 [00:04<00:00, 18.64it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 101/101 [00:04<00:00, 21.47it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 113/113 [00:04<00:00, 23.99it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 127/127 [00:04<00:00, 26.51it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 86/86 [00:04<00:00, 18.66it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 100/100 [00:04<00:00, 21.19it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 114/114 [00:04<00:00, 24.09it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 56/56 [00:04<00:00, 12.18it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.97it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_53
Sweep_55
Sweep_56
Sweep_57
Sweep_58
Sweep_59
Sweep_71
Sweep_72
Sweep_73
Sweep_74
Sweep_75
Sweep_76
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_SM_A1_C04.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.09it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.30s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.41s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.28it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.22it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.46s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.00it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:04<00:00,  4.25it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.12it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:03<00:00,  1.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.35it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.80s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.97s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.13s/it]

Sweep_0
Sweep_10
Sweep_100
Sweep_101
Sweep_102
Sweep_11
Sweep_113
Sweep_114
Sweep_115
Sweep_116
Sweep_117
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_27
Sweep_28
Sweep_29
Sweep_30
Sweep_31
Sweep_78
Sweep_81
Sweep_82
Sweep_84
Sweep_85
Sweep_86
Sweep_87
Sweep_98
Sweep_99
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_SM_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.88s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:03<00:00,  1.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.45s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_18
Sweep_19
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M08\M08_SM_A1_C09.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.39it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.04it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.88it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.33it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:04<00:00,  4.88it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.92s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.98s/it]
Spike: 100%|████████████████████████████████████████████████████████████████████████████| 1/1 [04:10<00:00, 250.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.47s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.61s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.31s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.40s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_186
Sweep_187
Sweep_188
Sweep_189
Sweep_190
Sweep_191
Sweep_192
Sweep_193
Sweep_194
Sweep_195
Sweep_196
Sweep_28
Sweep_29
Sweep_30
Sweep_31
Sweep_9

NameError: name 'M06_df' is not defined

In [11]:
M08_df.tail()

,ramp_amp,inflection_time,inflection_amp,peak_amp,peak_width,peak_sharpness,exp_lambda,exp_const,isi,r_squared_ramp,r_squared_exp,Sweep_#,file_name,dendriticType,SomaLayerLoc,brainOrigin,Weight,Sex,Age,Species
1,0.794375,0.65,-38.909913,36.468507,0.80,4.425049,2.137163,-51.691492,NaN,0.545088,0.997106,Sweep_30,M08_SM_A1_C09,S,3,PFC,7,F,8.92,Macaca fascicularis
0,1.468515,0.55,-46.234132,40.954591,0.75,6.378174,3.026000,-50.892683,50.2,0.879472,0.991583,Sweep_31,M08_SM_A1_C09,S,3,PFC,7,F,8.92,Macaca fascicularis
1,1.474022,0.65,-38.879395,35.888673,0.80,3.082275,2.198073,-51.345226,NaN,0.874374,0.997618,Sweep_31,M08_SM_A1_C09,S,3,PFC,7,F,8.92,Macaca fascicularis
0,1.390041,0.55,-41.839601,38.360597,0.75,5.432129,2.742456,-52.898929,132.3,0.828544,0.994800,Sweep_9,M08_SM_A1_C09,S,3,PFC,7,F,8.92,Macaca fascicularis
1,1.450618,0.70,-39.520265,33.172608,0.80,3.662109,2.285205,-52.881483,NaN,0.813673,0.997377,Sweep_9,M08_SM_A1_C09,S,3,PFC,7,F,8.92,Macaca fascicularis

In [65]:
file_paths6 = get_file_paths(r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10")
M10_df = monkey_df(file_paths6, 95)

save_dataframe_to_pickle(M10_df, r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10_df.pkl")

C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C03.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 71/71 [00:03<00:00, 19.86it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 83/83 [00:04<00:00, 17.06it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 92/92 [00:04<00:00, 19.38it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 100/100 [00:04<00:00, 22.20it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 109/109 [00:04<00:00, 24.02it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.81s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.66it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 35/35 [00:03<00:00, 10.73it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 48/48 [00:03<00:00, 14.42it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 60/60 [00:03<00:00, 16.55it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_40
Sweep_41
Sweep_42
Sweep_43
Sweep_44
Sweep_45
Sweep_46
Sweep_47
Sweep_48
Sweep_49
Sweep_50
Sweep_51
Sweep_52
Sweep_6
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C04.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 34/34 [00:03<00:00,  9.35it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.44it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.53it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.04it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:02<00:00,  4.52it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 27/27 [00:03<00:00,  8.32it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 42/42 [00:03<00:00, 12.37it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 60/60 [00:04<00:00, 13.62it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_35
Sweep_36
Sweep_37
Sweep_38
Sweep_39
Sweep_40
Sweep_41
Sweep_42
Sweep_43
Sweep_44
Sweep_45
Sweep_46
Sweep_47
Sweep_48
Sweep_49
Sweep_50
Sweep_6
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C05.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.82it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.31it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.35it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.61it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.71s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.84s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  4.08it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.96it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  2.68it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.88it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  3.11it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.81s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_113
Sweep_114
Sweep_115
Sweep_116
Sweep_117
Sweep_118
Sweep_119
Sweep_12
Sweep_120
Sweep_121
Sweep_122
Sweep_123
Sweep_124
Sweep_125
Sweep_126
Sweep_127
Sweep_128
Sweep_129
Sweep_13
Sweep_130
Sweep_131
Sweep_14
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_62
Sweep_63
Sweep_64
Sweep_65
Sweep_66
Sweep_67
Sweep_68
Sweep_69
Sweep_70
Sweep_71
Sweep_72
Sweep_73
Sweep_74
Sweep_75
Sweep_76
Sweep_77
Sweep_78
Sweep_79
Sweep_8
Sweep_80
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.74s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.84s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.85s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_119
Sweep_12
Sweep_120
Sweep_121
Sweep_122
Sweep_123
Sweep_124
Sweep_13
Sweep_137
Sweep_138
Sweep_139
Sweep_14
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C08.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.71it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.87it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.53it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.07it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.83it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.75s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.64it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.78s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_8
Sweep_89
Sweep_9
Sweep_90
Sweep_91
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C09.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 76/76 [00:03<00:00, 23.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 99/99 [00:03<00:00, 28.98it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 121/121 [00:03<00:00, 32.63it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 141/141 [00:03<00:00, 36.42it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 158/158 [00:04<00:00, 38.76it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:03<00:00,  7.64it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 50/50 [00:03<00:00, 14.66it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_48
Sweep_50
Sweep_51
Sweep_52
Sweep_53
Sweep_54
Sweep_55
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C11.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.74it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.18it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.88s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]

Sweep_100
Sweep_101
Sweep_102
Sweep_103
Sweep_104
Sweep_105
Sweep_106
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_97
Sweep_98
Sweep_99
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C13.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 33/33 [00:03<00:00,  9.95it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 76/76 [00:03<00:00, 22.19it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 97/97 [00:03<00:00, 27.26it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12
Sweep_13
Sweep_14
Sweep_69
Sweep_70
Sweep_71
Sweep_72
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C14.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.72it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.51it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.33it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12
Sweep_13
Sweep_14
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C15.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.75s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:03<00:00,  5.42it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 35/35 [00:03<00:00,  9.64it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 50/50 [00:03<00:00, 13.07it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 68/68 [00:04<00:00, 16.94it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 77/77 [00:04<00:00, 18.04it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]

Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C16.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12
Sweep_13
Sweep_14
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C17.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.72it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.12it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  3.87it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:03<00:00,  3.94it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.04it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C18.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 31/31 [00:03<00:00,  8.31it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.03it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:04<00:00,  5.22it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  3.76it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.88s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.85s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_51
Sweep_52
Sweep_53
Sweep_54
Sweep_55
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C19.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 63/63 [00:03<00:00, 17.85it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 76/76 [00:03<00:00, 19.80it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 73/73 [00:04<00:00, 18.20it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 32/32 [00:04<00:00,  7.80it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  4.11it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.85s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 34/34 [00:03<00:00,  9.59it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 53/53 [00:03<00:00, 14.35it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_49
Sweep_50
Sweep_51
Sweep_52
Sweep_53
Sweep_54
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C20.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 43/43 [00:03<00:00, 10.93it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 51/51 [00:04<00:00, 12.57it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 58/58 [00:04<00:00, 13.98it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 63/63 [00:04<00:00, 14.95it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 69/69 [00:04<00:00, 15.77it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:02<00:00,  4.38it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:03<00:00,  6.88it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 35/35 [00:03<00:00,  9.16it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_56
Sweep_57
Sweep_58
Sweep_59
Sweep_60
Sweep_61
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C21.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]

Sweep_100
Sweep_101
Sweep_102
Sweep_103
Sweep_104
Sweep_105
Sweep_106
Sweep_107
Sweep_108
Sweep_109
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_96
Sweep_97
Sweep_98
Sweep_99
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C22.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 57/57 [00:03<00:00, 17.12it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 81/81 [00:03<00:00, 23.28it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 99/99 [00:03<00:00, 26.94it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 118/118 [00:03<00:00, 30.16it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 129/129 [00:04<00:00, 31.35it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.86it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 38/38 [00:03<00:00, 10.93it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_51
Sweep_52
Sweep_53
Sweep_54
Sweep_55
Sweep_56
Sweep_57
Sweep_58
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C23.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.68it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:05<00:00,  2.67it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 22/22 [00:06<00:00,  3.36it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:06<00:00,  3.69it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.88s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.18it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_69
Sweep_7
Sweep_70
Sweep_71
Sweep_72
Sweep_73
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C24.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.35it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.88it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.94it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.03it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  2.81it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.80s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_137
Sweep_138
Sweep_139
Sweep_14
Sweep_140
Sweep_141
Sweep_142
Sweep_143
Sweep_144
Sweep_145
Sweep_146
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C25.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.20it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.76it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C26.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 53/53 [00:03<00:00, 16.41it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 65/65 [00:04<00:00, 13.67it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 75/75 [00:04<00:00, 16.16it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 84/84 [00:04<00:00, 18.33it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 94/94 [00:04<00:00, 20.17it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.88s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 29/29 [00:03<00:00,  9.05it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 41/41 [00:04<00:00,  8.45it/s]

Sweep_0
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_57
Sweep_58
Sweep_59
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C27.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.74it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.16it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:03<00:00,  5.21it/s]

Fitting failed for sweep Sweep_7: could not broadcast input array from shape (9,) into shape (20,)

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.66it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.38it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_25
Sweep_26
Sweep_27
Sweep_6
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C28.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 42/42 [00:06<00:00,  6.36it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 55/55 [00:06<00:00,  8.14it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 69/69 [00:06<00:00,  9.94it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 75/75 [00:06<00:00, 11.26it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 82/82 [00:06<00:00, 12.14it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.12it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:04<00:00,  4.55it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 36/36 [00:05<00:00,  7.16it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_58
Sweep_59
Sweep_60
Sweep_61
Sweep_62
Sweep_63
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C30.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.76s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.75s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_62
Sweep_63
Sweep_64
Sweep_65
Sweep_66
Sweep_67
Sweep_68
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_JS_A1_C32.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.57it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.59it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.71s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:02<00:00,  4.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  4.21it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.90it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.19it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_110
Sweep_112
Sweep_12
Sweep_13
Sweep_14
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_MJ_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_MJ_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.72it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.72it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.75it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.73it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.67it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.74it/s]

Fitting failed for sweep Sweep_64: could not broadcast input array from shape (14,) into shape (20,)

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.70it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.70it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.12it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_63
Sweep_65
Sweep_66
Sweep_67
Sweep_68
Sweep_69
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_MJ_A1_C03.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.76s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.20it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.70it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.60it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.49it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.01it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.94it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.09it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.08it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.83it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.95it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.88it/s]

Sweep_0
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_MJ_A1_C06.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  2.71it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.01it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 61/61 [00:04<00:00, 12.31it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 62/62 [00:05<00:00, 12.09it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 27/27 [00:05<00:00,  5.22it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  2.95it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.41it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.94it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.45it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.12it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.67it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 36/36 [00:06<00:00,  5.34it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 47/47 [00:06<00:00,  6.96it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 56/56 [00:06<00:00,  8.35it/s]

Sweep_0
Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_2
Sweep_3
Sweep_4
Sweep_42
Sweep_44
Sweep_45
Sweep_46
Sweep_47
Sweep_48
Sweep_49
Sweep_50
Sweep_52
Sweep_53
Sweep_54
Sweep_6
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_MJ_A1_C10.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.62it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.00it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.04it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11
Sweep_12
Sweep_13
Sweep_14
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_MJ_A1_C11.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_MJ_A1_C12.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.20it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13
Sweep_14
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_SA_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 29/29 [00:05<00:00,  5.53it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 34/34 [00:05<00:00,  6.22it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 38/38 [00:05<00:00,  7.57it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 40/40 [00:04<00:00,  8.11it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 44/44 [00:05<00:00,  8.67it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.13it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:02<00:00,  4.47it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 32/32 [00:03<00:00,  8.60it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 35/35 [00:04<00:00,  8.06it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 40/40 [00:04<00:00,  8.65it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 43/43 [00:04<00:00,  9.73it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 46/46 [00:04<00:00, 10.11it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.69it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.86it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.19it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_140
Sweep_141
Sweep_142
Sweep_143
Sweep_144
Sweep_21
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_6
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_SA_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 141/141 [00:04<00:00, 28.39it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 163/163 [00:05<00:00, 30.42it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 183/183 [00:05<00:00, 33.42it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 196/196 [00:05<00:00, 34.46it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 210/210 [00:05<00:00, 36.20it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 82/82 [00:04<00:00, 17.80it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 114/114 [00:06<00:00, 17.76it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_57
Sweep_58
Sweep_59
Sweep_60
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_SA_A1_C03.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:06<00:00,  3.26it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 26/26 [00:06<00:00,  3.90it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:06<00:00,  3.48it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 34/34 [00:06<00:00,  5.19it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  4.97it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.78it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:04<00:00,  1.84it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:05<00:00,  2.83it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_6
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_SA_A1_C05.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.08it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.77s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_68
Sweep_70
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_SA_A1_C06.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 31/31 [00:03<00:00,  8.97it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 40/40 [00:04<00:00,  9.79it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 45/45 [00:05<00:00,  8.82it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 28/28 [00:04<00:00,  5.81it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.77it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.79it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.78it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.84it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.46it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 30/30 [00:05<00:00,  5.85it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 44/44 [00:05<00:00,  7.98it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.17s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 26/26 [00:04<00:00,  6.12it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.58it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:05<00:00,  4.39it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 32/32 [00:05<00:00,  5.55it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 37/37 [00:05<00:00,  6.30it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 41/41 [00:06<00:00,  6.65it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 37/37 [00:06<00:00,  5.88it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:06<00:00,  4.05it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.53it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 22/22 [00:06<00:00,  3.52it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:04<00:00,  2.42it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.53it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.15it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:05<00:00,  2.94it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 26/26 [00:05<00:00,  4.93it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.14it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 32/32 [00:04<00:00,  6.80it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 36/36 [00:04<00:00,  8.00it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 40/40 [00:04<00:00,  8.83it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 33/33 [00:04<00:00,  7.05it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 30/30 [00:04<00:00,  6.32it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:04<00:00,  3.72it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.80it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_18
Sweep_19
Sweep_2
Sweep_20
Sweep_3
Sweep_4
Sweep_64
Sweep_66
Sweep_72
Sweep_73
Sweep_74
Sweep_75
Sweep_76
Sweep_77
Sweep_78
Sweep_79
Sweep_8
Sweep_80
Sweep_81
Sweep_82
Sweep_83
Sweep_84
Sweep_85
Sweep_87
Sweep_88
Sweep_89
Sweep_9
Sweep_90
Sweep_91
Sweep_92
Sweep_93
Sweep_94
Sweep_95
Sweep_96
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_SA_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 29/29 [00:04<00:00,  5.84it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 79/79 [00:05<00:00, 15.01it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 93/93 [00:05<00:00, 16.80it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 104/104 [00:05<00:00, 18.44it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 115/115 [00:05<00:00, 19.24it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 126/126 [00:06<00:00, 20.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.91it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 77/77 [00:06<00:00, 11.93it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 91/91 [00:06<00:00, 14.40it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 107/107 [00:05<00:00, 18.26it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 121/121 [00:05<00:00, 22.01it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 133/133 [00:05<00:00, 25.33it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]

Sweep_100
Sweep_101
Sweep_102
Sweep_103
Sweep_104
Sweep_105
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_88
Sweep_89
Sweep_90
Sweep_99
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_SA_A1_C08.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 104/104 [00:03<00:00, 31.41it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 121/121 [00:03<00:00, 30.61it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 136/136 [00:04<00:00, 30.38it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 151/151 [00:04<00:00, 33.86it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 160/160 [00:04<00:00, 35.70it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 172/172 [00:04<00:00, 37.37it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 182/182 [00:04<00:00, 38.57it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 34/34 [00:03<00:00, 10.57it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 58/58 [00:04<00:00, 12.18it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 85/85 [00:04<00:00, 17.37it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_46
Sweep_47
Sweep_48
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_SA_A1_C10.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████| 108/108 [00:05<00:00, 21.41it/s]

Fitting failed for sweep Sweep_0: Length of values (109) does not match length of index (108)

Spike: 100%|███████████████████████████████████████████████████████████████████████████| 88/88 [00:05<00:00, 17.30it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 106/106 [00:05<00:00, 19.83it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 85/85 [00:05<00:00, 15.92it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 92/92 [00:05<00:00, 16.55it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 101/101 [00:05<00:00, 17.35it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 107/107 [00:06<00:00, 17.42it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 112/112 [00:06<00:00, 17.77it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 115/115 [00:06<00:00, 17.57it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 115/115 [00:06<00:00, 17.97it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 114/114 [00:06<00:00, 17.94it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 60/60 [00:04<00:00, 13.59it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 121/121 [00:05<00:00, 22.60it/s]

Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_2
Sweep_3
Sweep_39
Sweep_4
Sweep_40
Sweep_41
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_SA_A1_C11.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.58it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.19it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.80it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.47it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.64it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.73it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_151
Sweep_157
Sweep_158
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_SA_A1_C14.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_115
Sweep_116
Sweep_119
Sweep_12
Sweep_120
Sweep_13
Sweep_14
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M10\M10_SA_A1_C15.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.48s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.48s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.48s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.09it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.09it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]

Sweep_101
Sweep_102
Sweep_103
Sweep_104
Sweep_105
Sweep_106
Sweep_107
Sweep_108
Sweep_109
Sweep_110
Sweep_111
Sweep_112
Sweep_113
Sweep_114
Sweep_115
Sweep_116
Sweep_117
Sweep_118
Sweep_119
Sweep_120
Sweep_121
Sweep_122
Sweep_123
Sweep_124
Sweep_125
Sweep_126
Sweep_127
Sweep_128
Sweep_129
Sweep_18
Sweep_97
Sweep_98
file added

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

In [66]:
M10_df.tail()

,ramp_amp,inflection_time,inflection_amp,peak_amp,peak_width,peak_sharpness,exp_lambda,exp_const,isi,r_squared_ramp,r_squared_exp,Sweep_#,file_name,dendriticType,SomaLayerLoc,brainOrigin,Weight,Sex,Age,Species
0,5.624321,0.70,-51.312257,35.900880,1.05,2.520752,1.306941,-55.665414,0.0,0.999225,0.998378,Sweep_129,M10_SA_A1_C15,NA,NA,PFC,5.1,M,5.11,Macaca fascicularis
1,5.624321,0.70,-51.312257,35.900880,1.05,2.520752,1.306941,-55.665414,NaN,0.999225,0.998378,Sweep_129,M10_SA_A1_C15,NA,NA,PFC,5.1,M,5.11,Macaca fascicularis
0,2.568433,0.75,-33.911134,30.499268,1.05,2.270508,0.935556,-49.614184,NaN,0.945924,0.999244,Sweep_18,M10_SA_A1_C15,NA,NA,PFC,5.1,M,5.11,Macaca fascicularis
0,3.764814,0.70,-49.493409,37.994386,1.05,3.094482,1.342215,-54.548994,NaN,0.996289,0.998179,Sweep_97,M10_SA_A1_C15,NA,NA,PFC,5.1,M,5.11,Macaca fascicularis
0,3.466705,0.75,-48.797609,37.640382,1.05,3.399658,1.288728,-54.044722,NaN,0.764764,0.998636,Sweep_98,M10_SA_A1_C15,NA,NA,PFC,5.1,M,5.11,Macaca fascicularis

In [14]:
file_paths7 = get_file_paths(r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M11")
M11_df = monkey_df(file_paths7, 130)

save_dataframe_to_pickle(M11_df, r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M11_df.pkl")

C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M11\M11_SA_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.81it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.93it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.67it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.66it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.47s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.38it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_42
Sweep_43
Sweep_44
Sweep_45
Sweep_46
Sweep_47
Sweep_7
Sweep_8
Sweep_9

In [15]:
M11_df.tail()

,ramp_amp,inflection_time,inflection_amp,peak_amp,peak_width,peak_sharpness,exp_lambda,exp_const,isi,r_squared_ramp,r_squared_exp,Sweep_#,file_name,dendriticType,SomaLayerLoc,brainOrigin,Weight,Sex,Age,Species
3,4.384619,0.65,-40.948487,24.346924,0.85,2.746582,1.752491,-56.577616,41.75,0.947650,0.996799,Sweep_9,M11_SA_A1_C02,S,3,V1,10.6,M,12.69,Macaca mulatta
4,4.359746,0.65,-39.117433,22.375489,0.85,2.416992,1.732443,-56.075213,41.95,0.951499,0.996658,Sweep_9,M11_SA_A1_C02,S,3,V1,10.6,M,12.69,Macaca mulatta
5,4.354973,0.70,-40.454102,22.973633,0.85,2.261353,1.809240,-56.006935,40.95,0.950477,0.996328,Sweep_9,M11_SA_A1_C02,S,3,V1,10.6,M,12.69,Macaca mulatta
6,3.985642,0.70,-40.075684,22.393799,0.85,2.340698,1.760836,-55.809571,47.15,0.960559,0.996670,Sweep_9,M11_SA_A1_C02,S,3,V1,10.6,M,12.69,Macaca mulatta
7,4.839124,0.75,-37.615968,20.031739,0.85,2.011108,1.737839,-55.304615,NaN,0.959954,0.996909,Sweep_9,M11_SA_A1_C02,S,3,V1,10.6,M,12.69,Macaca mulatta

In [67]:
file_paths8 = get_file_paths(r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12")
M12_df = monkey_df(file_paths8, 131)

save_dataframe_to_pickle(M12_df, r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12_df.pkl")

C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_JS_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 163/163 [00:03<00:00, 46.08it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 174/174 [00:03<00:00, 49.60it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 177/177 [00:03<00:00, 49.30it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 177/177 [00:03<00:00, 46.58it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 144/144 [00:03<00:00, 38.13it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  4.05it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 125/125 [00:03<00:00, 36.79it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 147/147 [00:03<00:00, 42.41it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_41
Sweep_42
Sweep_43
Sweep_44
Sweep_45
Sweep_46
Sweep_47
Sweep_48
Sweep_49
Sweep_50
Sweep_51
Sweep_52
Sweep_53
Sweep_54
Sweep_55
Sweep_56
Sweep_57
Sweep_58
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_JS_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:03<00:00,  4.99it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.75it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:03<00:00,  5.79it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 22/22 [00:03<00:00,  5.84it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:03<00:00,  6.07it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.39it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  4.08it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.39it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_154
Sweep_155
Sweep_156
Sweep_6
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_JS_A1_C04.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.44s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.19it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_28
Sweep_29
Sweep_30
Sweep_31
Sweep_32
Sweep_33
Sweep_34
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_JS_A1_C05.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.33s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.44s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_55
Sweep_56
Sweep_57
Sweep_58
Sweep_59
Sweep_60
Sweep_61
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_JS_A1_C08.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_4
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_JS_A1_C11.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 133/133 [00:03<00:00, 36.77it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 136/136 [00:03<00:00, 39.79it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 98/98 [00:03<00:00, 29.37it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 58/58 [00:03<00:00, 16.49it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 18/18 [00:03<00:00,  5.19it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 88/88 [00:03<00:00, 26.30it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 106/106 [00:03<00:00, 30.29it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 119/119 [00:03<00:00, 32.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 128/128 [00:03<00:00, 33.29it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_30
Sweep_32
Sweep_33
Sweep_34
Sweep_5
Sweep_6
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_JS_A1_C12.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 30/30 [00:03<00:00,  8.01it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 152/152 [00:04<00:00, 37.30it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 158/158 [00:04<00:00, 38.03it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 134/134 [00:04<00:00, 32.55it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.11it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.13it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_5
Sweep_6
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_JS_A1_C14.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.06it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.64it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Fitting failed for sweep Sweep_11: could not broadcast input array from shape (12,) into shape (20,)

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.95it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.06it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 31/31 [00:03<00:00,  7.77it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 34/34 [00:03<00:00,  8.51it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 37/37 [00:04<00:00,  9.11it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  2.99it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  2.95it/s]

Fitting failed for sweep Sweep_9: could not broadcast input array from shape (14,) into shape (20,)
Sweep_10
Sweep_3
Sweep_4
Sweep_5
Sweep_6
Sweep_7
Sweep_8
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_SA_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.88s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_47
Sweep_48
Sweep_49
Sweep_50
Sweep_51
Sweep_52
Sweep_53
Sweep_54
Sweep_55
Sweep_56
Sweep_57
Sweep_58
Sweep_59
Sweep_60
Sweep_61
Sweep_62
Sweep_63
Sweep_64
Sweep_65
Sweep_66
Sweep_67
Sweep_68
Sweep_69
Sweep_70
Sweep_71
Sweep_72
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_SA_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12
Sweep_84
Sweep_85
Sweep_86
Sweep_87
Sweep_88
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_SA_A1_C08.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.66s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_57
Sweep_58
Sweep_59
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_SA_A1_C09.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11
Sweep_12
Sweep_13
Sweep_14
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_SA_A1_C10.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.78it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_14
Sweep_26
Sweep_27
Sweep_28
Sweep_29
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_SA_A1_C11.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.67it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.76it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.32it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.04it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.53it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.53it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.16it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_102
Sweep_103
Sweep_104
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_SA_A1_C13.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_21
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M12\M12_SA_A1_C14.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]

Sweep_11
Sweep_12
Sweep_13
Sweep_14
file added

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

In [68]:
M12_df.tail()

,ramp_amp,inflection_time,inflection_amp,peak_amp,peak_width,peak_sharpness,exp_lambda,exp_const,isi,r_squared_ramp,r_squared_exp,Sweep_#,file_name,dendriticType,SomaLayerLoc,brainOrigin,Weight,Sex,Age,Species
1,6.263217,0.55,-38.110111,12.994629,0.55,3.976440,10.000000,-49.644095,NaN,0.997178,0.094598,Sweep_28,M12_SA_A1_C13,NA,NA,LIP,16.2,M,14.38,Macaca mulatta
0,3.142255,0.60,-44.312992,20.915285,0.75,2.908326,3.051178,-53.659981,NaN,0.985559,0.998535,Sweep_11,M12_SA_A1_C14,NA,NA,LIP,16.2,M,14.38,Macaca mulatta
0,4.129373,0.55,-45.716801,21.824709,0.75,3.527832,3.224466,-52.940475,NaN,0.987189,0.997524,Sweep_12,M12_SA_A1_C14,NA,NA,LIP,16.2,M,14.38,Macaca mulatta
0,4.780384,0.50,-49.348392,20.988527,0.70,4.699708,3.410526,-55.296365,NaN,0.991280,0.996018,Sweep_13,M12_SA_A1_C14,NA,NA,LIP,16.2,M,14.38,Macaca mulatta
0,5.296567,0.55,-51.661625,18.608156,0.75,3.240968,3.537176,-55.982380,NaN,0.996950,0.991853,Sweep_14,M12_SA_A1_C14,NA,NA,LIP,16.2,M,14.38,Macaca mulatta

In [71]:
file_paths9 = get_file_paths(r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19")
M19_df = monkey_df(file_paths9, 147)

save_dataframe_to_pickle(M19_df, r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19_df.pkl")

C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_JS_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_36
Sweep_39
Sweep_44
Sweep_45
Sweep_46
Sweep_47
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_JS_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.73it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.20it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.19it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.74it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.74it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.75it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.75it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_5
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_JS_A1_C03.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12
Sweep_13
Sweep_14
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_JS_A1_C04.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.47it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.47it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.83it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.49it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.06it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.51it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.19it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_JS_A1_C05.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.50it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.65it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.91it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.06it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 38/38 [00:03<00:00, 11.47it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.84s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.72it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.20it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.55it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.81s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_7
Sweep_8
Sweep_87
Sweep_88
Sweep_89
Sweep_9
Sweep_90
Sweep_91
Sweep_92
Sweep_93
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_JS_A1_C06.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12
Sweep_13
Sweep_14
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_JS_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.75it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.52it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.10it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.21it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.20it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_60
Sweep_62
Sweep_63
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_JS_A1_C08.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.79s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.72it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.77it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.71it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.58it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.05it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.33it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_175
Sweep_176
Sweep_177
Sweep_178
Sweep_179
Sweep_30
Sweep_31
Sweep_32
Sweep_33
Sweep_34
Sweep_35
Sweep_36
Sweep_37
Sweep_38
Sweep_39
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_JS_A1_C09.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.22it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.71it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.74it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.49it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.71it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.60it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_6
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_JS_A1_C10.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:02<00:00,  4.53it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:03<00:00,  4.58it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.52it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:03<00:00,  5.32it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 24/24 [00:03<00:00,  6.51it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.08it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.06it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.49it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.12it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_8
Sweep_87
Sweep_88
Sweep_89
Sweep_9
Sweep_90
Sweep_91
Sweep_92
Sweep_93
Sweep_94
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_JS_A1_C11.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.74it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.71it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_JS_A1_C13.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 62/62 [00:03<00:00, 19.04it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 80/80 [00:03<00:00, 23.38it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 97/97 [00:03<00:00, 25.72it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 114/114 [00:04<00:00, 27.46it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 129/129 [00:04<00:00, 32.02it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.71it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 44/44 [00:03<00:00, 12.26it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_53
Sweep_54
Sweep_55
Sweep_56
Sweep_57
Sweep_58
Sweep_59
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_JS_A1_C14.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.73it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.69it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.09it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.11it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.51it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.81s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_18
Sweep_65
Sweep_66
Sweep_67
Sweep_68
Sweep_69
Sweep_70
Sweep_71
Sweep_72
Sweep_73
Sweep_74
Sweep_75
Sweep_76
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_JS_A1_C15.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.12it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.52it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.85it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:02<00:00,  4.44it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.68it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.75it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.97it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  3.72it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.36it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.20it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.21it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.25it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.27it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.01it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.22it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.03it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  3.50it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_18
Sweep_19
Sweep_20
Sweep_21
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_30
Sweep_31
Sweep_32
Sweep_33
Sweep_34
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_MM_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  3.82it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 22/22 [00:03<00:00,  5.82it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:03<00:00,  4.32it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.37it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.25it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.03it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.65it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  4.18it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.95it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.85it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  4.10it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_1
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_MM_A1_C02.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_MM_A1_C03.nwb
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_MM_A1_C05.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.12it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  3.77it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.84it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.00it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.25it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11
Sweep_17
Sweep_18
Sweep_19
Sweep_20
Sweep_21
Sweep_22
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_MM_A1_C06.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 39/39 [00:03<00:00,  9.98it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 48/48 [00:04<00:00, 11.75it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 61/61 [00:04<00:00, 14.58it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 73/73 [00:04<00:00, 16.88it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 86/86 [00:04<00:00, 20.16it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.31s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.76it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.81it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 56/56 [00:03<00:00, 16.12it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 65/65 [00:03<00:00, 17.63it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.35it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_67
Sweep_68
Sweep_69
Sweep_70
Sweep_71
Sweep_72
Sweep_73
Sweep_74
Sweep_85
Sweep_86
Sweep_87
Sweep_88
Sweep_89
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_MM_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.77s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 58/58 [00:03<00:00, 16.95it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 73/73 [00:03<00:00, 19.67it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 87/87 [00:03<00:00, 22.04it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.85s/it]

Sweep_13
Sweep_14
Sweep_30
Sweep_31
Sweep_32
Sweep_33
Sweep_34
Sweep_9
Sweep_91
Sweep_94
Sweep_95
Sweep_96
Sweep_97
Sweep_98
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_MM_A1_C08.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.26s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.07it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.85s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_30
Sweep_31
Sweep_32
Sweep_33
Sweep_34
Sweep_35
Sweep_36
Sweep_37
Sweep_38
Sweep_39
Sweep_40
Sweep_41
Sweep_44
Sweep_45
Sweep_48
Sweep_49
Sweep_51
Sweep_52
Sweep_53
Sweep_54
Sweep_56
Sweep_57
Sweep_58
Sweep_59
Sweep_60
Sweep_61
Sweep_62
Sweep_63
Sweep_64
Sweep_65
Sweep_66
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_MM_A1_C09.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_17
Sweep_18
Sweep_19
Sweep_20
Sweep_21
Sweep_22
Sweep_78
Sweep_79
Sweep_80
Sweep_81
Sweep_82
Sweep_83
Sweep_84
Sweep_85
Sweep_86
Sweep_87
Sweep_88
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_MM_A1_C10.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.39it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  4.27it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 14/14 [00:02<00:00,  4.69it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.84it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.83it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.80s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.47it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_18
Sweep_19
Sweep_29
Sweep_30
Sweep_31
Sweep_32
Sweep_33
Sweep_34
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_MM_A1_C11.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.20it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_80
Sweep_82
Sweep_83
Sweep_84
Sweep_85
Sweep_86
Sweep_87
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_SA_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.47it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.81it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.34it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11
Sweep_12
Sweep_13
Sweep_14
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_SA_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_65
Sweep_66
Sweep_75
Sweep_76
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_SA_A1_C03.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.78s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.21it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.53it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  4.31it/s]

Sweep_6
Sweep_66
Sweep_67
Sweep_68
Sweep_69
Sweep_7
Sweep_70
Sweep_71
Sweep_72
Sweep_73
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_SA_A1_C05.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_6
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_SA_A1_C06.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.16it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_6
Sweep_84
Sweep_85
Sweep_86
Sweep_87
Sweep_88
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_SA_A1_C08.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_55
Sweep_56
Sweep_59
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_SA_A1_C09.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M19\M19_SA_A1_C10.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.11it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:02<00:00,  4.50it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11
Sweep_12
Sweep_13
Sweep_14
file added

In [72]:
M19_df.tail()

,ramp_amp,inflection_time,inflection_amp,peak_amp,peak_width,peak_sharpness,exp_lambda,exp_const,isi,r_squared_ramp,r_squared_exp,Sweep_#,file_name,dendriticType,SomaLayerLoc,brainOrigin,Weight,Sex,Age,Species
8,1.006392,0.40,-32.806397,5.126953,0.40,6.530762,7.080046,-45.984471,179.90,0.909565,0.810322,Sweep_14,M19_SA_A1_C10,NA,NA,V1,14.6,M,14,Macaca fascicularis
9,1.422165,0.45,-30.914307,5.889893,0.40,5.783081,5.853469,-46.889182,56.20,0.907662,0.941953,Sweep_14,M19_SA_A1_C10,NA,NA,V1,14.6,M,14,Macaca fascicularis
10,1.713574,0.45,-29.846192,5.950928,0.40,5.493164,6.284264,-46.386262,263.10,0.955074,0.886901,Sweep_14,M19_SA_A1_C10,NA,NA,V1,14.6,M,14,Macaca fascicularis
11,1.909529,0.45,-30.212403,5.676270,0.35,5.187988,6.138267,-46.991332,138.65,0.989066,0.926262,Sweep_14,M19_SA_A1_C10,NA,NA,V1,14.6,M,14,Macaca fascicularis
12,1.524043,0.45,-30.059815,6.103516,0.40,5.844116,5.572046,-46.961211,NaN,0.885470,0.956144,Sweep_14,M19_SA_A1_C10,NA,NA,V1,14.6,M,14,Macaca fascicularis

In [73]:
file_paths10 = get_file_paths(r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20")
M20_df = monkey_df(file_paths10, 174)

save_dataframe_to_pickle(M20_df, r"C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20_df.pkl")

C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_JS_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.10it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 19/19 [00:03<00:00,  5.92it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.81it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 45/45 [00:03<00:00, 13.87it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 108/108 [00:03<00:00, 30.93it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 130/130 [00:03<00:00, 35.21it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 151/151 [00:03<00:00, 39.40it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_13
Sweep_14
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_JS_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.73it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 84/84 [00:03<00:00, 23.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 103/103 [00:03<00:00, 27.24it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 113/113 [00:03<00:00, 28.56it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 109/109 [00:03<00:00, 27.86it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 71/71 [00:03<00:00, 18.09it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 25/25 [00:03<00:00,  6.38it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.85s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.19it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_50
Sweep_51
Sweep_52
Sweep_53
Sweep_54
Sweep_55
Sweep_56
Sweep_57
Sweep_58
Sweep_59
Sweep_60
Sweep_61
Sweep_62
Sweep_63
Sweep_64
Sweep_65
Sweep_66
Sweep_67
Sweep_68
Sweep_69
Sweep_70
Sweep_71
Sweep_72
Sweep_73
Sweep_74
Sweep_75
Sweep_76
Sweep_77
Sweep_78
Sweep_79
Sweep_80
Sweep_81
Sweep_82
Sweep_83
Sweep_84
Sweep_85
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_JS_A1_C03.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 119/119 [00:03<00:00, 35.65it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 153/153 [00:03<00:00, 45.49it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 56/56 [00:03<00:00, 17.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 104/104 [00:03<00:00, 31.20it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 137/137 [00:03<00:00, 38.51it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 168/168 [00:03<00:00, 44.53it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 188/188 [00:03<00:00, 48.36it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 205/205 [00:04<00:00, 50.79it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.88it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 81/81 [00:03<00:00, 24.83it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

Sweep_0
Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_20
Sweep_21
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_45
Sweep_48
Sweep_50
Sweep_51
Sweep_52
Sweep_53
Sweep_54
Sweep_55
Sweep_56
Sweep_57
Sweep_58
Sweep_59
Sweep_60
Sweep_61
Sweep_62
Sweep_63
Sweep_64
Sweep_65
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_MM_A1_C01.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.67it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 174/174 [00:03<00:00, 50.06it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_14
Sweep_38
Sweep_39
Sweep_40
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_MM_A1_C02.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.90s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.88s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.76s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.81s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.82s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.75s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.70it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.76it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.20it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_151
Sweep_152
Sweep_153
Sweep_154
Sweep_155
Sweep_156
Sweep_157
Sweep_158
Sweep_159
Sweep_160
Sweep_161
Sweep_162
Sweep_163
Sweep_22
Sweep_23
Sweep_24
Sweep_25
Sweep_26
Sweep_27
Sweep_28
Sweep_29
Sweep_30
Sweep_31
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_MM_A1_C03.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.79s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.88s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.80s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.82s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 50/50 [00:03<00:00, 15.21it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  3.93it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 49/49 [00:03<00:00, 14.98it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 62/62 [00:03<00:00, 18.58it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 64/64 [00:03<00:00, 18.48it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 79/79 [00:03<00:00, 22.04it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 90/90 [00:03<00:00, 23.83it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 101/101 [00:03<00:00, 25.78it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 110/110 [00:04<00:00, 27.49it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 121/121 [00:03<00:00, 30.92it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 133/133 [00:04<00:00, 32.79it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 142/142 [00:04<00:00, 34.66it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_115
Sweep_116
Sweep_118
Sweep_119
Sweep_120
Sweep_121
Sweep_122
Sweep_123
Sweep_13
Sweep_138
Sweep_139
Sweep_14
Sweep_140
Sweep_141
Sweep_142
Sweep_143
Sweep_144
Sweep_145
Sweep_146
Sweep_147
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_MM_A1_C04.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.13it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.09it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_18
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_MM_A1_C05.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.19it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.20it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.11s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/it]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_67
Sweep_68
Sweep_69
Sweep_70
Sweep_71
Sweep_72
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_MM_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.54it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.76it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.19it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.87it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_18
Sweep_19
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_SA_A1_C01.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.85it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.83it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.56it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.67it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]

Fitting failed for sweep Sweep_62: All fits failed.

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/it]

Fitting failed for sweep Sweep_63: All fits failed.

Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.13it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.77it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  4.13it/s]

Sweep_0
Sweep_10
Sweep_11
Sweep_12
Sweep_5
Sweep_6
Sweep_64
Sweep_66
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_SA_A1_C02.nwb

Spike: 100%|█████████████████████████████████████████████████████████████████████████| 216/216 [00:03<00:00, 55.50it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.22it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.71it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.71it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.26it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 56/56 [00:03<00:00, 14.35it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 102/102 [00:04<00:00, 25.00it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 141/141 [00:04<00:00, 34.00it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 172/172 [00:04<00:00, 40.71it/s]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Python312\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

Sweep_0
Sweep_1
Sweep_2
Sweep_3
Sweep_4
Sweep_5
Sweep_6
Sweep_7
Sweep_8
Sweep_9
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_SA_A1_C03.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 136/136 [00:04<00:00, 32.49it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.88s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.93s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 59/59 [00:03<00:00, 16.93it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 95/95 [00:03<00:00, 25.09it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 120/120 [00:04<00:00, 25.36it/s]

Sweep_10
Sweep_36
Sweep_37
Sweep_38
Sweep_39
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_SA_A1_C04.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.84s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.14it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.74it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.75it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.73it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_18
Sweep_19
Sweep_52
Sweep_53
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_SA_A1_C05.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.12it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:03<00:00,  6.32it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 22/22 [00:05<00:00,  3.97it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:05<00:00,  4.07it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 21/21 [00:05<00:00,  3.64it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 17/17 [00:05<00:00,  2.90it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.47it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.31it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.92s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.85s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_18
Sweep_19
Sweep_34
Sweep_35
Sweep_36
Sweep_37
Sweep_38
Sweep_39
Sweep_40
Sweep_41
Sweep_42
Sweep_43
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_SA_A1_C06.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.24it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 53/53 [00:05<00:00,  9.33it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 63/63 [00:05<00:00, 12.12it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 76/76 [00:04<00:00, 15.35it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.83it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_SA_A1_C07.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/it]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 13/13 [00:02<00:00,  4.55it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 28/28 [00:04<00:00,  6.75it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 35/35 [00:04<00:00,  8.30it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')

Sweep_50
Sweep_52
Sweep_6
Sweep_7
Sweep_8
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_SA_A1_C08.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.43it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.05it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:03<00:00,  3.56it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.54it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  2.99it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.84s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.86it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.29it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.79it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.09it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_27
Sweep_30
Sweep_31
Sweep_5
Sweep_6
Sweep_7
Sweep_8
Sweep_9
file added
C:\Users\david\Documents\Voytek Research\nwb files\primate Dataset\M20\M20_SA_A1_C09.nwb

C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 53/53 [00:03<00:00, 14.57it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 69/69 [00:04<00:00, 14.56it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 85/85 [00:04<00:00, 17.75it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 99/99 [00:04<00:00, 20.44it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 111/111 [00:04<00:00, 22.23it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 124/124 [00:05<00:00, 23.98it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 133/133 [00:05<00:00, 25.36it/s]
Spike: 100%|█████████████████████████████████████████████████████████████████████████| 137/137 [00:05<00:00, 25.45it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 94/94 [00:05<00:00, 17.26it/s]
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 35/35 [00:05<00:00,  6.30it/s]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]
Spike: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/it]
C:\Users\david\spikeparam\spikeparam\patch\fit\fit.py:228: UserWarning: No spikes detected.
  warnings.warn('No spikes detected.')
Spike: 100%|███████████████████████████████████████████████████████████████████████████| 37/37 [00:04<00:00,  7.74it/s]

Sweep_10
Sweep_11
Sweep_12
Sweep_13
Sweep_14
Sweep_15
Sweep_16
Sweep_17
Sweep_18
Sweep_19
Sweep_72
Sweep_73
Sweep_9
file added